### PR TITLE
put history view into the correct state after a successful pull 

### LINKED ISSUE #2737: history UI out of sync with repository after pulling with merge
### Description

Commits that were created and pushed to remote repository from other people are not shown in the History tab.

### Version

**GitHub Desktop version:** 0.8.2

**OS version:** Microsoft Windows [10.0.14393]

### Steps to Reproduce

1. Commit **A** on local repository on **Mac** and push to remote (shared bare repository not on Github)
1. Commit **B** on local repository on **Windows** before pulling **A** from remote
1. Pull from remote, merge and push changes back to remote

**Expected behavior:** Both commit **A** and **B** should appear in the History tab.

**Actual behavior:** On Mac, both commits are shown, but on Windows only the local commit and merge commit is shown.

**Reproduces how often:** Only initially after pulling the changes from remote. After restarting, all the commits are properly shown again.

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2737 

The problem manifests itself in a couple of ways:

 - you have some existing history to look at
 - you perform a pull which merges in some remote commits

Because of how `loadHistory` merges new commits with the current history, you can find yourself in a situation where remote commits (which occurred _before_ the tip of the current history) are not loaded into this array of commits.

https://github.com/desktop/desktop/blob/f12ff8c4775904bbb44ef6fdb78b26e734c14455/app/src/lib/stores/git-store.ts#L156-L171

The quick fix for this is to nuke the history and let it reload, but results in a flicker when you are viewing the list. This is also probably bad for scenarios where you've scrolled down the history.

The better fix for this is to reconcile the two histories manually. Given the remote ref and local branch should share a common ancestor, we should be able to invalidate a subset of the commits currently loaded: 

```shellsession
$ git merge-base master origin/master
b7641d1de6ca0b05b0279266df9120f6a945bf52
```

This also means that an existing selected commit is remembered, even after moving the history around.

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -1961,16 +1962,26 @@ export class AppStore {
       }
 
       const state = this.getRepositoryState(repository)
+      const tip = state.branchesState.tip
 
-      if (state.branchesState.tip.kind === TipState.Unborn) {
+      if (tip.kind === TipState.Unborn) {
         throw new Error('The current branch is unborn.')
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/app-store.ts]: I think we should have a more user-friendly error message here. Something that will give them the path to success.

File: app/src/lib/stores/git-store.ts [hunk 2]
```diff
@@ -138,6 +138,52 @@ export class GitStore {
     return this.emitter.on('did-error', fn)
   }
 
+  /**
+   * Reconcile the local history view with the repository state
+   * after a pull has completed, to include merged remote commits.
+   */
+  public async reconcileHistory(mergeBase: string): Promise<void> {
+    if (this._history.length === 0) {
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/git-store.ts]: 👍 for the explicit check!

File: app/src/lib/stores/git-store.ts [hunk 3]
```diff
@@ -138,6 +138,52 @@ export class GitStore {
...
+    if (this.requestsInFight.has(LoadingHistoryRequestKey)) {
+      return
+    }
+
+    this.requestsInFight.add(LoadingHistoryRequestKey)
+
+    const commits = await this.performFailableOperation(() =>
+      getCommits(this.repository, `HEAD..${mergeBase}`, CommitBatchSize)
+    )
+    if (!commits) {
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/git-store.ts]: Explicitly check for`null` or `undefined` (can't actually tell what the type is on dotcom).

File: app/src/lib/stores/app-store.ts (hunk 1 above)
Comment (shiftkey) [reply app/src/lib/stores/app-store.ts]: We really shouldn't let the user get into this state in the first place (this is driven from the push/pull/fetch contextual button).

File: app/src/lib/stores/git-store.ts (hunk 3 above)
Comment (shiftkey) [reply app/src/lib/stores/git-store.ts]: `undefined`, but :thumbsup: anyway

File: app/src/lib/stores/app-store.ts (hunk 1 above)
Comment (shiftkey) [reply app/src/lib/stores/app-store.ts]: But it's also unrelated to this change. Feel free to open an issue if you want to take it further.

**Comment by shiftkey** [comment]
:apple:

**Comment by janoveve** [comment]
Can I say Number 9 over n over again? What will appen?
