### PR TITLE
Loosen detection of web flow committer on GHES

### LINKED ISSUE #13848: GitHub Enterprise User Showing
### Describe the bug
GitHub Enterprise User Showing in commit history

### Version & OS

Version 2.9.7-beta2 (x64) - Windows 10

### Steps to reproduce the behavior

1. On a GHE repo, got to commit history

### Expected behavior

GitHub History matches GHES webpage

### Actual behavior

GitHub History does not match GHES webpage

### Screenshots

image

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

This seems to have been introduced with the  changes to add Avatars from GHES 3.0+. https://github.com/desktop/desktop/pull/13719

We are currently on GHES 3.1.14

### PR DESCRIPTION
**Pull request by niik**
Closes #13848

## Description

Turns out the email address used for the web flow committer on GHES is admin-configurable so we can't rely on it matching the domain of the GHES instance.

I did briefly consider trying match on a substring of the domain but while likely rare it is possible for a company to have their GHES hosted on `domainA.com` while having their noreply emails originating from `domainB.com`.

## Release notes

Notes: [Fixed] Hide committer for commits made using the web flow on GitHub Enterprise Server

### CODE REVIEW

**Review by sergiou87 — APPROVED** [review]
I think this is the safest option even if we have to update it with newer flavors of GHE as you mention in the comment 😅 

🚀

File: app/src/lib/web-flow-committer.ts [hunk 1]
```diff
@@ -31,9 +31,19 @@ export function isWebFlowCommitter(
     return true
   }
 
-  if (name === 'GitHub Enterprise') {
-    const host = new URL(endpoint).host.toLowerCase()
-    return email.endsWith(`@${host}`)
+  if (endpoint !== getDotComAPIEndpoint() && name === 'GitHub Enterprise') {
```
Comment (say25) [inline app/src/lib/web-flow-committer.ts:34]: I think this is safe, we could I'm not sure if email starts with `ghe-noreply` would also work or be better/worse?

**Review by say25 — APPROVED** [review]

File: app/src/lib/web-flow-committer.ts (hunk 1 above)
Comment (niik) [reply app/src/lib/web-flow-committer.ts:34]: It looks like that part is configurable as well unfortunately.

Comment (say25) [reply app/src/lib/web-flow-committer.ts:34]: 🤯

**Review by say25 — APPROVED** [review]
