### PR TITLE
fix stash diff viewer button order (for mac)

### LINKED ISSUE #7273: [Stashing] macOS button order is incorrect
This issue was brought up in review of https://github.com/desktop/desktop/pull/7210#discussion_r274839393. 

https://github.com/desktop/desktop/blob/686fbbc04f9b2c229ad98799dd0c4d63c8df5d01/app/src/ui/stashing/stash-diff-viewer.tsx#L1

> 🎨 can we add some context here about why we've needed to do this?

> I concur, especially since I believe that through subverting this rule we've created the wrong order on Windows. I'll comment about that below.

Let's do a bit of validation here to see if this gives the wrong order on Windows. If so, we need to yank this rule and follow our current conventions.

### PR DESCRIPTION
**Pull request by outofambit**
fixes #7273

Windows (i spoofed windows in code locally):
Screen Shot 2019-04-24 at 2 10 34 PM

Mac:
Screen Shot 2019-04-24 at 2 09 28 PM

### CODE REVIEW

File: app/src/ui/stashing/stash-diff-viewer.tsx [hunk 1]
```diff
@@ -94,20 +94,26 @@ const Header: React.SFC<{
...
       <h3>Stashed changes</h3>
-      <ButtonGroup destructive={true}>
-        <Button onClick={onSubmitClick} type="submit">
+      {/*
+      this is false because ButtonGroup assumes the submit button
+      performs the destructive action. In this case the destructive
+      action is performed by the non-submit button so we lie to the
+      props to get the correct button ordering
+       */}
+      <ButtonGroup destructive={false}>
```
Comment (billygriffin) [inline app/src/ui/stashing/stash-diff-viewer.tsx]: I think this may work just fine without the destructive false, unless I'm missing something?

Comment (outofambit) [reply app/src/ui/stashing/stash-diff-viewer.tsx]: it would! i wanted to pass it explicitly (and with the comment above it) so the intent was super clear 😄

Comment (iAmWillShepherd) [reply app/src/ui/stashing/stash-diff-viewer.tsx]: Moving this comment outside of the return statement will help make the code a bit more readable.

File: app/src/ui/stashing/stash-diff-viewer.tsx [hunk 2]
```diff
@@ -109,14 +109,11 @@ const Header: React.SFC<{
   dispatcher: Dispatcher
   isWorkingTreeClean: boolean
 }> = props => {
-  const { dispatcher, repository, stashEntry, isWorkingTreeClean } = props
-
-  const onClearClick = () => {
-    dispatcher.dropStash(repository, stashEntry)
+  const onDiscardClick = () => {
+    props.dispatcher.dropStash(props.repository, props.stashEntry)
```
Comment (iAmWillShepherd) [inline app/src/ui/stashing/stash-diff-viewer.tsx]: `dispatcher`, `repository`, and `stashEntry` can be destructured to reduce the amount of `props.<field>` expressions.

Comment (iAmWillShepherd) [reply app/src/ui/stashing/stash-diff-viewer.tsx]: I addressed this in c8956f0 since I broke the build with my previous merge.

File: app/src/ui/stashing/stash-diff-viewer.tsx (hunk 1 above)
Comment (outofambit) [reply app/src/ui/stashing/stash-diff-viewer.tsx]: done in https://github.com/desktop/desktop/pull/7392/commits/bb022a458aac3d3a75188306c4ec12fc574b0cbc
