### PR TITLE
Send IPC messages from menu over webContents channel rather than broadcast

### LINKED ISSUE #1603: Invoking certain menu items breaks Aero Snap state
**GitHub Desktop version:** 

0.5.4

**OS version:** 

Windows 10 1703

### Steps to Reproduce

1. Snap the Github Desktop window to half your screen using Win+Left/Right keys
1. Open any Dialog (About, Clone Repo, Add repo, etc)

**Actual behaviour:**

http://i.imgur.com/aruOJ5S.gifv

### PR DESCRIPTION
**Pull request by niik**
For some unknown reason dispatching over ipcMain causes the ui window to restore its position if snapped.

Fixes #1603

### CODE REVIEW

File: app/src/main-process/menu/build-default-menu.ts [hunk 1]
```diff
@@ -307,10 +307,14 @@ export function buildDefaultMenu(sharedProcess: SharedProcess): Electron.Menu {
...
+type ClickHandler = (menuItem: Electron.MenuItem, browserWindow: Electron.BrowserWindow, event: Electron.Event) => void
+
 /**
  * Utility function returning a Click event handler which, when invoked, emits
  * the provided menu event over IPC.
  */
-function emit(name: MenuEvent): () => void {
-  return () => ipcMain.emit('menu-event', { name })
+function emit(name: MenuEvent): ClickHandler {
+  return (menuItem, window) => {
```
Comment (shiftkey) [inline app/src/main-process/menu/build-default-menu.ts]: I can't see a use for `menuItem` - does that need to be defined here?
