### PR TITLE
"Go to Summary" Action

### LINKED ISSUE #1719: Add "Go to Commit Message" keyboard shortcut
### Description
Cmd-Shift-C, to bring the commit message textfield into focus, is probably my most-used shortcut in the old Desktop. I'd love to have it in new Desktop.

### Version
**GitHub Desktop version:** 0.5.3
**OS version:** macOS 10.12.5

### Steps to Reproduce
1. Select file in Changes list
2. Press Cmd-Shift-C (or something else)

**Expected behaviour:** Bring commit message text field into focus

**Actual behaviour:** Nothing

### PR DESCRIPTION
**Pull request by bruncun**
Happy Friday!

This pull request resolves #1719, adding a "Go to Summary" menu item that focuses on the summary message input. This was a feature of Desktop Classic that some users have requested be added to GitHub Desktop. Currently, when the app is selected but unfocused, it takes 7 tab inputs to select the summary input; this feature allows users to focus on the input in a single keystroke (Cmd or Ctrl S). The keyboard shortcut use to be Cmd/Ctrl+Shift+C, but that shortcut was reassigned to "Compare on Github", so I went with Cmd/Ctrl+S. I also went with "Go to Summary" to reflect the UI's language.

This is my first significant contribution to a major OSS project, so all feedback is appreciated. I mostly duplicated "Show Changes" behavior and added a document-emitted `go-to-summary` custom event. I haven't worked with Electron before, so I'm not entirely sure if this implementation is the best way to communicate between the main process and UI.

I also wasn't sure whether this feature merited test coverage. Looking over the existing coverage, it didn't seem like it was necessary for a UI feature like this.

Have a great weekend!

### CODE REVIEW

File: app/src/ui/app.tsx [hunk 1]
```diff
@@ -358,6 +360,21 @@ export class App extends React.Component<IAppProps, IAppState> {
     })
   }
 
+  private goToSummary() {
```
Comment (bruncun) [inline app/src/ui/app.tsx]: This method duplicates `showChanges` but also emits an event when `changeRepositorySection` is resolved. It could be made DRY if `showChanges` is refactored to return `changeRepositorySection`'s promise.

File: app/src/main-process/menu/build-default-menu.ts [hunk 2]
```diff
@@ -150,6 +150,12 @@ export function buildDefaultMenu(
         click: emit('show-branches'),
       },
       separator,
+      {
+        label: __DARWIN__ ? 'Go to Summary' : 'Go to &Summary',
+        id: 'go-to-summary',
+        accelerator: 'CmdOrCtrl+S',
```
Comment (say25) [inline app/src/main-process/menu/build-default-menu.ts]: Feels a lot like save :/ but I cant think of anything better

Comment (bruncun) [reply app/src/main-process/menu/build-default-menu.ts]: I knowww. 😕

Comment (say25) [reply app/src/main-process/menu/build-default-menu.ts]: image

Maybe `CmdOrCtrl+3` would make more sense?

Comment (jdiago) [reply app/src/main-process/menu/build-default-menu.ts]: In a way, you can think of committing as saving a change to the repo so `CmdOrCtrl+S` sort of makes sense since a commit message is required.

1. `CmdOrCtrl+S`
2. Write a commit message
3. `CmdOrCtrl+Enter`

Comment (say25) [reply app/src/main-process/menu/build-default-menu.ts]: @desktop/maintainers care to weigh in?

Comment (say25) [reply app/src/main-process/menu/build-default-menu.ts]: I agree it makes sense under View

Comment (say25) [reply app/src/main-process/menu/build-default-menu.ts]: `CmdOrCtrl+G` Or `CmdOrCtrl+3` (1 and 2 also jump in the UI) work for me. We can always change it later. Just a touch worried if we add another “Go to X” menu item

Comment (shiftkey) [reply app/src/main-process/menu/build-default-menu.ts]: The commit summary element is within the Changes tab, so I'd rather leave future numbered shortcuts for top-level components for now.

Comment (bruncun) [reply app/src/main-process/menu/build-default-menu.ts]: @shiftkey `CmdOrCtrl+G` works for me - I've updated the hotkey accordingly.

**Comment by iAmWillShepherd** [comment]
@bruncun, sorry for the delay in getting a review on this. Turns out I forgot to submit the review, so when I came to check on the status of this PR, I saw my review still in history 🤦‍♂️

**Comment by bruncun** [comment]
@iAmWillShepherd No sweat! I made the changes you requested. @shiftkey I also made the changes you requested. Thanks to you both for the thorough review.

@shiftkey I also noticed the same issue when I implemented this feature - its what motivated me to chain the event dispatch on to `showChanges`. I could have sworn that did the trick at the time, but my memory is fuzzy and it clearly doesn't work now. I share your suspicions - if you repro the issue by rapidly firing the respective keyboard shortcuts, more often than not the input gains focus.

I tried modifying `showChanges` so that it returned a Promise.all containing both promises, `closeCurrentFoldout` and `changeRepositorySection`, but didn't resolve the issue. I'll continue to give it thought as well and try to come up with a solution.

**Comment by tierninho** [comment]
The UI was tested for this change, and overall it functions well. 

- [ ] `Go to Summary` is a selectable option in the `View` menu
- [ ] `⌘G` takes user to Summary field in Changes; focus is active
- [ ] `⌘G` selected twice in a row from menu still focuses on Summary field
- [ ] `⌘G` is disabled if administrative modal present
- [ ] `⌘G` puts cursor focus after any previously entered text

Build/OS: 1.4.4-beta0, mac, 260d985713cb2a3869b42748f624b1915d88a0c3

**Comment by bruncun** [comment]
@shiftkey Totally understandable - React's controlled input components feel excessive, but to my knowledge there's no other way to manage their state. 😓

I updated the API to be a setter as requested.

File: app/src/lib/stores/app-store.ts [hunk 3]
```diff
@@ -2903,6 +2905,14 @@ export class AppStore extends TypedBaseStore<IAppState> {
     return Promise.resolve()
   }
 
+  public _setCommitMessageFocus(focus: boolean) {
+    const previousValue = this.focusCommitMessage
+    this.focusCommitMessage = focus
+    if (this.focusCommitMessage !== previousValue) {
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/app-store.ts]: This could be cleaned up a bit to make it clearer that this property should be set only if it changes.

```ts
    if (this.focusCommitMessage !== focus) {
      this.focusCommitMessage = focus
      this.emitUpdate()
    }
```

Comment (bruncun) [reply app/src/lib/stores/app-store.ts]: Updated.

**Comment by shiftkey** [comment]
I've assigned this to the `1.5.1` milestone because we've got a fair bit of changes already on the way with `1.5.0` release, and I'd like to ensure that goes as smoothly as possible. Thanks @bruncun for the contribution!

**Comment by bruncun** [comment]
Thank you @shiftkey and @iAmWillShepherd for the opportunities and kind guidance! Your project and team are a joy to hack with and learn from.

**Comment by shiftkey** [comment]
@bruncun just a heads up, it looks like there are some conflicts introduced (I think it was #6037) that affect your work. If you're not able to resolve it I'll co-ordinate with one of the maintainers to get it reviewed.

**Comment by outofambit** [comment]
i'm happy to help!

**Comment by bruncun** [comment]
@shiftkey @outofambit Thanks for the heads up - I can get to it tonight and reach out if I need any help.

**Comment by bruncun** [comment]
@outofambit @shiftkey So it might almost be there, but I ran into an issue. I resolved the merge conflicts (worth verifying) and updated the focus feature's conditional check inside `componentDidUpdate` of `commitMessage` to no longer reference `nextProps`. I thought that was it, but building dev crashed with the error:

```
[WEBPACK] Errors building ask-pass.js
[at-loader] ./app/src/lib/git/core.ts:258:22
    TS2339: Property 'NoMergeToAbort' does not exist on type 'typeof GitError'.
```

Not sure what's going on there.

**Comment by shiftkey** [comment]
@bruncun ensure you run `yarn` to get any updates to packages locally - that's a new message we added in an update to  `dugite` in [`v1.75.0`](https://github.com/desktop/dugite/releases/tag/v1.75.0).

**Comment by bruncun** [comment]
@shiftkey Ty, that fixed it! I successfully started the project locally and manually verified that the commit message focus action still works. 🎉
