### PR TITLE
Fixes #2964 'Delete Branch' warns that branch already exists on remote after it's deleted

### LINKED ISSUE #2964: 'Delete Branch' warns that branch already exists on remote after it's deleted
### Description

When I click on **Branch > Delete...**, I get a popup dialogue saying *"The branch also exists on the remote, do you wish to delete it there as well?"*. This is a useful message, but it always seems to say that, even after I have deleted the branch in GitHub after I merge. I have also tried switching to master and Fetching Origin first and trying again, but I am still getting the same message.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** 10.12.6

### Steps to Reproduce

1. Create branch in GitHub Desktop
1. Publish branch to GitHub
1. Delete branch in GitHub
1. Click to delete branch in Github Desktop

image

**Expected behavior:** I expected the branch to be deleted on the remote and thus not be notified otherwise.

**Actual behavior:** I was informed that the branch still exists on the remote, even after having deleted the branch.

**Reproduces how often:** 100%

### Logs

[2017-10-04.desktop.production.log](https://github.com/desktop/desktop/files/1357381/2017-10-04.desktop.production.log)

### LINKED ISSUE #3468: Deleting local branch still shows delete on remote option after upstream has been deleted from remote
### Description

Currently if you have a copy of a branch locally and on the remote when you attempt to delete from the desktop client you have the option to delete the remote as well. (`The branch also exists on the remote, do you wish to delete it there as well?`)

If the branch is deleted on the remote (e.g. on GitHub.com), the local client still gives the same option even though there is no longer a branch on the remote.

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Microsoft Windows [Version 10.0.16299.64]

### Steps to Reproduce

1. Create branch a new branch from master
	- Push/pull button shows publish branch
2. Branch -> Delete -> Cancel
	- Popup doesn't show remote branch option (correct - there is no remote branch)
3. Publish branch
	- Push/pull button shows fetch origin
4. Branch -> Delete
	- Gives remote branch option (correct - there is a remote branch)
5. Delete the branch on GitHub.com
6. Fetch origin
	- Push/pull button shows publish branch
7. Branch -> Delete
	- Gives remote branch option (incorrect - no remote branch exists)

**Expected behavior:** In step 7 the remote branch notice should not be shown

**Actual behavior:** In step 7 the remote branch notice is shown despite there not being a remote branch

**Reproduces how often:** Whenever the local branch had an upstream which has since been deleted on the remote

### PR DESCRIPTION
**Pull request by JordanMussi**
Fixes #2964

### CODE REVIEW

**Comment by tooomm** [comment]
Does this also fix https://github.com/desktop/desktop/issues/2964?

**Comment by JordanMussi** [comment]
Yes #3468 duplicates that issue, my bad.

File: app/src/lib/app-state.ts [hunk 1]
```diff
@@ -210,7 +210,12 @@ export enum PopupType {
 
 export type Popup =
   | { type: PopupType.RenameBranch; repository: Repository; branch: Branch }
-  | { type: PopupType.DeleteBranch; repository: Repository; branch: Branch }
+  | {
+      type: PopupType.DeleteBranch
+      repository: Repository
+      branch: Branch
+      aheadBehind: IAheadBehind | null
```
Comment (iAmWillShepherd) [inline app/src/lib/app-state.ts]: Instead of passing `IAheadBehind` let's pass a Boolean value, `existsOnRemote` that determines whether or not we show the delete on remote dialog.

**Comment by iAmWillShepherd** [comment]
Thanks for your contribution @JordanMussi! This is pretty much ✨  just one minor change.

File: app/src/lib/app-state.ts (hunk 1 above)
Comment (JordanMussi) [reply app/src/lib/app-state.ts]: Fixed in 60f791b8705928d35ba0bb8400edc0e404bcbc5a. 😺

File: app/src/ui/app.tsx [hunk 2]
```diff
@@ -417,12 +417,14 @@ export class App extends React.Component<IAppProps, IAppState> {
...
 
     const tip = state.state.branchesState.tip
+    const aheadBehind = state.state.aheadBehind
 
     if (tip.kind === TipState.Valid) {
       this.props.dispatcher.showPopup({
         type: PopupType.DeleteBranch,
         repository: state.repository,
         branch: tip.branch,
+        existsOnRemote: aheadBehind != null,
```
Comment (iAmWillShepherd) [inline app/src/ui/app.tsx]: Nit: `aheadBehind != null` -> `aheadBehind !== null`

You could also do the check where you declare `aheadBehind`

`const existsOnRemote = state.state.ahead !== null`

Comment (j-f1) [reply app/src/ui/app.tsx]: How about just `!!aheadBehind`?

Comment (iAmWillShepherd) [reply app/src/ui/app.tsx]: Definitely shorter, but that `!!` though!

**Comment by shiftkey** [comment]
Does this actually cover all the possible scenarios about a remote branch existing? I mentioned in https://github.com/desktop/desktop/issues/2964#issuecomment-335067138 that a `git ls-remote` call would be the most accurate way to confirm this, but if the `aheadBehind` state is cleared after a `git fetch` when the remote branch is removed then maybe this is fine as an interim solution?

**Comment by iAmWillShepherd** [comment]
@shiftkey 

I am with you that we should solve this using `git ls-remote`, but I think this is still a step in the right direction. 

@JordanMussi would you be willing to make the necessary changes to not rely on `aheadBehind` or to make sure to reset `aheadBehind` after each fetch?

**Comment by JordanMussi** [comment]
As far as I can tell `aheadBehind` is already updated for each fetch/pull/push. For example when performing a manual fetch with the push pull button this is the call trace:
- `ui/toobar/push-pull-button.tsx@performAction`
- `lib/dispatcher.ts@fetch`
- `lib/stores/app-store.ts@_fetch`
- `@performFetch`
- `@fastForwardBranches`
- `lib/git/rev-list.ts@getBranchAheadBehind`
- `@getAheadBehind`

With this code resetting `aheadBehind` to null when the branch doesn't exist on the remote:
https://github.com/desktop/desktop/blob/dd54f83a269d6353b5b48ae90d923e6130845ad1/app/src/lib/git/rev-list.ts#L25-L29

File: app/src/ui/app.tsx (hunk 2 above)
Comment (JordanMussi) [reply app/src/ui/app.tsx]: Fixed in 46d78157e1c7747983f820470079ae0e43e8016e. 🔍

**Comment by iAmWillShepherd** [comment]
@JordanMussi just need to resolve conflicts and we're 🏅

**Comment by JordanMussi** [comment]
Conflicts resolved in f9c94337ba79a143171b2a40fd709286e6f77389. 🛠

**Comment by iAmWillShepherd** [comment]
Gonna leave this open for a bit to allow @shiftkey the chance to review.
