### PR TITLE
Resize without observing

### LINKED ISSUE #20760: `[Unknown]` crash when opening notifications
### The problem

When opening a notification, sometimes the app would crash with this error

Image

Another way of reproducing this on dev builds is just hovering over PRs on the PR list (which on dev builds have a "preview popup").

### Release version

3.5.1 (arm64)

### Operating system

macOS 15.5

### Steps to reproduce the behavior

1. Open a PR comment notification

### Log files

_No response_

### Screenshots

_No response_

### Additional context

After digging into this, I found the problem is we're getting a `null` error in our [`onUncaughtException` handler](https://github.com/desktop/desktop/blob/f25fd2b252d5489fc2ee869bd3ab2c63065d3ac3/app/src/ui/index.tsx#L191). I set a breakpoint there and noticed the error is `ResizeObserver loop completed with undelivered notifications` but no error object is passed, which causes these `[Unknown]`.

Sentry error: https://github.sentry.io/issues/6271684196/?project=1824813&query=is%3Aunresolved%20release%3A3.5.1&referrer=issue-stream&stream_index=0

### LINKED ISSUE #21311: GH crashes, after clicking on notification
### The problem

When GH shows notification on MacOS, clicking on it causes error to be thrown. (I think it's caused by emoji characters in notification message)

```
[Unknown]: [Unknown]

Version: 3.5.4
OS: Mac OS 26.1.0
```

### Release version

3.5.4

### Operating system

Mac OS 26.1.0

### Steps to reproduce the behavior

1. Log into Enterprise acc
2. create PR
3. pipeline finishes, gh action shows "✅ No Critical or High CodeQL Findings Detected ✅"
4. GH app shows notification with this message
5. clicking on notification gives focus to GH app and the app instantly crash

### Log files

```
2025-11-24T12:53:35.004Z - info: [ui] [AppStore] loading 21 repositories from store
2025-11-24T12:53:35.007Z - info: [ui] [AppStore] found account: <user> (<user_name>)
2025-11-24T12:53:35.502Z - info: [ui] Subscribed '<user>' to Alive channel
2025-11-24T12:53:36.121Z - info: [ui] launching: 3.5.4 (Mac OS 26.1.0)
2025-11-24T12:53:36.122Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2025-11-24T12:53:36.530Z - info: [ui] Stats reported.
2025-11-24T12:53:38.050Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T12:53:38.980Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.976s)
2025-11-24T12:53:39.279Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T13:28:57.085Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T13:28:57.709Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.036s)
2025-11-24T13:28:57.987Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T13:59:17.381Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T13:59:18.051Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.181s)
2025-11-24T13:59:18.348Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T14:50:35.140Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T14:50:36.060Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.318s)
2025-11-24T14:50:36.306Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T15:05:20.872Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T15:05:23.532Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 3.368s)
2025-11-24T15:05:23.967Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T15:05:24.580Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.047s)
2025-11-24T16:01:13.080Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T16:01:13.712Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.024s)
2025-11-24T16:01:13.986Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T16:03:07.220Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:07.906Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.576s)
2025-11-24T16:03:08.363Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:08.476Z - info: [ui] [Timing] Action 'checkout branch from list' for '<company_repo>' took 0.250s
2025-11-24T16:03:09.442Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:10.082Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.231s)
2025-11-24T16:03:10.462Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:15.535Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:16.052Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.402s)
2025-11-24T16:03:16.901Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:17.309Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.256s)
2025-11-24T16:03:17.747Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:19.123Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:19.550Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.279s)
2025-11-24T16:03:21.100Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:21.522Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.902s)
2025-11-24T16:03:22.372Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:22.832Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.309s)
2025-11-24T16:03:23.260Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:23.476Z - info: [ui] [Timing] Action 'create branch' for '<company_repo>' took 0.313s
2025-11-24T16:03:24.028Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:25.428Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:25.921Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.359s)
2025-11-24T16:03:26.535Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:26.959Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.037s)
2025-11-24T16:03:27.836Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:28.322Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.298s)
2025-11-24T16:03:28.926Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T16:03:29.351Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.028s)
2025-11-24T17:25:50.182Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:25:51.306Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.810s)
2025-11-24T17:25:51.887Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:25:52.314Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.007s)
2025-11-24T17:25:53.326Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:25:53.778Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.405s)
2025-11-24T17:25:54.630Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:25:55.011Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.232s)
2025-11-24T17:25:55.955Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:25:56.435Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.357s)
2025-11-24T17:25:57.309Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:25:57.734Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.297s)
2025-11-24T17:25:58.668Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:25:59.525Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.698s)
2025-11-24T17:26:00.125Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:26:01.127Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.601s)
2025-11-24T17:26:01.809Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:26:02.247Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.037s)
2025-11-24T17:26:02.848Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:26:03.551Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.304s)
2025-11-24T17:26:04.536Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:26:05.310Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.674s)
2025-11-24T17:26:05.806Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:26:06.747Z - info: [ui] No submodules found. Skipping "git submodule status"
2025-11-24T17:26:07.183Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:26:07.576Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.263s)
2025-11-24T17:26:08.169Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T17:26:08.658Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.081s)
2025-11-24T17:26:11.014Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.012s)
2025-11-24T17:26:11.633Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 20 repositories took 47.0s of which 8405.4s paused, total 8452.4s
2025-11-24T17:29:40.362Z - info: [ui] [BranchPruner] Last prune took place 5 hours ago - skipping
2025-11-24T18:27:15.913Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:17.617Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 2.342s)
2025-11-24T18:27:18.470Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:19.022Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.404s)
2025-11-24T18:27:19.647Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:20.112Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.044s)
2025-11-24T18:27:20.689Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:22.017Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:22.469Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.313s)
2025-11-24T18:27:23.333Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:23.713Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.244s)
2025-11-24T18:27:24.999Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:25.450Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.707s)
2025-11-24T18:27:26.372Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:26.930Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.479s)
2025-11-24T18:27:27.588Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:28.002Z - info: [ui] No submodules found. Skipping "git submodule status"
2025-11-24T18:27:28.310Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.336s)
2025-11-24T18:27:28.907Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:29.764Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:30.778Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:31.229Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.027s)
2025-11-24T18:27:32.166Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:32.616Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.345s)
2025-11-24T18:27:33.119Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:33.921Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.304s)
2025-11-24T18:27:34.551Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:35.061Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.102s)
2025-11-24T18:27:35.639Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:36.939Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:37.542Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.485s)
2025-11-24T18:27:38.154Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:38.571Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.029s)
2025-11-24T18:27:39.487Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:39.947Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.339s)
2025-11-24T18:27:40.407Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:46.990Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:47.408Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.024s)
2025-11-24T18:27:48.288Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:48.700Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.292s)
2025-11-24T18:27:49.315Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:49.755Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.026s)
2025-11-24T18:27:50.668Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:51.304Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.548s)
2025-11-24T18:27:51.736Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:53.067Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:53.491Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.296s)
2025-11-24T18:27:53.929Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:54.980Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:56.278Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:56.780Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.342s)
2025-11-24T18:27:57.845Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:58.559Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.779s)
2025-11-24T18:27:59.557Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:27:59.952Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.351s)
2025-11-24T18:28:00.324Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T18:28:03.009Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.082s)
2025-11-24T18:28:03.428Z - info: [ui] [Timing] Action 'create commit' for '<company_repo>' took 0.383s
2025-11-24T18:28:03.437Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 20 repositories took 43.5s of which 1146.6s paused, total 1190.2s
2025-11-24T18:28:06.249Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T18:28:07.458Z - info: [ui] Executing push: git push origin <branch_name> --set-upstream --progress (took 1.539s)
2025-11-24T18:28:07.750Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T18:28:08.728Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T18:28:12.313Z - info: [main] opening in browser: https://github.com/<company_repo>/pull/new/feature%2F1808022
2025-11-24T18:32:31.248Z - info: [ui] [Timing] Action 'create commit' for '<company_repo>' took 0.412s
2025-11-24T18:32:32.014Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.009s)
2025-11-24T18:32:32.404Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 20 repositories took 3.9s of which 0.0s paused, total 3.9s
2025-11-24T18:32:36.668Z - info: [ui] [Timing] Action 'create commit' for '<company_repo>' took 0.001s
2025-11-24T18:32:37.311Z - warn: [ui] Attempted to add a popup of already existing type - MultiCommitOperation.
2025-11-24T18:32:37.869Z - info: [ui] [squash] starting rebase for <branch_name> at <hash>
2025-11-24T18:32:37.869Z - info: [ui] [squash] to restore the previous state if this completed rebase is unsatisfactory:
2025-11-24T18:32:37.869Z - info: [ui] [squash] - git checkout <branch_name>
2025-11-24T18:32:37.869Z - info: [ui] [squash] - git reset <hash> --hard
2025-11-24T18:32:39.457Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T18:32:40.450Z - info: [ui] Executing push: git push origin <branch_name>:<branch_name> --force-with-lease --progress (took 1.299s)
2025-11-24T18:32:40.777Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T18:32:41.615Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T19:01:25.042Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:01:25.671Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.578s)
2025-11-24T19:01:26.510Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:01:26.895Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.224s)
2025-11-24T19:18:28.037Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:28.520Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.416s)
2025-11-24T19:18:29.391Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:29.875Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.355s)
2025-11-24T19:18:30.962Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:31.637Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.677s)
2025-11-24T19:18:32.565Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:32.967Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.329s)
2025-11-24T19:18:33.589Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:34.191Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.179s)
2025-11-24T19:18:35.082Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:35.492Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.301s)
2025-11-24T19:18:36.423Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:36.841Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.288s)
2025-11-24T19:18:37.392Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:38.683Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:39.121Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.275s)
2025-11-24T19:18:39.963Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:40.474Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.352s)
2025-11-24T19:18:40.893Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:42.171Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:42.549Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.225s)
2025-11-24T19:18:43.452Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:43.879Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.287s)
2025-11-24T19:18:44.442Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:45.089Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.209s)
2025-11-24T19:18:45.518Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:46.520Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:47.937Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:48.345Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.260s)
2025-11-24T19:18:49.209Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:49.606Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.260s)
2025-11-24T19:18:50.248Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:51.051Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.398s)
2025-11-24T19:18:51.912Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:52.310Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.259s)
2025-11-24T19:18:53.227Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:53.755Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.409s)
2025-11-24T19:18:54.379Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:18:55.034Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.278s)
2025-11-24T19:26:28.573Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:26:29.919Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:26:30.332Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.293s)
2025-11-24T19:26:30.961Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:26:32.037Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.662s)
2025-11-24T19:26:32.948Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:26:33.285Z - info: [ui] [Timing] Action 'create commit' for '<company_repo>' took 0.459s
2025-11-24T19:26:33.338Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.300s)
2025-11-24T19:26:34.193Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T19:26:34.223Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:26:34.905Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.540s)
2025-11-24T19:26:35.268Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:26:35.499Z - info: [ui] Executing push: git push origin <branch_name>:<branch_name> --progress (took 1.713s)
2025-11-24T19:26:35.802Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T19:26:36.797Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2025-11-24T19:29:41.693Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:29:42.199Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.078s)
2025-11-24T19:29:43.141Z - info: [ui] credential-helper: found generic credential for https://<company_domain>.visualstudio.com/
2025-11-24T19:29:43.693Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.493s)
2025-11-24T19:35:55.900Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 20 repositories took 44.2s of which 2028.3s paused, total 2072.6s
2025-11-24T19:36:40.116Z - error: [main] [Unknown]: [Unknown]
2025-11-24T19:36:40.575Z - info: [main] Error report submitted
2025-11-24T19:36:48.672Z - info: [main] opening in browser: https://github.com/desktop/desktop/issues
2025-11-24T19:44:16.651Z - info: [ui] [AppStore] loading 21 repositories from store
2025-11-24T19:44:16.652Z - info: [ui] [AppStore] found account: <user> (<user_name>)
2025-11-24T19:44:16.665Z - info: [ui] [BranchPruner] Last prune took place 7 hours ago - skipping
2025-11-24T19:44:17.523Z - info: [ui] launching: 3.5.4 (Mac OS 26.1.0)
2025-11-24T19:44:17.529Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2025-11-24T19:44:17.534Z - info: [ui] Subscribed '<user>' to Alive channel
```

### Screenshots

Image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niik**
Closes #21311
Closes #20760

## Description

We're seeing a ton of crashes with no info attached due to the exception reaching us being `null`.

Image

I tracked it down to our use of `ResizeObserver` to observe elements inside of an `iframe` in our SandboxedMarkdown component. It's reproducible in development by hovering over PRs which pops up our PR preview pane. Our prior workarounds for this have failed so I went down the route of trying to avoid using `ResizeObserver` entirely and instead subscribe to the DOM events that could cause a resize inside of our markdown component.

As part of this work and to avoid flickering I reworked our filter pipeline to operate on the iframe Document itself instead of stringifying, parsing, mutating, stringifying etc etc. This lead to much snappier response times and dramatically reduced rerenders.

## Release notes

Notes:

### CODE REVIEW

File: app/src/lib/markdown-filters/is-element.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+export function isElement<T extends keyof HTMLElementTagNameMap>(
```
Comment (tidy-dev) [inline app/src/lib/markdown-filters/is-element.ts:1]: Nice readability improvement. :)

**Review by tidy-dev — APPROVED** [review]
💖  Makes sense. I kicked it around via the pull request previewer and some notifications and appears to work great.

File: app/src/lib/markdown-filters/is-element.ts (hunk 1 above)
Comment (niik) [reply app/src/lib/markdown-filters/is-element.ts:1]: Yeah I think it turned out pretty nice but this change is primarily needed because you can no longer do `element instanceof HTMLAnchorElement` because the HTMLAnchorElement type available in the renderer is different from the HTMLAnchorElement in the iframe due to sandboxing. This wasn't an issue in the previous logic because we were instantiating elements in the renderer, then stringifying them and having them be recreated in the iframe.
