### PR TITLE
tidy up some truthy checks

### LINKED ISSUE #3583: Opening a PR no longer asks the user if they want to push first
This is a regression brought to my attention by @Haacked.

The previous behavior for opening a PR in Desktop was to:
1. Check if the PR has been published, if not, ask user if they want to publish
2. Check if the PR is ahead of the branch on remote if so, ask if the user wants to push first
3. Just create the PR already

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes #3583

### CODE REVIEW

**Comment by iAmWillShepherd** [comment]
Did some truthiness cleanup here as well.

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -2918,11 +2918,10 @@ export class AppStore {
     const branch = tip.branch
     const aheadBehind = state.aheadBehind
 
-    if (!aheadBehind) {
+    if (aheadBehind == null) {
       this._showPopup({
-        type: PopupType.PushBranchCommits,
+        type: PopupType.PublishRepository,
```
Comment (shiftkey) [inline app/src/lib/stores/app-store.ts]: I'm still a bit unclear on how this fixes the issue. The `aheadBehind` value is associated with the current branch, but we should show the `PublishRepository` popup if there are no remotes associated with the repository. Maybe this fixes the issue because the app will push the current branch after the publish completes?

My gut feeling is that there needs to be two checks here:

 - first, confirm that there's no remote defined -> publish repository flow
 - second, handle situation where branch has no tracking branch -> push the branch to the remote?

Thoughts?

Comment (shiftkey) [reply app/src/lib/stores/app-store.ts]: > Is it possible to not have a tracking branch at this point?

Good question. I'll see if I can reproduce the issue using the original details and report back.

Comment (shiftkey) [reply app/src/lib/stores/app-store.ts]: > Is it possible to not have a tracking branch at this point?

An unpublished branch will not have any tracking information. But that should be handled by the old first code path.

Comment (shiftkey) [reply app/src/lib/stores/app-store.ts]: Shall we move this back to #3583 and get to the bottom of reproducing the issue?

Comment (shiftkey) [inline app/src/lib/stores/app-store.ts]: The other reason I don't think this is the right fix is that the "Create Pull Request" button should only be enabled for a GitHub or Enterprise repository - which assumes that it has a remote setup. Publishing a repository should only be necessary if that remote doesn't exist...

**Comment by iAmWillShepherd** [comment]
@shiftkey I reverted [3c14f7a](https://github.com/desktop/desktop/pull/3584/commits/3c14f7a5eda434bf647d70b99fc811c24c64d139)

💯
