### PR TITLE
Issue 4574: Allow pull on empty repo

### LINKED ISSUE #4574: Cannot pull after cloning a truly empty repository
## Description

If you clone a truly empty repository (no files, no commits yet) from an SSH source github desktop will not let you pull or fetch.  The normal pull/fetch/push tab shows the message "cannot publish unborn head" and does nothing.  The push and pull menu items in the _Repository_ menu are disabled.

If someone else adds files and commits to the remote repository you cannot subsequently do a pull or fetch to pull them in via github desktop.  Obviously you can drop into command line git to do so but this does not seem like an advanced use-case that would require git to solve.

## Version

* GitHub Desktop: 1.1.1
* Operating system: Windows 7, 64 bit

## Steps to Reproduce
Clone an empty repository (no commits) from an SSH source

### Expected Behavior
You would still be able to pull/fetch from the remote.

### Actual Behavior
Pull/fetch is disabled (apparently) through all controls.

### Logs
Nothing relevant in the logs.

### PR DESCRIPTION
**Pull request by jackfreem**
Closes #4574
Closes #4575

## Description

- Allows origin fetch for fully empty repo 

### Screenshots

Before:
Screenshot 2026-01-27 at 7 47 27 PM

After:
Screenshot 2026-01-27 at 7 47 35 PM

## Release notes

Notes: Bug fix: Allow origin fetch on empty repo

### CODE REVIEW

File: app/src/ui/toolbar/push-pull-button.tsx [hunk 1]
```diff
@@ -455,6 +455,11 @@ export class PushPullButton extends React.Component<
     }
 
     if (tipState === TipState.Unborn) {
+      // If we have a remote, allow fetching to check for new commits
+      // that may have been pushed by others
+      if (remoteName !== null) {
```
Comment (niik) [inline app/src/ui/toolbar/push-pull-button.tsx]: The check on line 453 here ensures that remoteName is never null meaning that this will always be true which means that `unbornRepositoryButton` will never get called and can be deleted.

**Review by niik — CHANGES_REQUESTED** [review]
Hey @jackfreem, thanks for wanting to contribute. I think these changes are sound but there's one interesting logical consequence of your changes that I'd like you to take a look at

File: app/src/ui/toolbar/push-pull-button.tsx (hunk 1 above)
Comment (jackfreem) [reply app/src/ui/toolbar/push-pull-button.tsx]: Good call! I've cleaned this up and removed the dead code.

**Review by niik — APPROVED** [review]
Thanks @jackfreem!
