### PR TITLE
Repo rule branch meta data false postive fix

### LINKED ISSUE #17392: Ruleset rejects branches that should pass the rule
### The problem

Assuming I have a repository with the rule for branch naming: `^(minor|feature|bugfix)\/.*(ABC|DEF|GHI)-[0-9]+.*`
when I try creating branch with name feature/ABC-12345-test using Github Desktop there is a validation error saying "Branch name feature/ABC-12345-test" is restricted by repo rules. At the same time it lets me create same branch using Web version.

### Release version

Version 3.3.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Setup metadata restriction:
Applies to: Branch name
Requirement: must match a given regex pattern
Matching pattern: `^(minor|feature|bugfix)\/.*(ABC|DEF|GHI)-[0-9]+.*`
2. Try creating branch with name feature/ABC-12345-some-branch-name 
3. Validation error occurs

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Fixes https://github.com/desktop/desktop/issues/17392

## Description
The above ticket highlighted that when a repo rule users the `Metadata restrictions` to limit a branch to a specific pattern that the create dialog check was not verifying against the regex, it was just failing when the regex existed. 

This PR adds the same check that is in the `commit-message.tsx` to check against the provided regex.

I tested the following logic flows:
- Add both Restrict Creation and Branch Name Pattern Rules - Verified failure
- Added one at a time - verified failure
- Added bypass - verified bypass still worked.
- Verified that regex failure and success cases.

Notes: Restrict Creation and Branch Name Pattern all only rules that can apply here.

### Screenshots

With ruleset:
- Target Branches:  All branches
- metadata restriction:
    - Applies to: Branch name
    - Requirement: must match a given regex pattern
    - Matching pattern: ^(minor|feature|bugfix)\/.*(ABC|DEF|GHI)-[0-9]+.*
image

No longer receive error:
image

Does show error for one that does not match the regex:
image

## Release notes
Notes: [Fixed] Branch name pattern regex no longer causes an automatic failure in the "Create a Branch" dialog.

### CODE REVIEW

File: app/src/ui/create-branch/create-branch-dialog.tsx [hunk 1]
```diff
@@ -150,6 +150,10 @@ export class CreateBranch extends React.Component<
         ),
       })
     }
+
+    if (nextProps.initialName.length > 0) {
+      this.checkBranchRules(nextProps.initialName)
+    }
```
Comment (tidy-dev) [inline app/src/ui/create-branch/create-branch-dialog.tsx:156]: I found that if I use the "New Branch" button in the branch dropdown with an invalid name, the repo rules were not being run on that initial branch name and I could create the branch as long as I didn't modify the name again. :P (An unintentional bypass to repo rules)

File: app/src/ui/create-branch/create-branch-dialog.tsx [hunk 2]
```diff
@@ -392,13 +401,27 @@ export class CreateBranch extends React.Component<
     )
 
     // there are no relevant rules for this branch name, so return
-    if (toCheckForBypass.size === 0) {
+    if (toCheck.size === 0) {
+      return
+    }
+
+    // check for actual failures
+    const { branchNamePatterns, creationRestricted } = await parseRepoRules(
```
Comment (tidy-dev) [inline app/src/ui/create-branch/create-branch-dialog.tsx:409]: This is conducted one other place in `app-store` for cacheing to reduce number of times it is called for the `commit-messages` section - I believe this is mostly an general efficiency measure as it doesn't cause more heavy resource things like api calls. I am safe guarding against unnecessary running of this by the above check that says to only run this if there are rules that apply to branch names.

https://github.com/desktop/desktop/blob/b794fa55beffffb5b4c242ff830f8283a7ee92c9/app/src/lib/stores/app-store.ts#L1193-L1206

The below `getFailedRules` is called on every `commit-messages.tsx` render so I am not as concerned about it getting called more frequently, and should be the call of one regex anyways.

https://github.com/desktop/desktop/blob/b794fa55beffffb5b4c242ff830f8283a7ee92c9/app/src/ui/changes/commit-message.tsx#L445-L467

**Review by haldun — COMMENTED** [review]
I have manually tested this PR and I can no longer reproduce the originally reported issue.

**Comment by steveward** [comment]
Tested this out as well and confirmed the fix works. 👍🏻

File: app/src/ui/create-branch/create-branch-dialog.tsx [hunk 3]
```diff
@@ -392,13 +401,27 @@ export class CreateBranch extends React.Component<
...
+      branchRules,
+      this.props.cachedRepoRulesets,
```
Comment (tidy-dev) [inline app/src/ui/create-branch/create-branch-dialog.tsx:411]: So, I ran into an issue with using this `cachedRepoRulesets`. When I released to beta and tested on Windows, I opened `desktop/desktop` in GitHub Desktop. Then, opened `desktop/desktop` in dotcom and added a branch name pattern rule. Then, I returned to GitHub Desktop and attempted to create a branch that violated that rule. It did not catch even tho the branch rule was being pulled down here because these cached rules were empty. I had to switch repositories to get the `app-store.ts` to rule to populate this cache.

Two thoughts: 
1. We could use whatever we pull down and not pass in the cache here.
2. We could do something along the lines that Markus had pointed out in one of the other repo rule fix PRs and make the `app-store.ts` logic run on window focus.

Comment (tidy-dev) [reply app/src/ui/create-branch/create-branch-dialog.tsx:411]: (Note this is an edge case/only when fiddling with the repo rules on dotcom while desktop is open)

Comment (vaindil) [reply app/src/ui/create-branch/create-branch-dialog.tsx:411]: The endpoint queried by this component is ["Get rules for a branch"](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#get-rules-for-a-branch), which only returns a very slim list of rules. The user's bypass status comes from the full ruleset object, which is why these cached rulesets are passed in at all. Option 1 therefore wouldn't really work here.

Option 2 would work, but users could potentially end up with a lot of queries. The ["Get all repository rulesets" endpoint](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#get-all-repository-rulesets) doesn't return this bypass status either, so each individual ruleset has to be queried, and a given repo could have any number of rulesets. That's why I opted for heavier caching like this: These rulesets are probably rarely changing in the first place outside of testing, and swapping it to something like the window focus event would likely trigger a _lot_ more API calls than are necessary.

File: app/src/ui/create-branch/create-branch-dialog.tsx (hunk 2 above)
Comment (vaindil) [reply app/src/ui/create-branch/create-branch-dialog.tsx:409]: This is perfectly fine to call more often like you said, I just cached it because it doesn't _need_ to run more often in most cases. The only thing that can change it is the underlying rulesets changing, and that can only happen when they're queried in `app-store.ts` in the first place (or a special case like this component).

**Review by vaindil — COMMENTED** [review]
This looks great, thank you for fixing while I was out today!

File: app/src/ui/create-branch/create-branch-dialog.tsx (hunk 3 above)
Comment (tidy-dev) [reply app/src/ui/create-branch/create-branch-dialog.tsx:411]: > so each individual ruleset has to be queried, and a given repo could have any number of ruleset

Wonder if it would be possible for client app consumption to add an api call that simply returns the last updated date of any rules? That we do that one more frequently and only go get all the rules if there has been an update.

File: app/src/ui/create-branch/create-branch-dialog.tsx [hunk 4]
```diff
@@ -408,10 +431,6 @@ export class CreateBranch extends React.Component<
       }
     }
 
-    if (this.state.branchName !== branchName) {
```
Comment (sergiou87) [inline app/src/ui/create-branch/create-branch-dialog.tsx:411]: Shouldn't we keep this check after `await checkRepoRules`?

The chance for something bad to happen is slow, but I tend to be paranoid around async stuff 😂

**Review by sergiou87 — COMMENTED** [review]
It looks good and makes sense. It also worked great. I only have a question around one of the checks after an async call.

File: app/src/ui/create-branch/create-branch-dialog.tsx (hunk 4 above)
Comment (tidy-dev) [reply app/src/ui/create-branch/create-branch-dialog.tsx:411]: That check is here to be after the network call of `await api.fetchRepoRulesForBranch` of which it is directly after to short circuit anymore work if it has changed in the time it took to retrieve the repo rules. 

I will go ahead and put another check in since I did introduce another async method. Tho,  `await parseRepoRules`  is only async due to the `getBooleanConfigValue` so it is not a network call, thus, I believe the risk is much smaller but, technically still there is a chance for a blip for users with commit signing repo rules.

**Review by sergiou87 — APPROVED** [review]
Thanks for that change!! 💖 :shipit:
