### PR TITLE
Fix sign in hanging

### LINKED ISSUE #2769: Client Hangs on Sign In
### Description
Sign in fails on fresh install. The program appears to freeze after an attempted sign in. Signing in works on the older client.
[Description of the issue]

### Version

**GitHub Desktop version:** 0.9.1

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Download and Install Client
2. Attempt to sign in with correct credentials

capture

**Expected behavior:** Expected to be taken to main screen and allowed to select a repo

**Actual behavior:** Hung on the screen shown in the attached image

**Reproduces how often:** 100%

### Logs

2017-09-18T22:15:11.515Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #2769

I haven't been able to reproduce the bug, but I think I understand what's happening.

We would only advance to the next step of the Welcome flow when the `Welcome` component was rendered twice with the same sign in step. That was a logic error introduced in https://github.com/desktop/desktop/commit/ed2a5b917977c159249832c1af5d31bbdb272ddd.

This bug didn't manifest most of the time because most of the time we'd get lucky. Our account store's state update and login store's state update would happen across two separate animation frames. The `Welcome` component would be rendered twice with the same sign in step, and life would go on. But on slower or busier computers, those two state updates could be coalesced into the same animation frame. The `Welcome` component would only get rendered once and so it'd get stuck.

### CODE REVIEW

File: app/src/ui/welcome/welcome.tsx [hunk 1]
```diff
@@ -91,10 +91,10 @@ export class Welcome extends React.Component<IWelcomeProps, IWelcomeState> {
     }
 
     // Only advance when the state first changes...
-    if (this.props.signInState.kind !== nextProps.signInState.kind) {
+    if (this.props.signInState.kind === nextProps.signInState.kind) {
```
Comment (niik) [inline app/src/ui/welcome/welcome.tsx]: Some day I'll learn how to computer

Comment (joshaber) [reply app/src/ui/welcome/welcome.tsx]: giphy-3
