### PR TITLE
fix: handle empty rowcount array in section-list

### LINKED ISSUE #19793: GitHubDesktop-dev crashes with unrecoverable error
### The problem

When building the current development branch using yarn, GitHub Desktop crashes with the following error:

    TypeError: Reduce of empty array with no initial value
        at Array.reduce (<anonymous>)
        at get totalHeight (http://localhost:3000/build/renderer.js:143657:36)
        at SectionList.renderFakeScroll (http://localhost:3000/build/renderer.js:143706:93)
        at SectionList.renderContents (http://localhost:3000/build/renderer.js:143590:22)
        at SectionList.render (http://localhost:3000/build/renderer.js:143569:28)
        at finishClassComponent (http://localhost:3000/build/renderer.js:32822:31)
        at updateClassComponent (http://localhost:3000/build/renderer.js:32777:24)
        at beginWork (http://localhost:3000/build/renderer.js:33725:16)
        at performUnitOfWork (http://localhost:3000/build/renderer.js:37393:12)
        at workLoop (http://localhost:3000/build/renderer.js:37433:24)

    Version: 3.4.13-beta1
    OS: Windows 10.0.26100

No errors or warnings occur during build. During "yarn start" the following warnings are displayed:

    [desktop-notifications] [error] Failed to initialize with RO_INIT_MULTITHREADED: -2147417850

    info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}

    (node:19252) UnhandledPromiseRejectionWarning: Error: Invalid header: Does not start with Cr24
        at crxToZip (D:\Repositories\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\main.js:42290:15)
        at D:\Repositories\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\main.js:42327:32
        at callHanler (D:\Repositories\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\main.js:46933:16)
        at tryCatcher (D:\Repositories\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\main.js:46650:32)
        at D:\Repositories\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\main.js:46789:38
        at flush (D:\Repositories\desktop\dist\GitHubDesktop-dev-win32-x64\resources\app\main.js:46692:17)
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

### Release version

3.4.13-beta1

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Clone the repository on Windows 11.
2. Build app with `yarn build:dev`.
3. Run app with `yarn start`.

v20.17.0

>yarn -v
1.22.22

>python --version
Python 3.9.13

### PR DESCRIPTION
**Pull request by sfadschm**
Closes #19793

This adds a conditional early exit to the `section-list` `totalheight` method to catch empty arrays being passed to the `array.reduce` method. This is necessary, as the `rowcount` prop is generated by `array.map´ which returns an empty array if it is fed an empty array.

It further adds a fallback value of `0` (which is the neutral fallback value for addition) to the `array.reduce` method to catch potential further errors.

The second change might be subject to discussion.

### CODE REVIEW

File: app/src/ui/lib/list/section-list.tsx [hunk 1]
```diff
@@ -1383,9 +1383,14 @@ export class SectionList extends React.Component<
   }
 
   private get totalHeight() {
+    // Exit early if no rows present
+    if (this.props.rowCount.length === 0) {
+      return 0
+    }
+
```
Comment (sergiou87) [inline app/src/ui/lib/list/section-list.tsx]:
```suggestion
```

I think I would remove these lines and leave only the default value in `reduce`: it's its purpose and keeps the code simpler 😄

**Review by sergiou87 — CHANGES_REQUESTED** [review]
Great catch!!!

File: app/src/ui/lib/list/section-list.tsx (hunk 1 above)
Comment (sfadschm) [reply app/src/ui/lib/list/section-list.tsx]: Did not think about it that way, but sure :-D

I guess I wanted to have some documentation of the purpose, but that's fine.

**Comment by sfadschm** [comment]
Implemented suggestion via force-push, as this should not be more than 1 commit.

File: app/src/ui/lib/list/section-list.tsx (hunk 1 above)
Comment (sergiou87) [reply app/src/ui/lib/list/section-list.tsx]: And that makes total sense! But being `reduce` a well-known API, I think having `0` as default/initial value should be enough.

**Review by sergiou87 — APPROVED** [review]
💖 :shipit: 🚀
