### PR TITLE
Make the version text copiable

### LINKED ISSUE #1935: make the version text under About selectable
### Description

To save accidentally mis-typing the version number, the text in the **About GitHub Desktop** should be selectable so you can copy and paste it elsewhere.

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** macOS (also relevant to Windows)

### Steps to Reproduce

1. Launch the application
1. Select **GitHub Desktop** | **About GitHub Desktop**
1. Try and select the version number

**Expected behaviour:** can highlight text

**Actual behaviour:** nothing

**Reproduces how often:** 100%

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #1935.

### CODE REVIEW

File: app/src/ui/about/about.tsx [hunk 1]
```diff
@@ -232,7 +237,7 @@ export class About extends React.Component<IAboutProps, IAboutState> {
           </Row>
           <h2>{name}</h2>
           <p className='no-padding'>
-            Version {version} ({releaseNotesLink})
+            Version <span title='Click to copy' className='version-text' onClick={this.onClickVersion}>{version} <Octicon symbol={OcticonSymbol.clippy} /></span> ({releaseNotesLink})
```
Comment (shiftkey) [inline app/src/ui/about/about.tsx]: I think we should be consistent with how we set things on the clipboard throughout the app. I _think_ the work in #1778 is something we should also do here (use a link that copies to the clipboard) rather than an icon.

Comment (j-f1) [inline app/src/ui/about/about.tsx]: @shiftkey So something like this?

> Version [0.6.0] ([release notes](https://desktop.github.com/release-notes/))

[0.6.0]: #discussion_r121018222 "Click to copy"

Comment (shiftkey) [inline app/src/ui/about/about.tsx]: Possibly, but I've not kept up with the latest design thread so I'll defer to @niik or @donokuda  here.

Comment (joshaber) [inline app/src/ui/about/about.tsx]: In the mean time, I think simply making the text selectable would be an A+ improvement.

Comment (j-f1) [inline app/src/ui/about/about.tsx]: @joshaber The downside of that is that you can’t easily *un*select it afterwards.

Comment (j-f1) [inline app/src/ui/about/about.tsx]: If I should to use `<LinkButton>`s, I’ll need #1962 merged.

Comment (j-f1) [inline app/src/ui/about/about.tsx]: Fixed.

**Comment by j-f1** [comment]
@shiftkey this is ready for review.

File: app/src/ui/about/about.tsx [hunk 2]
```diff
@@ -232,7 +237,7 @@ export class About extends React.Component<IAboutProps, IAboutState> {
           </Row>
           <h2>{name}</h2>
           <p className='no-padding'>
-            Version {version} ({releaseNotesLink})
+            <LinkButton title='Click to copy' className='version-text' onClick={this.onClickVersion}>Version {version}</LinkButton> ({releaseNotesLink})
```
Comment (shiftkey) [inline app/src/ui/about/about.tsx]: I'm not around for the next few weeks but I'll leave my thoughts here because I think this needs some design input.

The fact that this text is now clickable isn't really helpful. Here's what I now see:



And unlike all the other links here, there's no feedback when you do click that it's done anything. You need to hover for a couple of seconds to see the `Click to copy` message.

I think we can do better than this, and I like where the discussion in #1778 ended up.

Comment (j-f1) [inline app/src/ui/about/about.tsx]: I read through #1778, and it’s not clear what you’d like me to that's from that. Should I have a separate “click to copy” link?

Comment (iAmWillShepherd) [inline app/src/ui/about/about.tsx]: Ideally, the text should just be selectable. I am not a fan of having links that don't behave like links and having actions that don't provide the user with much feedback.

**Comment by iAmWillShepherd** [comment]
Picking up while @shiftkey is out. I'll review once all checks pass.

**Comment by j-f1** [comment]
@iAmWillShepherd can you restart the build?

> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by j-f1** [comment]
🗜

**Comment by joshaber** [comment]
@iAmWillShepherd Could you give this a look? 👀
