### PR TITLE
Fix merge branch dialog preview message check for slow merge check

### LINKED ISSUE #17929: Merge request dialog: Error merge information
### The problem

企业微信截图_da3af112-e252-4e14-9c38-93e3e29f43e3

After opening the Merge dialog, Immediately select the branches to merge, but Merge prompts to merge the **root node**。
Whether this problem can be solved

### Release version

Version 3.3.6 (arm64)

### Operating system

Macos14.0

### Steps to reproduce the behavior

_No response_

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes #17929 

## Description
This PR updates the merge branch dialog to only update the preview if the branch a merge check was completed on matches the branch currently in state (last selected by the user.) This prevents the scenario that if a merge check starts and a user clicks another branch and that branches merge check is faster than the previous, the previous selected branch merge check data will not overwrite the current selected data.

(For verification) In order to reliably reproduce the issue, I added this code to the mergeabilty check so the initial merge check always took significant time.
Shows adding a sleep timer to the development branch merge check

## Release notes
Notes: [Fixed] Merge branch dialog's merge preview no longer shows stale merge check data.

### CODE REVIEW

File: app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx [hunk 1]
```diff
@@ -104,6 +104,12 @@ export class MergeChooseBranchDialog extends BaseChooseBranchDialog {
         return { kind: ComputedAction.Clean }
       })
 
+      if (this.state.selectedBranch !== branch) {
```
Comment (sergiou87) [inline app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx]: Should we do this in the `catch` part above too?

Or even more comprehensively… store the result of `await promiseWithMinimumTimeout` in a variable, then do this `selectedBranch != branch` check, and then store it in `this.mergeStatus` to prevent other issues.

Does that make sense? 🤔

**Review by sergiou87 — COMMENTED** [review]
The fix makes total sense, but I wonder if there could be other edge cases that could still cause issues.

File: app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx (hunk 1 above)
Comment (tidy-dev) [reply app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx]: Because it all sets the `mergeStatus`, I don't think there is needed difference for the `catch`. But.. I do think, you are right and it doesn't make sense to set `this.mergeStatus` until until after the `this.state.selectedBranch` check. I will take another look at it.

File: app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx [hunk 2]
```diff
@@ -127,12 +125,17 @@ export class MergeChooseBranchDialog extends BaseChooseBranchDialog {
 
     if (this.state.selectedBranch !== branch) {
       this.commitCount = 0
+      return
```
Comment (tidy-dev) [inline app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx:128]: Same reason as above -> if this has changed, no need to continue to update the preview.

File: app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx [hunk 3]
```diff
@@ -127,12 +125,17 @@ export class MergeChooseBranchDialog extends BaseChooseBranchDialog {
...
-    this.updateMergeStatusPreview(branch)
+    this.updateMergeStatusPreview(branch, mergeStatus)
   }
 
-  private updateMergeStatusPreview(branch: Branch) {
+  private updateMergeStatusPreview(
+    branch: Branch,
+    mergeStatus: MergeTreeResult
+  ) {
+    this.mergeStatus = mergeStatus
```
Comment (tidy-dev) [inline app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx:138]: Don't need to update the class variable unless updating the state... probably should refactor to store these in the state and just update the preview on state update... but that PR may be pretty hefty.. so just focusing on issue at hand with this pr.

**Comment by tidy-dev** [comment]
@sergiou87 I did take some time yesterday.. admittedly maybe more than this warranted and went down the rabbit hole of refactoring this to better [use state and follow the React convention of not using class extensions](https://github.com/desktop/desktop/compare/use-state-not-class-variables?expand=1).  Since I have it working, we could override this PR for that one.. but it is many more changes so needs more thorough review/testing.

**Review by sergiou87 — APPROVED** [review]
Thank you for those changes ❤️  I think we can merge this and then consider that refactor separately if you want. I agree that using state is better, but it's also true that the current implementation does work…

If you feel confident and comfortable with that refactor, I say we take a look at it. Otherwise I think it's ok to keep the current implementation even if it's not perfect.

**Comment by Influ1877** [comment]
J

File: app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx (hunk 1 above)
Comment (rizwan123912) [reply app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx]: > Because it all sets the mergeStatus, I don't think there is needed difference for the catch. But.. I do think, you are right and it doesn't make sense to set this.mergeStatus until until after the this.state.selectedBranch check. I will take another look at it.

happy birthday to you
