### PR TITLE
Comma is a valid character in tags

### LINKED ISSUE #17952: Tag show wrong name in desktop
### The problem

the name of tag in Desktop looks like:
image
but it's really name is:
image
I can't see the right name

### Release version

3.3.6

### Operating system

Windows 11

### Steps to reproduce the behavior

_No response_

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes #17952

## Description
This replaces the regex with splitting the commit ref line on ", " and then looking through those for tags, because the regex was causing a tag such as `test,test,test` to be retrieved as `test`. 

Other thoughts... maybe this could still use regex.. and my regex skills just are not up to it. It would have to be something like `/tag: ([^\s]+)(,\s)?`.. but this still pulls back commas that separate the list.

## Release notes
Notes: [Fixed] Tags with commas are no longer truncated to the first comma.

### CODE REVIEW

**Review by vertUq-zinqa5-xyhnib — COMMENTED** [review]
read-tags-with-commas

File: app/src/lib/git/log.ts [hunk 1]
```diff
@@ -155,9 +154,21 @@ export async function getCommits(
...
-    const tags = getCaptures(commit.refs, /tag: ([^\s,]+)/g)
-      .filter(i => i[0] !== undefined)
-      .map(i => i[0])
+    // Ref is of the format: (HEAD -> master, tag: some-tag-name, tag: some-other-tag,with-a-comma, origin/master, origin/HEAD)
+    // Refs are comma separated, but some like tags can also contain commas in the name, so we split on the pattern ", " and then
+    // check each ref for the tag prefix. We used to use the regex /tag: ([^\s,]+)/g)`, but will clip a tag with a comma short.
+    const refs = commit.refs.split(', ')
+    const tags = []
+    for (let i = 0; i < refs.length; i++) {
+      const ref = refs[i]
```
Comment (sergiou87) [inline app/src/lib/git/log.ts]: Nit:
```suggestion
    for (const ref of refs) {
```

The whole `for` could also be replaced with a `refs.flatMap(…)` returning `[]` for refs that don't start with `tag: `, but maybe it's not as straightforward as this? 🤔

**Review by sergiou87 — DISMISSED** [review]
LGTM just a small suggestion but feel free to ignore it and merge this right away if you want

File: app/src/lib/git/log.ts (hunk 1 above)
Comment (tidy-dev) [reply app/src/lib/git/log.ts]: :D I do like the straight forward reading of the `for` loop, but I do really like the cleanliness of the one-liner. :P I think with the comment explaining what a ref can look like the `flatMap` is discernible enough. Thank you for the suggestion.

**Review by sergiou87 — APPROVED** [review]
