### PR TITLE
Better diff expand button focus management

### LINKED ISSUE #17776: Scroll on Commit Diff keeps jumping around
### The problem

The scroll bar and content on the diff view of a file in the commit selected from the history tab is glitching.

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10 x64

### Steps to reproduce the behavior

I use a unified view and I don't have my "hide whitespaces" checked.
I'm checking out my history, I select a commit, I select a file and I am watching the diff.
As I scroll down, I expand some of the hidden lines by clicking the arrows on the left margin on the diff code.
when I try to scroll down fast, the scrollbar and the diff scroll position glitches and flickers across a different position.

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes: https://github.com/desktop/desktop/issues/17776
xref: https://github.com/github/accessibility-audits/issues/4989

## Description
This PR keeps a map (similar to List rowRef solution) of diff expansion button refs so that on diff expansion we can focus the next expansion handle of that type. If that doesn't exist, we move to the next expansion handle in logical tab order, if not that, then the closed expansion handle. Otherwise, we focus the diff container (meaning no available expansion handles to focus).

The main issue this solve is that if you are keyboard user and you click an expansion handle that gets removed from the DOM (any of them but the expand up), the focus moves to the app body. Inaccessible/annoying for keyboard users who must now tab through the app to get back to interacting with the diff.  Secondarily, if a user expands down to see more and another expansion down button is visible, this focuses that expand down button so a user can more easily keep expanding as needed. 

This PR also removes my previous attempt of using the buttons `autoFocus` property that did not quite get the job done because if there were no buttons of the same type, the focus would again move to the app body. Additionally, I found while testing again that it sometimes causes jumpy behavior if scrolling with the arrow keys. 

Other thoughts:
- ~I was following accessibility advice of moving focus to the next handle of the same type.. generally this works great. But.. in the scenario of expand down and now the next expander is out of scroll or there is no more expand down, but there is an expand up. The focus moves to the diff which is nice in the sense that now a user can scroll to see what the expanded.. but I also thought maybe the next logical focus point should be the available next expander button? I think it could make sense either way tho... and also thought.. well maybe more focus management work will happen when the diff gets audited.. so maybe best to not introduce too many new behaviors before we know the full scope of work around diff accessibility. (There are already other issues.. like if you have focus on the up expander and use the keyboard to scroll.. scrolling just stops when the up expander moves out of focus. :/)~ Outdated -> Updated the logic to focus the closet button to the last expanded hunk.
- I had thought to use DOM traversal to just grab all the expansion handles.. but I needed some meta data (hunk index/expansion handle type) which I could have done through data attributes.. But this PR feels more inline with how React works.
- The diff does not have a focus indicator... maybe it should... 

## Release notes

Notes: [Improved] Better focus management after diff expansion buttons triggered.

### CODE REVIEW

**Comment by tidy-dev** [comment]
> The diff does not have a focus indicator... maybe it should...

Just briefly looked at this and it doesn't look pretty to "just simply enable the focus indicator".. :P 
Showing partially hidden focus indicator

If I can get it to look decent, I would want to do it in another iteration.. as it looks like it will take some css fiddling time.

File: app/src/ui/diff/side-by-side-diff-row.tsx [hunk 1]
```diff
@@ -451,15 +432,21 @@ export class SideBySideDiffRow extends React.Component<
...
           ariaLabel={elementInfo.title}
+          onButtonRef={this.onHunkExpansionRef(hunkIndex, expansionType)}
         >
           <Octicon symbol={elementInfo.icon} />
         </Button>
       </div>
     )
   }
 
+  private onHunkExpansionRef =
```
Comment (sergiou87) [inline app/src/ui/diff/side-by-side-diff-row.tsx]: Nit: given this function actually returns an `on…Ref` function but is not one of them, I prefer to name them with the `get` prefix: `getOnHunkExpansionRef`

**Review by sergiou87 — COMMENTED** [review]
Not sure what's the expected behavior, but the behavior of the current beta feels more correct to me 😕 

https://github.com/desktop/desktop/assets/1083228/d94580e9-f5f3-4632-ae80-23bc4fd2e3c0

**Comment by tidy-dev** [comment]
> Not sure what's the expected behavior, but the behavior of the current beta feels more correct to me 

I think in the video you are referring to the behavior of it moving to the next button of the same type even if it is not in the same location. I have updated this PR's logic to first try for the same location and type if that exists if not, go to the next button in tab order, if not go to the next closest button. That is not exactly the same... but I think it is a little better because in your video it skips a button in logical tab order which I think would be bad for screen reader users.

https://github.com/desktop/desktop/assets/75402236/9d518079-197e-430a-b545-1866a4a7922d

File: app/src/ui/diff/side-by-side-diff.tsx [hunk 2]
```diff
@@ -408,6 +411,89 @@ export class SideBySideDiff extends React.Component<
...
+
+    if (closestInTabOrder) {
+      const closetHunkButton = this.hunkExpansionRefs.get(closestInTabOrder)
+      closetHunkButton?.focus()
+      return
+    }
+
+    // No? Then try to focus the next closest hunk in reverse tab order
+    const closestInReverseTabOrder = expansionHunkKeys
+      .reverse()
```
Comment (niik) [inline app/src/ui/diff/side-by-side-diff.tsx:487]: This seems to imply that `expansionHunkKeys` is already sorted by tab order but AFAICT it's sorted on insertion order (i.e. when the elements were added to the DOM) meaning it'll be sorted in tab order when scrolling downward but in the reverse order when scrolling upwards (since the list is virtualized). So we should probably sort `expansionHunkKeys` up front to ensure consistency regardless of scroll direction.

I'd also prefer if we, instead of reversing in-place here, used the [`findLast` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLast) though that will require us adding `ES2023.Array` and I believe we'll have to land the TS5 upgrade first so depending on the order of things happening here we can keep .reverse or switch to .findLast

File: app/src/ui/diff/side-by-side-diff.tsx [hunk 3]
```diff
@@ -408,6 +411,89 @@ export class SideBySideDiff extends React.Component<
...
+   * - A hunk index may have multiple expansion buttons (up and down) so it does
+   *   not uniquely identify a button.
+   */
+  private focusAfterLastExpandedHunkChange() {
+    if (this.state.lastExpandedHunk === null) {
+      return
+    }
+
+    const diffNode = findDOMNode(this.virtualListRef.current)
+    const diff = diffNode instanceof HTMLElement ? diffNode : null
```
Comment (niik) [inline app/src/ui/diff/side-by-side-diff.tsx]: I'd love it if we could defer this lookup to when it's actually needed. Could we extract this into a `focusListElement` method and call that in the conditional below and at the end of the method?

**Review by niik — CHANGES_REQUESTED** [review]

File: app/src/ui/diff/side-by-side-diff.tsx (hunk 3 above)
Comment (tidy-dev) [reply app/src/ui/diff/side-by-side-diff.tsx]: Nice - makes sense.

File: app/src/ui/diff/side-by-side-diff.tsx (hunk 2 above)
Comment (tidy-dev) [reply app/src/ui/diff/side-by-side-diff.tsx:487]: Add the sort, `findLast` sound quite nice.

**Review by niik — APPROVED** [review]
