### PR TITLE
Initial support for repository rules

### LINKED ISSUE #16707: Add support for repository rules
[Repository rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) ([announced here](https://github.blog/changelog/2023-04-17-introducing-repository-rules-public-beta/)) are the next version of branch protection rules, they use different endpoints to manage and have some different logic. I'm currently working on implementing support for them, this issue will track that work.

### Limitations
- The initial implementation will not check whether the current user can bypass the rules.
- Only repository-level rules are currently supported due to a pending internal bug fix.

#### Restrict creations
- [x] Display a warning in the "create a branch" popup when the user types a branch name that's disallowed by a ruleset
- [x] Display a warning in the commit area if an unpublished branch will fail to publish because its name is disallowed

#### Metadata restrictions
- [x] Display warning in "create a branch" popup if branch name metadata rule doesn't match
- [x] Display warning in commit area if any rules don't match configured metadata restrictions for:
  - [x] Commit message
  - [x] Commit author email address

#### Other rules
- [x] Many of the rules won't be handled in a special way beyond a generic warning in the commit area. I'm open to hearing if we could support these though, as I'm not the most familiar with this program! These include:
- restrict updates
- require linear history
- require signed commits
- require deployments to succeed before merging
- require status checks to succeed before merging

#### Still investigating
- [ ] The "require a pull request" rule will probably display a warning in the commit area that prompts the user to open a PR instead
- [ ] "Block force pushes" could theoretically display a warning, but I don't know that there's a good place to display it
- [ ] "Restrict deletions" (of branches) could also theoretically display a warning, but I don't see much benefit here because they'll get the error by clicking the button--I don't really see a value add here.
- [ ] I have a warning implemented for commit author email addresses not matching the pattern (by tweaking the existing [commit message avatar component](https://github.com/desktop/desktop/blob/291d632825a349856bc1f49b77104705e745473d/app/src/ui/changes/commit-message-avatar.tsx)). Is there a similar spot a warning could be shown for the committer email?

### PR DESCRIPTION
**Pull request by vaindil**
Closes #16707

## Description
- This adds initial support for [repository rules](https://github.blog/changelog/2023-04-17-introducing-repository-rules-public-beta/), a new GitHub feature that's currently in beta. There are [quite a few available rules](https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets), this grabs the ones I think make the most sense to support.
- Rules are queried when changing branches or when typing into the "create a branch" field (debounced).
- The goal is to proactively warn users that an action they're taking might fail; as far as I can tell there's no need for special handling if a push does fail.
- Certain users are able to bypass rules, this is configured per-ruleset. The process for parsing out whether the current user has bypass permission is rather convoluted, so I opted not to support it for now. The API may be updated fairly soon to make this easier, but for now the wording of warnings is that "your push **may** fail".
- [The API endpoint](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#get-rules-for-a-branch) does not currently show the source of a rule, so I cannot link directly to a specific rule that's failing. Additionally, rules may be configured in multiple places and therefore apply multiple times in different ways. This is why I opted to link to the page that lists all rulesets for a branch ([example here](https://github.com/desktop/desktop/rules?ref=refs%2Fheads%2Fdevelopment)). This page is viewable by anyone with read access to the repo.
  - An API update may be coming soon that adds the source to that endpoint, which would make it easy to link to the exact rule rather than to the general rulesets page. I could add that in when it's ready and just link to the first failing rule if there are multiple that overlap.
  - There are two types of rules, the high-level ones like "restrict creation" and "require linear history", and metadata restrictions. Metadata restrictions can have an exact error generated (similar to `must begin with "foo"`) and this PR does generate those to list exactly what's failing.
- The PR does not have tests yet, as I'm new to the desktop app and I imagine tweaks will be needed.

My remaining questions (some carried over from #16707):

- [ ] The "catch-all" commit warning above the commit button handles these rules. Can any of these be handled in a better way? restrict updates (no pushing at all), require linear history (no merge commits, i.e. must squash or rebase into this branch), require signed commits, require deployments to succeed before merging, require status checks to succeed before merging
- [ ] A rule is available to require a pull request to merge. Can this be handled in the app? I couldn't figure out a way to create a PR programmatically. It might make sense to lump into the catch-all.
- [ ] The commit message email warning currently handles the commit author only, not the committer. I'm not familiar with the intricacies of Git or how the app works, should it handle both?
- [ ] The "invalid commit message" warning uses the existing commit message warning component, but displays it above the boxes to prevent the fields jumping around as the user types. This can lead to having a warning displayed both above and below the fields (see screenshots), which isn't great. Is there a better UI pattern I could use?
- [ ] If a branch exists locally and not on the server and fails a branch name rule, then the server may prevent it from being published. I'm currently displaying this warning in the commit message area. Would it make more sense in the header by the actual "Publish branch" button?
- [ ] Are there any places the "block force pushes" rule could be warned about?

### Screenshots

<details>

<summary>Screenshots are collapsed because there are a bunch</summary>

"Restrict creation" and branch name metadata rules:

Warning in the create a branch dialog

Commit message metadata rule, and catch-all warning for several other types of failures:

Warning in the commit message area

Commit author email address metadata rule:

Warning popup for an invalid commit author email address

Unpublished branch conflicts with a branch name or "restrict creations" rule:

Warning in the commit message area for an unpublished branch

</details>

## Release notes

Notes:

### CODE REVIEW

File: app/src/ui/multi-commit-operation/cherry-pick.tsx [hunk 1]
```diff
@@ -130,6 +130,7 @@ export abstract class CherryPick extends BaseMultiCommitOperation {
         defaultBranch={defaultBranch}
         upstreamDefaultBranch={upstreamDefaultBranch}
         upstreamGitHubRepository={upstreamGhRepo}
+        gitHubAccount={null}
```
Comment (vaindil) [inline app/src/ui/multi-commit-operation/cherry-pick.tsx]: How can I get the user's GitHub account info in this file? It's necessary for querying the API in the create branch component. I wasn't able to figure out how this file is even called.

File: app/src/lib/helpers/repo-rules.ts [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+function toMatcher(rule: IAPIRepoRuleMetadataParameters | undefined): RepoRulesMetadataMatcher {
+  if (!rule) {
+    return () => false
+  }
+
+  let regex: RegExp
+
+  switch (rule.operator) {
+    case APIRepoRuleMetadataOperator.StartsWith:
+      regex = new RegExp(`^${escapeRegExp(rule.pattern)}`)
```
Comment (niik) [inline app/src/lib/helpers/repo-rules.ts]: Looking at the [ruleset documentation](https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/managing-rulesets-for-a-repository#using-regular-expressions-for-commit-metadata) it appears they're using RE2-syntax for their expressions so I imagine we'll have to use some library to make us compatible?

i.e. `\Afoo` in RE2 would be `^foo` in JS

File: app/src/ui/create-branch/create-branch-dialog.tsx [hunk 3]
```diff
@@ -101,9 +106,53 @@ export class CreateBranch extends React.Component<
...
+      this.setState({ currentError: { error: new Error(errMsg), isBlocking: false }})
+    }
+  }, 500)
+
   public constructor(props: ICreateBranchProps) {
     super(props)
 
+    if (props.upstreamGitHubRepository !== null && props.gitHubAccount !== null) {
+      this.api = API.fromAccount(props.gitHubAccount)
+    }
```
Comment (niik) [inline app/src/ui/create-branch/create-branch-dialog.tsx]: API objects are not expensive to create, rather than setting it up in the constructor and thereby missing any prop updates for the account we should just instantiate it in the debounced method.

File: app/src/ui/create-branch/create-branch-dialog.tsx [hunk 4]
```diff
@@ -28,11 +28,16 @@ import { CommitOneLine } from '../../models/commit'
...
+import { debounce } from 'lodash'
+import { API } from '../../lib/api'
+import { Account } from '../../models/account'
+import { parseRepoRules } from '../../lib/helpers/repo-rules'
 
 interface ICreateBranchProps {
   readonly repository: Repository
   readonly targetCommit?: CommitOneLine
   readonly upstreamGitHubRepository: GitHubRepository | null
+  readonly gitHubAccount: Account | null
```
Comment (niik) [inline app/src/ui/create-branch/create-branch-dialog.tsx]: I imagine these branch rules will eventually make it to GHES as well right? So we should probably pass in all accounts here and use `getAccountForRepository` to resolve the proper account for the `upstreamGitHubRepository`. We should also add a method to `endpoint-capabilities.ts` that lets us query whether the endpoint supports repo rules at runtime

File: app/src/ui/create-branch/create-branch-dialog.tsx [hunk 5]
```diff
@@ -259,14 +308,18 @@ export class CreateBranch extends React.Component<
...
     const alreadyExists =
       this.props.allBranches.findIndex(b => b.name === branchName) > -1
 
     const currentError = alreadyExists
-      ? new Error(`A branch named ${branchName} already exists`)
+      ? { error: new Error(`A branch named ${branchName} already exists`), isBlocking: true }
       : null
 
+    if (!currentError) {
+      await this.checkBranchRules(branchName)
```
Comment (niik) [inline app/src/ui/create-branch/create-branch-dialog.tsx:402]: Now that we've introduced an async operation here we would typically begin by issuing a state update to reflect the branch name change and then after the async operation check to make sure it hasn't changed while we were out fetching data from the API so that we don't end up in a race condition where the slowest API response "wins"

Same applies within the checkBranchRules method

File: app/src/ui/multi-commit-operation/cherry-pick.tsx (hunk 1 above)
Comment (niik) [reply app/src/ui/multi-commit-operation/cherry-pick.tsx]: You'd start by passing it from the App state to the `MultiCommitOperation` component here:

https://github.com/desktop/desktop/blob/291d632825a349856bc1f49b77104705e745473d/app/src/ui/app.tsx#L2187

And then to the `CherryPick` component here

https://github.com/desktop/desktop/blob/291d632825a349856bc1f49b77104705e745473d/app/src/ui/multi-commit-operation/multi-commit-operation.tsx#L17

**Review by niik — DISMISSED** [review]
Took a quick look at this. Good job of staying close to the spirit of the code base. I'll take a deeper look at things as we get further along but leaving some notes.

File: app/src/lib/helpers/repo-rules.ts (hunk 2 above)
Comment (vaindil) [reply app/src/lib/helpers/repo-rules.ts]: Oh that's a really good catch, I completely missed that, thanks! The only library I see for this is [node-re2](https://github.com/uhop/node-re2), which I can pull in if that's okay, but I don't know what the policies are for adding new packages.

File: app/src/ui/create-branch/create-branch-dialog.tsx (hunk 5 above)
Comment (vaindil) [reply app/src/ui/create-branch/create-branch-dialog.tsx:402]: I think I get what you're saying to do, I added that in https://github.com/desktop/desktop/pull/16904/commits/edf4ba0a91234a66ca86deba69ff217e0a88b2c2. Is that all I need? I think this covers all of the async edge cases now.

File: app/src/ui/create-branch/create-branch-dialog.tsx (hunk 3 above)
Comment (vaindil) [reply app/src/ui/create-branch/create-branch-dialog.tsx]: Handling this now in https://github.com/desktop/desktop/pull/16904/commits/d9e3c23a2bcefc6d1abcc96cbc3420b80e5325b2, thanks! I looked at moving this and the accounts change into `componentWillReceiveUpdates` so it only has to be computed when they change, but I'm not a React expert and React's docs say not to use that method for new code, so I just left it here for now.

File: app/src/ui/create-branch/create-branch-dialog.tsx (hunk 4 above)
Comment (vaindil) [reply app/src/ui/create-branch/create-branch-dialog.tsx]: Added this in https://github.com/desktop/desktop/pull/16904/commits/d9e3c23a2bcefc6d1abcc96cbc3420b80e5325b2

File: app/src/ui/multi-commit-operation/cherry-pick.tsx (hunk 1 above)
Comment (vaindil) [reply app/src/ui/multi-commit-operation/cherry-pick.tsx]: Perfect, added in https://github.com/desktop/desktop/pull/16904/commits/d9e3c23a2bcefc6d1abcc96cbc3420b80e5325b2, thanks!

File: app/src/ui/create-branch/create-branch-dialog.tsx (hunk 5 above)
Comment (vaindil) [reply app/src/ui/create-branch/create-branch-dialog.tsx:402]: Actually, that commit just doesn't work, because `if (branchName === this.state.branchName)` is always false. I guess I'm not sure how you're saying to change it then. I could leave in the other change from https://github.com/desktop/desktop/commit/edf4ba0a91234a66ca86deba69ff217e0a88b2c2 but remove that specific check since it's always false?

Comment (vaindil) [reply app/src/ui/create-branch/create-branch-dialog.tsx:402]: After discussion with some of the team, I'm going to try pulling in a package to perform the fnmatch-style matching and update to do these checks client-side, which would make this no longer async. That will come in a future PR though. We'll merge this one in as-is, then my next PR will either render this point moot or fix the logic.

**Review by sergiou87 — APPROVED** [review]
It looks good, some of the changes we discussed in the call will be tackled in a separate PR, and I also tested it and worked as expected! Awesome work!!!! 🙇‍♂️ 💖
