### PR TITLE
Fix screenreader list position announcement regression

### LINKED ISSUE #19603: Bug Report: Missing Group Position Announcements in Commit List
### The problem

In the 3.4.9 update of *GitHub Desktop*, group position announcements (e.g., "1 of 10") are no longer provided when navigating the list of commits. This issue significantly affects accessibility for blind users relying on screen readers to understand their position in the list.  

## Steps to Reproduce  
1. Open *GitHub Desktop* version 3.4.9.  
2. Navigate to the list of commits using a screen reader.  
3. Listen for group position announcements (e.g., "1 of 10").  

### Expected Result  
The screen reader announces the group position for each commit, such as "1 of 10," "2 of 10," etc.  

### Actual Result  
The group position announcements are missing, leaving users unaware of their position in the list.  

## Impact  
This bug disrupts the workflow of blind programmers and users by removing essential navigation feedback, making it difficult to manage commits effectively.  

## Environment  
- **GitHub Desktop Version**: 3.4.9  
- **OS**: Windows 10
- **Screen Reader**: both JAWS and NVDA

## Additional Notes  
This issue did not exist in previous versions and seems to have been introduced in the 3.4.9 update.  

Please investigate and resolve this accessibility issue at the earliest, as it has a significant impact on blind users.  

Thank you for your attention to this matter.  

### Release version

3.4.9

### Operating system

Windows

### Steps to reproduce the behavior

1. Open *GitHub Desktop* version 3.4.9.  
2. Navigate to the list of commits using a screen reader.  
3. Listen for group position announcements (e.g., "1 of 10").  

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes #19603 

## Description
When working on https://github.com/desktop/desktop/pull/19341, to make it so non-selectable list items could be browsed, I unintentionally made it so that selectable list items would take the same behavior. My mistake was seeing that the role of the list was still correct after changes.. but the actual list items now had role of `listitem` as opposed to `option` for non-presentational lists.

### Screenshots
Commit list with correct role of `listbox` and items with role of `option`.
Commit list with correct role of `list-box` and items with role of `option

Commit unreachable list with correct role of `list` and items with role of `listitem`
Commit unreachable list with correct role of `list` and items with role of `listitem`

Showing item number on NVDA:
Shows a picture of desktop history commit list with the NVDA speechviewer open. The speech viewier shows that the list had been navigated and each item announced x of 100.

## Release notes
Notes: [Fixed] Screen readers announce the position of the list items in selectable lists such as the history commit list.

### CODE REVIEW

File: app/src/ui/history/commit-list.tsx [hunk 1]
```diff
@@ -499,7 +499,7 @@ export class CommitList extends React.Component<
         {this.renderReorderCommitsHint()}
         <List
           ariaLabel="Commits"
-          role={this.props.isInformationalView === true ? 'list' : 'list-box'}
```
Comment (tidy-dev) [inline app/src/ui/history/commit-list.tsx:502]: Yes.. Not only did I goof on checking for `undefined` against an item that couldn't be `undefined`... but also I yes switched `listbox` to `list-box` (my malapropism acting up..). But it most definitely is `listbox` https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role

File: app/src/ui/lib/list/list-row.tsx [hunk 2]
```diff
@@ -107,13 +107,13 @@ interface IListRowProps {
...
   /** Optional role setting.
    *
-   * By default our lists use the `list-box` role paired with list items of role
+   * By default our lists use the `listbox` role paired with list items of role
    * 'option' because that have selection capability. In that case, a
    * screenreader will only browse to the selected list option. If the list is
    * meant to be informational as opposed for selection, we should use `list`
    * with `listitem` as the role for the items so browse mode can navigate them.
    */
-  readonly role?: `option` | `listitem` | 'presentation'
```
Comment (tidy-dev) [inline app/src/ui/lib/list/list-row.tsx:116]: I also for some reason used backtick.. when it would more properly be a single quote... surprised the linter didn't hammer me on that.

File: app/src/ui/lib/list/list.tsx [hunk 3]
```diff
@@ -1188,7 +1188,7 @@ export class List extends React.Component<IListProps, IListState> {
         <ListRow
           key={params.key}
           id={id}
-          role={this.props.role === undefined ? undefined : 'listitem'}
```
Comment (tidy-dev) [inline app/src/ui/lib/list/list.tsx:1191]: In ListRow the logic is:

```
sectionHasHeader && rowIndex.row === 0
            ? 'presentation'
            : role ?? 'option'
```

List logic:
``` role={this.props.role ?? 'listbox'} ```

So our two use cases are:
1. CommitList which now does define a role as either `list` or `listbox`.  (History or unreachable commit list)
2. Every other list where role = undefined.

For every other, we want  to keep current behavior as `listbox` and `option`. This does uphold, if role is undefined, the main grid is "defined or listbox", this logic here says undefined !== list so the ListBox will receive undefined. which will then filter through the sectionHeader logic to the same "definedRole or option".

For the CommitList, it will send in a defined role of `list` or `listbox` so it will pass that and set it on the main List. and this condition will say if it `list` to define a role for the list item as `listitem` otherwise do undefined which will again follow the above and use the default of `option` assuming it isn't a sectionHeader row.

**Review by niik — APPROVED** [review]
