### PR TITLE
Don't attempt to check out the currently checked out branch

### LINKED ISSUE #11235: Switch to current branch
### Switch to current branch

When selecting the current branch from the branches dropdown, I get the prompt to stash my changes or bring them over. If I select "bring over" nothing happens but if I select "stash", my changes are stashed.

### Version & OS

Version 2.6.1
Windows 10

### Steps to reproduce the behavior

1. Go to 'Branches'
2. Click on the current branch

### Expected behavior

Nothing should happen or there should be a message that you are already on this branch

### Actual behavior

Acts as if it is switching branches

### Screenshots

image

### Additional Context

This issue occurs when there are changes present on the current branch and "Ask me where I want my current changes to go" is set.

### PR DESCRIPTION
**Pull request by niik**
Closes #11235 

## Description

Turns out that we allow checking out the currently checked out branch which makes very little sense and causes some very confusing behavior when you've also got local changes (see #11235). Let's not do that any more.

## Release notes

Notes: [Fixed] Don't offer to stash or move changes when clicking on the currently checked out branch in the branch list.

### CODE REVIEW

**Review by sergiou87 — APPROVED** [review]
LGTM! :shipit:

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -3059,6 +3059,11 @@ export class AppStore extends TypedBaseStore<IAppState> {
     const { tip } = branchesState
     const hasChanges = changesState.workingDirectory.files.length > 0
 
+    // No point in checking out the currently checked out branch.
+    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {
```
Comment (Stirfry70) [inline app/src/lib/stores/app-store.ts:3063]: @**
```suggestion
    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {
```suggestion
    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {![default.jpg](https://user-images.githubusercontent.com/46066539/102594304-dd947e80-40ca-11eb-9fe7-1f85389b0b6c.jpg)
```

```
**

Comment (Stirfry70) [inline app/src/lib/stores/app-store.ts:3063]:
```suggestion
    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {Pin copied text snippets to stop them expiring after 1 hour
```

Comment (Stirfry70) [inline app/src/lib/stores/app-store.ts:3063]: A

**Review by Stirfry70 — APPROVED** [review]

File: app/src/lib/stores/app-store.ts (hunk 1 above)
Comment (Stirfry70) [reply app/src/lib/stores/app-store.ts:3063]: The Green Post Office is open

Comment (Stirfry70) [inline app/src/lib/stores/app-store.ts:3063]: []()
```suggestion
    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {
```

Comment (Stirfry70) [inline app/src/lib/stores/app-store.ts:3063]:
```suggestion
    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {

```

Comment (Stirfry70) [inline app/src/lib/stores/app-store.ts:3063]:
```suggestion
    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {
```

Comment (Stirfry70) [inline app/src/lib/stores/app-store.ts:3063]:
```suggestion
    if (tip.kind === TipState.Valid && tip.branch.name === branch.name) {
```

**Review by Stirfry70 — CHANGES_REQUESTED** [review]
