### PR TITLE
Fix commit message generation while amending commits

### LINKED ISSUE #20664: Commit message generation disabled when amending commit
Hi

I accidentally hit commit before using the AI option. When I hit Amend Commit and hit the AI option nothing happens.

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #20664

## Description

This PR fixes two issues:
1. As pointed out in #20664, we should enable the Copilot button when the user is amending a commit **even if there aren't new changes in the working dir**.
2. When generating a commit message while amending a commit, we should create a diff not only with the changes in the working dir but also include the commit being amended.

### Screenshots

https://github.com/user-attachments/assets/991f1f93-e925-4b74-b06f-43bb79973aa7

## Release notes

Notes: [Fixed] Use all changes to generate a commit message when amending commits

### CODE REVIEW

File: app/src/lib/git/diff.ts [hunk 1]
```diff
@@ -424,6 +434,7 @@ export async function getFilesDiffText(
     '--patch-with-raw',
     '--no-color',
     '--staged',
+    ...(commitish ? [`${commitish}^`] : []),
```
Comment (niik) [inline app/src/lib/git/diff.ts]: Could we make this be committish only and have the caller's take care of adding the parent modifier?

I can't quite put my finger on it but it feels wrong for it to be codified in the method itself. If we didn't do that then omitting `comittish` would be the same as passing `HEAD`.

**Review by niik — CHANGES_REQUESTED** [review]
Looks great! One small request

**Review by niik — APPROVED** [review]
