### PR TITLE
2.1.0 release

### LINKED ISSUE #7495: branch pruner not enabled for production usage
## Description

Branches which were fully pushed, merged, and deleted on Github.com are not removed from GitHub Desktop. This super clutters up the list of branches.

## Version

* GitHub Desktop: 1.6.5

* Operating system: MacOS 10.14.4

## Steps to Reproduce

1. Create a branch
  - Either through cmd or through github desktop, unclear if relevant
2. Work on branch across two systems
  - Unclear if relevant
3. Push, squash-merge, delete the branch on GitHub.com
4. Wait 2 weeks #750 

### Expected Behavior

Branches are pruned after 2 weeks - (although I would prefer right away)

### Actual Behavior

Branches are never pruned.

SomeVeryOldBranches
[2019-05-09.desktop.production.log](https://github.com/desktop/desktop/files/3162498/2019-05-09.desktop.production.log)

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

Tracking the work related to shipping 2.1 on Tuesday

Also closes #7495 by enabling branch pruning for prod.

## Description

- [x] enable branch pruning for production
- [x] ???
- [x] bump version
- [x] draft release notes
- [x] get approval for release notes
- [x] :shipit: 
- [x] merge `development` into this branch

### CODE REVIEW

File: app/src/lib/feature-flag.ts [hunk 1]
```diff
@@ -48,7 +48,7 @@ export function enableReadmeOverwriteWarning(): boolean {
 
 /** Shoult the app automatically prune branches that are no longer actively being used */
```
Comment (billygriffin) [inline app/src/lib/feature-flag.ts]:
```suggestion
/** Should the app automatically prune branches that are no longer actively being used */
```
