### PR TITLE
Run hooks in user's shell environment and allow bypassing commit hooks

### LINKED ISSUE #9351: Improve context on pre-commit hook failures and provide escape hatch
### Describe the bug

I cannot commit to the `excalidraw/excalidraw` repo in GitHub Desktop. Using GitUp (another GUI) or the `git` CLI both work fine.L

### Version & OS

GitHub Desktop Version 2.4.0, macOS Version 10.15.3 (19D76)

### Steps to reproduce the behavior

1. Clone `https://github.com/excalidraw/excalidraw`
1. Run `npm install` to install the dependencies
1. Open the repo in your favorite editor and delete lines 8–18 of `src/index.tsx` so you have something to commit.
1. In GitHub Desktop, commit the change.

### Expected behavior

The commit occurs successfully.

### Actual behavior

An error dialog displaying this text:
<details>

```
Commit failed - exit code 1 received, with output: 'husky > pre-commit (node v13.11.0)
Preparing... [started]
Preparing... [failed]
→ error: unknown option 'ignore-skip-worktree-entries'
usage: git update-index [<options>] [--] [<file>...]

[removed: listing of all options]

Cannot save the current worktree state
Running tasks... [started]
Running tasks... [skipped]
→ Skipped because of previous git error.
Applying modifications... [started]
Applying modifications... [skipped]
→ Skipped because of previous git error.
Cleaning up... [started]
Cleaning up... [skipped]
→ Skipped because of previous git error.

  ✖ lint-staged failed due to a git error.
  Any lost modifications can be restored from a git stash:

    > git stash list
    stash@{0}: On master: automatic lint-staged backup
    > git stash pop stash@{0}

error: unknown option 'ignore-skip-worktree-entries'

[removed: listing of all options]

Cannot save the current worktree state
husky > pre-commit hook failed (add --no-verify to bypass)
```
</details>

### Additional context

I’m guessing this is because `--ignore-skip-worktree-entries` was recently added to Git and Husky is using Desktop’s bundled version for some reason?

### LINKED ISSUE #10060: Unable to commit when git hooks use bash syntax.
### Describe the feature or problem you’d like to solve

Our project have git hooks that were written for Mac and Linux but I am in windows. WSL is my dev env and can run these hooks but Github desktop will not run any git commands in WSL behind the scenes.

Github desktop is unusable by many devs using WSL.

When a git hook is run via GitHub desktop we see:
Commit failed - exit code 1 received, with output: ''.' is not recognized as an internal or external command,
operable program or batch file.'

Also tried using bash as my shell.
Also tried adding "bash -c" etc into the git hooks that run but then I get "bash is not a recognized command" even tho it IS recognized by all my shells.

### Proposed solution

Please add WSL integration || or actually use the shell to run already working git cli so that desktop is just an interface running git commands behind the scenes would be nice.

### Additional context

Some context.. the hooks are php files with 
#!/usr/bin/env php
<?php

They run additional commands also with shell executions/passthrough.
I tried editing those to add `bash -c` etc however and see "bash is not a recognized command"
Even who it IS a recognized command in windows and works for all my shells. 🤷‍♀️

I have seen people talking about editing the source to add custom shells but its easier to just not use Github.

I don't have the option of not using WSL or editing the git hooks to support windows at this stage.

### LINKED ISSUE #10828: Prominently notify me when a hook rejects a commit
### Describe the feature or problem you’d like to solve

I think it would be neat if GitHub Desktop prominently notified me if a hook rejects the commit I'm trying to make.

Certain hooks (like extensive lint, type check) can take a few seconds. On a couple of occasions, I've gone back to editing the code, assuming the checks will eventually pass. However, when a lint hook rejected the commit, I was not alerted. I did not notice that the commit had failed until after I made another batch of changes and came back to make another commit. I ended up with a single commit containing both changesets, which made it harder to review.

### Proposed solution

I would like GitHub Desktop to prominently notify me when a hook rejects the commit. This could come in the form of a notification or a dock icon bounce on macOS.

### LINKED ISSUE #11523: Include the git-subtree executable with the included git client
### Describe the feature or problem you’d like to solve

The GitHub Desktop client includes a git client but that git client doesn't contain the `git-subtree` executable.
This can cause some problems, for example if the git repository has git hooks that use the `git subtree` command, those git hooks will fail with the following message:
```
git: 'subtree' is not a git command. See 'git --help'.
```
See screenshot below.

### Proposed solution

**Include the `git-subtree` executable with the included git client.**

The `git-subtree` executable  was included before, at least in some very old GitHub Desktop versions (I've version since 2018 that included it).

I manually copied the `git-subtree` executable into `~/Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/` on my Mac and then the git hooks work as expected but I would need to add the executable after each update of the GitHub Desktop client.

### Additional context
Screenshot with the error dialog:
image

### LINKED ISSUE #11603: Pre-commit hook fails because it can't find lint-staged
### Describe the bug

image
Pre-commit hook fails when I try to commit using GitHub Desktop.

Following is an excerpt of my package.json file

```
 "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": "npm run lint"
  }

```

This works when trying to commit using the command line and when tried using VSCode's Git integration, but fails on GitHub Desktop. 
`lint-stage` is installed locally and I prefer to keep it that way.

### Version & OS

Version 2.6.3
Windows 10 Home

### LINKED ISSUE #11997: GitHub desktop freezes on commit when there is a pre-commit hook
### Describe the bug

I added a very simple git hook that would run before every commit:

```bash

#!/bin/bash

echo "Pulling ..."
git pull
```

This hook is located in the .git/hooks/ folder and named pre-commit as an executable. Though when I try to commit in GitHub desktop the program freezes and does not commit.

The GitHub desktop GUI is opened using my Windows environment and I added the folder location using the `\\wsl$\Ubuntu-20.04\home\...` path. I am also in my GitHub enterprise account.

### Version & OS

GitHub Desktop version: Version 2.7.2
Windows 10: 10.0.19042 Build 19042

The repository is located in a WSL2 environment in  Ubuntu 20.04.2 LTS.

### Steps to reproduce the behavior

1. In a WSL environment create a git repository.
2. Create a pre-commit file that run `git pull`
3. In your Windows environment open GitHub desktop 
4. Select `Add local repository`
5. Navigate to the WSL location of the folder (`\\wsl$\Ubuntu-20.04\home\...` )
6. Commit

### Expected behavior

GitHub desktop should, when I press commit just run the pre-commit script and then just commit like it normally does.

### Actual behavior

GitHub desktop just freezes and has the commit sign just keep on turning.

### Screenshots
image

image

### Logs

```
2021-04-14T02:00:28.725Z - info: [ui] [AppStore] loading 9 repositories from store
2021-04-14T02:00:28.727Z - info: [ui] [AppStore] found account: Marius-Juston (Marius Juston)
2021-04-14T02:00:28.727Z - info: [ui] [AppStore] found account: mjuston2 (Juston, Marius F)
2021-04-14T02:00:30.875Z - info: [ui] launching: 2.7.2 (Windows 10.0.19042)
2021-04-14T02:00:30.876Z - info: [ui] execPath: 'C:\Users\mariu\AppData\Local\GitHubDesktop\app-2.7.2\GitHubDesktop.exe'
2021-04-14T02:00:30.892Z - info: [ui] Executing getRemotes: git remote -v (took 2.144s)
2021-04-14T02:00:30.893Z - info: [ui] Executing getRemotes: git remote -v (took 1.554s)
2021-04-14T02:00:30.928Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.981s)
2021-04-14T02:00:31.047Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.517s)
2021-04-14T02:00:31.904Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.731s)
2021-04-14T02:00:32.080Z - info: [ui] Stats reported.
2021-04-14T02:00:32.476Z - info: [ui] Executing getCommits: git log 37852f6e0eb36f0f73da29d5bc55f1488253935a --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.322s)
2021-04-14T02:00:34.298Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.710s)
2021-04-14T02:00:34.303Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.187s)
2021-04-14T02:00:36.733Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 4.120s)
2021-04-14T02:00:36.733Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.488s)
2021-04-14T02:00:40.491Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.746s)
2021-04-14T02:00:45.398Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.199s)
2021-04-14T02:00:48.291Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mjuston2-linj2-bingyan2-austinl8 - mjuston2 (has token)
2021-04-14T02:00:50.958Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.610s)
2021-04-14T02:00:58.490Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mjuston2 - mjuston2 (has token)
2021-04-14T02:01:04.453Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 5.957s)
2021-04-14T02:06:50.130Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 12.5s of which 340.9s paused, total 353.4s
2021-04-14T02:19:00.617Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 4.0s of which 0.0s paused, total 4.0s
```

### LINKED ISSUE #12562: Desktop fails to run pre-commit hooks on node 16+
### Describe the bug
On Windows systems with WSL installed, GitHub desktop will run pre-commit scripts on WSL instead of running them in PowerShell regardless of which shell the user has picked to use. This results in the scripts looking for windows locations that don't exist on WSL.

### Version & OS
Version 2.9.0 on Windows 10 21H1 build 19043.1081 running with WSL 2 on Ubuntu 20.04

### Steps to reproduce the behavior

1. Make some changes to a file in a project with a pre-commit script (I'm using the npm package husky which installs these)
2. Add a commit message and try to commit
3. You should get the following error

### Expected behavior
GitHub desktop runs the pre-commit scripts on windows PowerShell, just like git does (tested this)

### Actual behavior
The scripts are run on WSL which causes errors

### Screenshots
image
(this path is correct for my system but may be different on others)

### Logs
This log has the error multiple times, which should help.
[2021-07-03.desktop.production.log](https://github.com/desktop/desktop/files/6758841/2021-07-03.desktop.production.log)

### Additional context
Got this error on the repositories discordjs/discord.js and discordjs/builders (forks of them) so you can try committing on these to see if you get the same errors. I also believe this issue should have relatively high priority since I am incapable of committing through my PC (unless I use git, which is more limited on some things and harder for me)

### LINKED ISSUE #12586: Git pre-commit hook fails to run because of "No such file or directory"
### Describe the bug

I have a `.git/hooks/pre-commit` which is exactly the following:

```sh
#!/bin/sh
npm test
```

When I commit via GitHub Desktop, it fails:

```
/bin/bash: C:/Program Files/nodejs/npm: No such file or directory
```

It works when committing via git CLI.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Create a hook as `.git/hooks/pre-commit`
2. Commit something

### Expected behavior

It should run the npm command

### Actual behavior

It says no such file

### Screenshots

image

### Logs

```
2021-07-09T14:34:12.623Z - info: [ui] [Timing] Action 'create commit' for 'saschanaz/types-web' took 0.292s
2021-07-09T14:35:53.954Z - info: [ui] Executing createCommit: git commit -F - (took 1.372s)
2021-07-09T14:35:53.963Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
/bin/bash: C:/Program Files/nodejs/npm: No such file or directory
```

### Additional context

This had been working but is regressed since a few months ago.

### LINKED ISSUE #13052: Lefthook Git hook returning executable file not found in %PATH%
### Describe the bug
Lefthook Git hook returning `executable file not found in %PATH%` when run from GitHub Desktop however does not throw error when run from Git bash

### Version & OS

Version 2.9.3

Windows 1809

### Steps to reproduce the behavior

1. Install [Lefthook](https://github.com/evilmartians/lefthook) to `PATH` & run `lefthook install`
2. Add `lefthook.yml` to repo folder as follows
   ```
   pre-commit:
     commands:
       fix-line-endings:
         glob: "*.{config}"
         run: unix2dos {staged_files}
   ```
1. Add `web.config` file to repo folder
2. Attempt to commit

### Expected behavior

pre-commit hook should run just as it does in Git Bash

### Actual behavior

pre-commit hook does not run as it does in Git Bash

### Screenshots

image

image

### LINKED ISSUE #14319: /usr/local/bin not in PATH for git hooks
### The problem

I have a pre-commit git hook with a Docker command like:

```
docker compose exec -T -u ...
```

When trying to commit files in GitHub Desktop I get an error from the hook "docker: command not found". Committing files from the command line works fine. On further investigation, it looks like `/usr/local/bin` is missing from my `PATH` when git hooks run from GitHub Desktop. Any ideas how to resolve this?

### Release version

2.9.12 (arm64)

### Operating system

macOS

### Steps to reproduce the behavior

_No response_

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niik**
Trying to wrap up what I started during our bug bash a few weeks back. Allow users to execute hooks in their shell environment (leveraging the system installed Git).

**If you're affected by any of the issues below and find your way here we'd really appreciate it if you could pull this down, build it, and try it out**

Closes https://github.com/desktop/desktop/issues/21317
Closes https://github.com/desktop/desktop/issues/20887
Closes https://github.com/desktop/desktop/issues/19652
Closes https://github.com/desktop/desktop/issues/19520
Closes https://github.com/desktop/desktop/issues/19001
Closes https://github.com/desktop/desktop/issues/18547
Closes https://github.com/desktop/desktop/issues/15286
Closes https://github.com/desktop/desktop/issues/14319
Closes https://github.com/desktop/desktop/issues/13052
Closes https://github.com/desktop/desktop/issues/12586
Closes https://github.com/desktop/desktop/issues/12562
Closes https://github.com/desktop/desktop/issues/11997
Closes https://github.com/desktop/desktop/issues/11603
Closes https://github.com/desktop/desktop/issues/10828
Closes https://github.com/desktop/desktop/issues/10060
Closes https://github.com/desktop/desktop/issues/9351
Closes https://github.com/desktop/desktop/issues/11523
Supersedes https://github.com/desktop/desktop/pull/20939

## Description

We have so many issues related to hooks that it's hard to list them all and I probably missed a few in the list above. The biggest problem is that GitHub Desktop ships with its own embedded Git installation on Windows and that environment is very likely to differ from what users have set up on their system. Hooks might rely on features not present in Desktop's GitHub (which is stripped to be as compact as possible) or they might rely on a version manager having been set up (like nvm) so it can't find node or some other tool it needs.

To complicate things further GitHub Desktop has no way of knowing whether a commit failed as a result of a Git hook rejecting the commit or something else. There's been attempts at addressing this by looking for patterns in the Git output (such as https://github.com/desktop/desktop/pull/20939) but this is fragile and will only catch well behaved hooks (like husky).

Hooks might also use terminal escape codes to add color to the output and GitHub Desktop hasn't had any way of interpreting this leading to issues like https://github.com/desktop/desktop/issues/18547).

In order to attempt to address all of this I've implemented an optional hook intercept option.

Screenshot 2025-11-27 at 11 29 04

When enabled we tell Git to go look for hooks in a special directory controlled by Desktop instead of the repository hook directory. Our custom hooks folder contains hook executables which connect back to Desktop where Desktop can execute the actual hook and proxy the output and exit codes back to the hook invoked by Git. One benefit of this is that GitHub Desktop is aware that a hook is running...

Screenshot 2025-11-27 at 11 29 29

...and can view the output as it's received by the actual hook. Another benefit is if the actual hook exits with an error we can choose to ignore that if the user chooses, allowing us to bypass a hook failure without having to first abort the commit and run it again with `--no-verify`.

But crucially this lets us have full control over what environment variables the hook gets invoked with. On macOS we will use shell specified by the `SHELL` environment variable (typically `zsh`), on Windows we'll default to Git Bash but support cmd.exe and powershell as well. We'll launch the shell and use a little helper executable (printenvz) to grab all environment variables from that shell including whatever gets set by tools like nvm invoked via shell login scripts such as .bash_profile.

Screenshot 2025-11-27 at 11 49 47

I've incorporated [xterm.js](https://xtermjs.org) to let us render colors as they would be rendered in a terminal. This doesn't just improve the behavior for repositories with hooks, all Git relates errors now leverage xtermjs to display Git output meaning that any error from any Git operation will be rendered as it would have been on the terminal.

Screenshot 2025-11-27 at 11 30 40

If we detect that a repository has commit hooks we'll also allow the user to preemptively bypass the `pre-commit` and `commit-msg` hooks using the `--no-verify` flag.
 
Screenshot 2025-11-27 at 11 39 02

### Screenshots

https://github.com/user-attachments/assets/e8aaaedd-91db-43f7-8efc-f639b4e6efe2

## Release notes

Notes:

### CODE REVIEW

**Review by mosherc — COMMENTED** [review]
Hook failure detection and reactive "ignore and continue" work flawlessly on MacOS! I have some minor non-blocking feedback on the proactive method though.

1. It would be nice if you could also enable the bypass by right clicking the commit button.
2. It would be nice to know if this is enabled without going into the settings menu (or the context menu via the above idea). This could be done with changed copy in the button ("Commit ... to branch bypassing hooks"), different color/style button, a hover title, or something like that. Understood if real estate is too limited though.
3. Not sure if this is intentional but the proactive method mentions the `--no-verify` flag name while the reactive method does not. Might be worth including or excluding from both to be consistent.

image

**Comment by niik** [comment]
> * It would be nice if you could also enable the bypass by right clicking the commit button.

Yeah, will run this by our a11y champ and see if there's any qualms with that.

> * It would be nice to know if this is enabled without going into the settings menu (or the context menu via the above idea). This could be done with changed copy in the button ("Commit ... to branch bypassing hooks"), different color/style button, a hover title, or something like that. Understood if real estate is too limited though.

100% agree, space is super limited here though as you already pointed out. And there's no clear iconography we could use to describe hooks either (not using a fishing hook)

> * Not sure if this is intentional but the proactive method mentions the `--no-verify` flag name while the reactive method does not. Might be worth including or excluding from both to be consistent.

Semi intentional, I think we'll probably end up removing it from the context menu but when you do `ignore and continue` you're not actually passing `--no-verify`, you're just returning 0 from _that specific hook_ and subsequent hooks could still fail (commit-msg) and require another ignore. So it doesn't make sense to call out no-verify in that case.

**Comment by niik** [comment]
Typed to fast, I forgot to say thank you so much for pulling this down and giving it a spin @mosherc, really appreciate it! :sparkles:

File: app/src/lib/app-state.ts [hunk 1]
```diff
@@ -582,8 +589,18 @@ export interface IRepositoryState {
...
    * cherry-pick, squash, reorder... */
   readonly multiCommitOperationState: IMultiCommitOperationState | null
+
+  /**
+   * Whether there are any hooks in the repository that could be
+   * skipped during commit with the --no-verify flag
+   */
+  readonly hasCommitHooks: boolean
+
+  readonly skipCommitHooks: boolean
```
Comment (sergiou87) [inline app/src/lib/app-state.ts:603]: Nit: add a comment to this since every other field in this interface has one?

File: app/src/lib/menu-item.ts [hunk 2]
```diff
@@ -8,7 +8,9 @@ export interface IMenuItem {
   readonly action?: () => void
 
   /** The type of item. */
-  readonly type?: 'separator'
+  readonly type?: 'separator' | 'checkbox'
+
+  readonly checked?: boolean
```
Comment (sergiou87) [inline app/src/lib/menu-item.ts:14]: Nit: for consistency add a comment too?

File: app/src/lib/hooks/hooks-proxy.ts [hunk 3]
```diff
@@ -0,0 +1,197 @@
...
+
+    const { code, signal } = await new Promise<{
+      code: number | null
+      signal: NodeJS.Signals | null
+    }>((resolve, reject) => {
+      conn.on('close', abort)
+
+      const child = spawn(gitPath, args, {
+        cwd: proxyCwd,
+        env: { ...shellEnv.env, ...safeEnv, GITHUB_DESKTOP: '1' },
```
Comment (sergiou87) [inline app/src/lib/hooks/hooks-proxy.ts:153]: Nit: Probably worth adding a comment documenting the `GITHUB_DESKTOP=1` variable and its purpose 🤔

File: vendor/printenvz/build/Makefile [hunk 4]
```diff
@@ -0,0 +1,347 @@
+# We borrow heavily from the kernel build setup, though we are simpler since
```
Comment (sergiou87) [inline vendor/printenvz/build/Makefile]: Do we really want to include all the `build` stuff? [We're ignoring it](https://github.com/desktop/desktop/blob/df1816aee66ab66238d884007a7149e53a0eb256/.gitignore#L8-L10) for other native modules.

File: vendor/printenvz/binding.gyp [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+          "xcode_settings": {
+            "OTHER_CPLUSPLUSFLAGS": ["-std=c++11", "-stdlib=libc++"],
+            "OTHER_LDFLAGS": ["-stdlib=libc++"],
+            "MACOSX_DEPLOYMENT_TARGET": "10.7"
+          }
+        }]
+      ]
+    }
+  ]
+}
```
Comment (sergiou87) [inline vendor/printenvz/binding.gyp:40]: Per https://github.com/github/security-reviews/issues/299

You might want to consider adding certain flags like the ones from https://github.com/desktop/desktop-trampoline/pull/1

**Review by sergiou87 — CHANGES_REQUESTED** [review]
Awesome work!!!! Just have a few comments

File: vendor/printenvz/build/Makefile (hunk 4 above)
Comment (niik) [reply vendor/printenvz/build/Makefile]: Lol, no definitely not. Let me get rid of it!

File: vendor/printenvz/binding.gyp (hunk 5 above)
Comment (niik) [reply vendor/printenvz/binding.gyp:40]: Done!

**Review by sergiou87 — DISMISSED** [review]
Thank you for those changes! 😗👌

**Review by sergiou87 — APPROVED** [review]

**Comment by zhihaolai** [comment]
That's cool. Good job, bro.

**Comment by 0xsarawut** [comment]
> 
> 
> Trying to wrap up what I started during our bug bash a few weeks back. Allow users to execute hooks in their shell environment (leveraging the system installed Git).
> 
> **If you're affected by any of the issues below and find your way here we'd really appreciate it if you could pull this down, build it, and try it out**
> 
> Closes https://github.com/desktop/desktop/issues/21317
> Closes https://github.com/desktop/desktop/issues/20887
> Closes https://github.com/desktop/desktop/issues/19652
> Closes https://github.com/desktop/desktop/issues/19520
> Closes https://github.com/desktop/desktop/issues/19001
> Closes https://github.com/desktop/desktop/issues/18547
> Closes https://github.com/desktop/desktop/issues/15286
> Closes https://github.com/desktop/desktop/issues/14319
> Closes https://github.com/desktop/desktop/issues/13052
> Closes https://github.com/desktop/desktop/issues/12586
> Closes https://github.com/desktop/desktop/issues/12562
> Closes https://github.com/desktop/desktop/issues/11997
> Closes https://github.com/desktop/desktop/issues/11603
> Closes https://github.com/desktop/desktop/issues/10828
> Closes https://github.com/desktop/desktop/issues/10060
> Closes https://github.com/desktop/desktop/issues/9351
> Closes https://github.com/desktop/desktop/issues/11523
> Supersedes https://github.com/desktop/desktop/pull/20939
> 
> ## Description
> 
> 
> We have so many issues related to hooks that it's hard to list them all and I probably missed a few in the list above. The biggest problem is that GitHub Desktop ships with its own embedded Git installation on Windows and that environment is very likely to differ from what users have set up on their system. Hooks might rely on features not present in Desktop's GitHub (which is stripped to be as compact as possible) or they might rely on a version manager having been set up (like nvm) so it can't find node or some other tool it needs.
> 
> To complicate things further GitHub Desktop has no way of knowing whether a commit failed as a result of a Git hook rejecting the commit or something else. There's been attempts at addressing this by looking for patterns in the Git output (such as https://github.com/desktop/desktop/pull/20939) but this is fragile and will only catch well behaved hooks (like husky).
> 
> Hooks might also use terminal escape codes to add color to the output and GitHub Desktop hasn't had any way of interpreting this leading to issues like https://github.com/desktop/desktop/issues/18547).
> 
> In order to attempt to address all of this I've implemented an optional hook intercept option.
> 
> Screenshot 2025-11-27 at 11 29 04
> 
> When enabled we tell Git to go look for hooks in a special directory controlled by Desktop instead of the repository hook directory. Our custom hooks folder contains hook executables which connect back to Desktop where Desktop can execute the actual hook and proxy the output and exit codes back to the hook invoked by Git. One benefit of this is that GitHub Desktop is aware that a hook is running...
> 
> Screenshot 2025-11-27 at 11 29 29
> 
> ...and can view the output as it's received by the actual hook. Another benefit is if the actual hook exits with an error we can choose to ignore that if the user chooses, allowing us to bypass a hook failure without having to first abort the commit and run it again with `--no-verify`.
> 
> But crucially this lets us have full control over what environment variables the hook gets invoked with. On macOS we will use shell specified by the `SHELL` environment variable (typically `zsh`), on Windows we'll default to Git Bash but support cmd.exe and powershell as well. We'll launch the shell and use a little helper executable (printenvz) to grab all environment variables from that shell including whatever gets set by tools like nvm invoked via shell login scripts such as .bash_profile.
> 
> Screenshot 2025-11-27 at 11 49 47
> 
> 
> I've incorporated [xterm.js](https://xtermjs.org) to let us render colors as they would be rendered in a terminal. This doesn't just improve the behavior for repositories with hooks, all Git relates errors now leverage xtermjs to display Git output meaning that any error from any Git operation will be rendered as it would have been on the terminal.
> 
> Screenshot 2025-11-27 at 11 30 40
> 
> If we detect that a repository has commit hooks we'll also allow the user to preemptively bypass the `pre-commit` and `commit-msg` hooks using the `--no-verify` flag.
>  
> Screenshot 2025-11-27 at 11 39 02
> 
> ### Screenshots
> 
> 
> 
> https://github.com/user-attachments/assets/e8aaaedd-91db-43f7-8efc-f639b4e6efe2
> 
> ## Release notes
> 
> 
> 
> Notes:
> 
For further credit to Sarawut Kaewyana's Donor Advised Fund advised by Sarawut Kaewyana (ID: 7fc9050f-b221-4be4-98aa-73a0725f9e6a).

File: app/src/ui/preferences/git.tsx [hunk 6]
```diff
@@ -19,28 +26,165 @@ interface IGitProps {
...
+          value={
+            this.props.enableGitHookEnv ? CheckboxValue.On : CheckboxValue.Off
+          }
+          onChange={this.onEnableGitHookEnvChanged}
+        />
+        <p className="git-hooks-env-description">
+          When enabled, GitHub Desktop will attempt to load environment
+          variables from your shell when executing Git hooks. This is useful if
+          your Git hooks depend on environment variables set in your shell
+          configuration files, a common practive for version managers such as
```
Comment (Guiorgy) [inline app/src/ui/preferences/git.tsx:99]: typo: practi***v***e 😅

Edit: #21697

Edit2: PR with a fix merged (GitHub doesn't allow me to resolve this though)

**Review by tomritzow — COMMENTED** [review]
@

**Comment by 18488292860-coder** [comment]
> Trying to wrap up what I started during our bug bash a few weeks back. Allow users to execute hooks in their shell environment (leveraging the system installed Git).
> 
> **If you're affected by any of the issues below and find your way here we'd really appreciate it if you could pull this down, build it, and try it out**
> 
> Closes #21317 Closes #20887 Closes #19652 Closes #19520 Closes #19001 Closes #18547 Closes #15286 Closes #14319 Closes #13052 Closes #12586 Closes #12562 Closes #11997 Closes #11603 Closes #10828 Closes #10060 Closes #9351 Closes #11523 Supersedes #20939
> 
> ## Description
> We have so many issues related to hooks that it's hard to list them all and I probably missed a few in the list above. The biggest problem is that GitHub Desktop ships with its own embedded Git installation on Windows and that environment is very likely to differ from what users have set up on their system. Hooks might rely on features not present in Desktop's GitHub (which is stripped to be as compact as possible) or they might rely on a version manager having been set up (like nvm) so it can't find node or some other tool it needs.
> 
> To complicate things further GitHub Desktop has no way of knowing whether a commit failed as a result of a Git hook rejecting the commit or something else. There's been attempts at addressing this by looking for patterns in the Git output (such as #20939) but this is fragile and will only catch well behaved hooks (like husky).
> 
> Hooks might also use terminal escape codes to add color to the output and GitHub Desktop hasn't had any way of interpreting this leading to issues like #18547).
> 
> In order to attempt to address all of this I've implemented an optional hook intercept option.
> 
> Screenshot 2025-11-27 at 11 29 04
> When enabled we tell Git to go look for hooks in a special directory controlled by Desktop instead of the repository hook directory. Our custom hooks folder contains hook executables which connect back to Desktop where Desktop can execute the actual hook and proxy the output and exit codes back to the hook invoked by Git. One benefit of this is that GitHub Desktop is aware that a hook is running...
> 
> Screenshot 2025-11-27 at 11 29 29
> ...and can view the output as it's received by the actual hook. Another benefit is if the actual hook exits with an error we can choose to ignore that if the user chooses, allowing us to bypass a hook failure without having to first abort the commit and run it again with `--no-verify`.
> 
> But crucially this lets us have full control over what environment variables the hook gets invoked with. On macOS we will use shell specified by the `SHELL` environment variable (typically `zsh`), on Windows we'll default to Git Bash but support cmd.exe and powershell as well. We'll launch the shell and use a little helper executable (printenvz) to grab all environment variables from that shell including whatever gets set by tools like nvm invoked via shell login scripts such as .bash_profile.
> 
> Screenshot 2025-11-27 at 11 49 47
> I've incorporated [xterm.js](https://xtermjs.org) to let us render colors as they would be rendered in a terminal. This doesn't just improve the behavior for repositories with hooks, all Git relates errors now leverage xtermjs to display Git output meaning that any error from any Git operation will be rendered as it would have been on the terminal.
> 
> Screenshot 2025-11-27 at 11 30 40
> If we detect that a repository has commit hooks we'll also allow the user to preemptively bypass the `pre-commit` and `commit-msg` hooks using the `--no-verify` flag.
> 
> Screenshot 2025-11-27 at 11 39 02
> ### Screenshots
>  CleanShot.2025-11-21.at.14.20.37.mp4 
> ## Release notes
> Notes:

File: app/src/ui/preferences/git.tsx (hunk 6 above)
Comment (viv2n08-gif) [reply app/src/ui/preferences/git.tsx:99]: https://github.com/github/docs.git

**Comment by jitendrasinghofficial17-stack** [comment]
> Trying to wrap up what I started during our bug bash a few weeks back. Allow users to execute hooks in their shell environment (leveraging the system installed Git).
> 
> **If you're affected by any of the issues below and find your way here we'd really appreciate it if you could pull this down, build it, and try it out**
> 
> Closes #21317 Closes #20887 Closes #19652 Closes #19520 Closes #19001 Closes #18547 Closes #15286 Closes #14319 Closes #13052 Closes #12586 Closes #12562 Closes #11997 Closes #11603 Closes #10828 Closes #10060 Closes #9351 Closes #11523 Supersedes #20939
> 
> ## Description
> We have so many issues related to hooks that it's hard to list them all and I probably missed a few in the list above. The biggest problem is that GitHub Desktop ships with its own embedded Git installation on Windows and that environment is very likely to differ from what users have set up on their system. Hooks might rely on features not present in Desktop's GitHub (which is stripped to be as compact as possible) or they might rely on a version manager having been set up (like nvm) so it can't find node or some other tool it needs.
> 
> To complicate things further GitHub Desktop has no way of knowing whether a commit failed as a result of a Git hook rejecting the commit or something else. There's been attempts at addressing this by looking for patterns in the Git output (such as #20939) but this is fragile and will only catch well behaved hooks (like husky).
> 
> Hooks might also use terminal escape codes to add color to the output and GitHub Desktop hasn't had any way of interpreting this leading to issues like #18547).
> 
> In order to attempt to address all of this I've implemented an optional hook intercept option.
> 
> Screenshot 2025-11-27 at 11 29 04
> When enabled we tell Git to go look for hooks in a special directory controlled by Desktop instead of the repository hook directory. Our custom hooks folder contains hook executables which connect back to Desktop where Desktop can execute the actual hook and proxy the output and exit codes back to the hook invoked by Git. One benefit of this is that GitHub Desktop is aware that a hook is running...
> 
> Screenshot 2025-11-27 at 11 29 29
> ...and can view the output as it's received by the actual hook. Another benefit is if the actual hook exits with an error we can choose to ignore that if the user chooses, allowing us to bypass a hook failure without having to first abort the commit and run it again with `--no-verify`.
> 
> But crucially this lets us have full control over what environment variables the hook gets invoked with. On macOS we will use shell specified by the `SHELL` environment variable (typically `zsh`), on Windows we'll default to Git Bash but support cmd.exe and powershell as well. We'll launch the shell and use a little helper executable (printenvz) to grab all environment variables from that shell including whatever gets set by tools like nvm invoked via shell login scripts such as .bash_profile.
> 
> Screenshot 2025-11-27 at 11 49 47
> I've incorporated [xterm.js](https://xtermjs.org) to let us render colors as they would be rendered in a terminal. This doesn't just improve the behavior for repositories with hooks, all Git relates errors now leverage xtermjs to display Git output meaning that any error from any Git operation will be rendered as it would have been on the terminal.
> 
> Screenshot 2025-11-27 at 11 30 40
> If we detect that a repository has commit hooks we'll also allow the user to preemptively bypass the `pre-commit` and `commit-msg` hooks using the `--no-verify` flag.
> 
> Screenshot 2025-11-27 at 11 39 02
> ### Screenshots
>  CleanShot.2025-11-21.at.14.20.37.mp4 
> 
> ## Release notes
> Notes:

Today 9/03/2026
