### PR TITLE
(almost) always be updating

### LINKED ISSUE #2373: update cleaning up old git.exe when it shouldn't
### Description

@NickCraver reported on Twitter that he encountered this Git error, which is a generic and questionable message when we can't resolve the packaged Git:

However after this he hasn't been able to launch Desktop at all. No errors, no logs, just silence.

### Version

**GitHub Desktop version:** 0.7.0 -> 0.7.2
**OS version:** Windows 10 I guess

### Steps to Reproduce

TBC, seems to be something like this:

 - Open app running 0.7.0
 - Update app to 0.7.x (latest version) (in background? or manually?)
 - Leave app open, keep doing Git things
 - :boom:

**Expected behavior:** The current version's bits are still on disk until the app is closed, and cleaned up In The Future™

**Actual behavior:** Files related to the running app were cleaned up, and now the app doesn't launch. Not sure if these are related, let's assume so.

**Reproduces how often:** lol I have no idea

### Logs

`SquirrelSetup.log` is interesting:

setup

It excluded `0.7.1` and `0.7.2` when cleaning up old versions, but not the running `0.7.0` version. Could this be related to us rolling out delta updates? [Full log is here](https://gist.github.com/NickCraver/5fbeedfaa316960b800e12cacdab22ce#file-squirrelsetup-log)

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2373 by ignoring requests to check for updates when the app has downloaded and applied an update and is ready for restarting.

### CODE REVIEW

File: app/src/ui/lib/update-store.ts [hunk 1]
```diff
@@ -150,6 +150,13 @@ class UpdateStore {
    *                       this check user-initiated?
    */
   public checkForUpdates(inBackground: boolean) {
+    // An update has been downloaded and the app is waiting to be restarted.
+    // Checking for updates again may result in the running app being nuked
+    // when it finds a subsequent update.
+    if (this.status === UpdateStatus.UpdateReady) {
```
Comment (joshaber) [inline app/src/ui/lib/update-store.ts]: Could we conditionalize this for Windows? Mac should be fine.

**Comment by shiftkey** [comment]
:apple:
