### PR TITLE
Prioritize repo account for generating commit messages

### LINKED ISSUE #21484: Using personal account for Copilot when I selected enterprise account for a repo
### The problem

The issue is simple. Github Desktop is using my personal login for Copilot operations even though I am committing from my enterprise account.

### Release version

3.5.4

### Operating system

Windows 11

### Steps to reproduce the behavior

In Git Settings, select enterprise account.
Click on little copilot icon
Receive a message that Payment Required

### Screenshots

Image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #21484

## Description
Sort accounts to prefer the one associated with the current repository before selecting an account for commit message generation. Uses getAccountForRepository to identify the repository-specific account and moves it to the front of the list so enableCommitMessageGeneration will pick it when available, avoiding selection of an unrelated account.

## Release notes

Notes: [Fixed] Choose the best account for the current repository to generate commit messages

### CODE REVIEW

**Review by tidy-dev — DISMISSED** [review]

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -5602,7 +5602,19 @@ export class AppStore extends TypedBaseStore<IAppState> {
...
+    const accounts = Array.from(this.getState().accounts).sort((a, b) => {
+      if (a === repositoryAccount) {
+        return -1
+      } else if (b === repositoryAccount) {
+        return 1
+      } else {
+        return 0
+      }
+    })
+    const account = accounts.find(enableCommitMessageGeneration)
```
Comment (niik) [inline app/src/lib/stores/app-store.ts]: Let me preface this by saying that I'm happy with this change and you can absolutely go ahead an merge but curiosity got the best of me here. Do we really need to sort? Right now chances are low that there's more than one account and even with multiple enterprise accounts there'd be few. When we do support multiple accounts for real I imagine it'd still be super rare to have more than a couple of accounts. Feels like we could just check if the repo account works no?

```ts
// prefer the account that is associated to this repository.
const repositoryAccount = getAccountForRepository(this.accounts, repository)
    const account =
      repositoryAccount && enableCommitMessageGeneration(repositoryAccount)
        ? repositoryAccount
        : this.accounts.find(enableCommitMessageGeneration)
```

Comment (sergiou87) [reply app/src/lib/stores/app-store.ts]: It's a great question! Since I was changing this code, I just wanted to make it as generic and future-proof as possible, but agree this might be too much 😂  I'm gonna go ahead with your suggestion instead!

**Review by niik — APPROVED** [review]
