### PR TITLE
chore: backport fixes from rebase dialog to merge dialog

### LINKED ISSUE #7043: backport fixes from rebase conflicts dialog review to merge conflicts
Some things uncovered in #6961 that should be brought back to the Merge Conflicts dialog once #6961 is merged:

 - #6032 means we should set `Dialog.title` to a JSX element (and update the CSS because of the DOM changes)

https://github.com/desktop/desktop/blob/5d9eab1801edd2413be9db323aa0101f5dcc9ebc/app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx#L244-L248

And also for the Merge Branch selector:

https://github.com/desktop/desktop/blob/b5529325ae629a52b02cb3e07699f1ccbcfb2cfa/app/src/ui/merge-branch/merge.tsx#L262-L271

 - these colours should be replaced with variables defined in `variables.scss` values (or add new values) to ensure they can be styled correctly with different themes

https://github.com/desktop/desktop/blob/5d9eab1801edd2413be9db323aa0101f5dcc9ebc/app/styles/ui/dialogs/_merge-conflicts.scss#L83-L95

 - the arrow octicon should have an explicit height and width if set in CSS - more context here https://github.com/desktop/desktop/pull/6961#discussion_r263800531

https://github.com/desktop/desktop/blob/5d9eab1801edd2413be9db323aa0101f5dcc9ebc/app/styles/ui/dialogs/_merge-conflicts.scss#L109-L114

### PR DESCRIPTION
**Pull request by HashimotoYT**
## Overview

**Closes #7043**

## Description

- Backported fixes from rebase dialog to merge and merge conflicts dialog.

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by billygriffin** [comment]
Hi @HashimotoYT, sorry for the delay! Should I mark this `ready-for-review`?

File: app/src/ui/merge-branch/merge.tsx [hunk 1]
```diff
@@ -258,16 +257,12 @@ export class Merge extends React.Component<IMergeProps, IMergeState> {
         id="merge"
         onDismissed={this.props.onDismissed}
         onSubmit={this.merge}
+        title={
+          <div className="merge-dialog-header">
+            Merge into <b>{currentBranchName}</b>
```
Comment (niik) [inline app/src/ui/merge-branch/merge.tsx]: Could we use `strong` instead of `b` here in order to stay consistent with the rebase dialog please?

File: app/src/ui/merge-branch/merge.tsx [hunk 2]
```diff
@@ -258,16 +257,12 @@ export class Merge extends React.Component<IMergeProps, IMergeState> {
         id="merge"
         onDismissed={this.props.onDismissed}
         onSubmit={this.merge}
+        title={
+          <div className="merge-dialog-header">
```
Comment (niik) [inline app/src/ui/merge-branch/merge.tsx]: In a similar vein to the rebase dialog I don't think we need this wrapping element any more. We should be able to change this to `<>Merge into <strong>${currentBranchName}</strong></>` and update the CSS just like we did in the rebase dialog by moving the `.merge-dialog-header` selector into the the `.dialog-header` selector and changing it to `h1`. Something like this

https://github.com/desktop/desktop/blob/6206729db9212815a14fe761637be28a036c01d2/app/styles/ui/dialogs/_rebase.scss#L13-L19

**Comment by HashimotoYT** [comment]
@niik changes made.

**Comment by niik** [comment]
Thank you @HashimotoYT!
