### PR TITLE
Discard untracked changes when permanently deleting files.

### LINKED ISSUE #20428: Discard added files not working on windows if trash bin settings are changed
### The problem

Good morning,

I found a strange behaviour when discarding added files on desktop application with windows operating system and trash bin settings changed.

If the recycle bin properties are set to "Don't move files to the Recycle Bin. Remove files immediately when deleted" discarding changes won't do anything to newly added files

Image

### Release version

3.4.19

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Left Click on trash bin > Properties > Enable "Don't move files to the Recycle Bin. Remove files immediately when deleted" 
3. Add any file to a git repository
4. On GitHub Desktop, left click on the added file > Discard
5. No changes will happen

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes #20428

## Description
This PR fixes where untracked change were not deleted when discarding changes permanently. This is because we choose which files to reset based on the index, and untracked files are not detected as changes in the index.

## Release notes

Notes: [Fixed] Delete untracked files when deleting permanently as opposed to moving to trash.

### CODE REVIEW

File: app/src/lib/stores/git-store.ts [hunk 1]
```diff
@@ -1505,6 +1505,7 @@ export class GitStore extends BaseStore {
 
   public async discardChanges(
     files: ReadonlyArray<WorkingDirectoryFileChange>,
+    repoPath: string,
```
Comment (niik) [inline app/src/lib/stores/git-store.ts]: Can't we use `this.repository.path` in this method instead of passing? It seems that's what we're doing in the previous version of this code

File: app/src/lib/stores/git-store.ts [hunk 2]
```diff
@@ -1516,22 +1517,25 @@ export class GitStore extends BaseStore {
...
+          } catch (e) {
+            if (askForConfirmationOnDiscardChangesPermanently) {
+              throw new DiscardChangesError(e, this.repository, files)
+            }
           }
+        } else if (file.status.kind === AppFileStatusKind.Untracked) {
+          // Removing untracked files as they will not be reset since they are
+          // no detected as changes in the index. We need to remove them
+          // manually.
+          rm(Path.join(repoPath, file.path))
```
Comment (niik) [inline app/src/lib/stores/git-store.ts]: We need to await this, and (I imagine) also handle if the file can't be deleted (locked, in use, etc)

**Review by niik — CHANGES_REQUESTED** [review]
I think there are two problems here of which one is addressed by this PR. The second issue is when a user attempts to discard a file and the `moveToTrash` call fails whereupon we typically throw a DiscardChangesError which then triggers this dialog

Screenshot 2025-05-08 at 11 40 32

If the user opts to not show this dialog again then discarding changes won't throw the DiscardChangesError and the error will just be silently ignored. Now we could just go for the `rm` route when `moveItemToTrash` fails and `askForConfirmationOnDiscardChangesPermanently` is false but that feels weird to me since there's more than one reason why `moveItemToTrash` might fail. It seems like we're talking about two different settings here. Like we should have a way to tell Desktop to always straight up delete, never move to trash, and then an option for whether to show a confirmation when deleting permanently which would only come into effect when the former setting is true. Then the error for `moveItemToTrash` would always show when it fails because that's an error.

I feel like that was a lot of incoherent words. If you feel the same we should talk synchronously and iron this out.

File: app/src/lib/stores/git-store.ts (hunk 2 above)
Comment (tidy-dev) [reply app/src/lib/stores/git-store.ts]: Added the await -> If this would fail there is a catch block on the in the `_discardChanges` at the app-store level that would show a user an error in that case.

File: app/src/lib/stores/git-store.ts (hunk 1 above)
Comment (tidy-dev) [reply app/src/lib/stores/git-store.ts]: Ah. Good call out. I am so used to working in the app-store where we usually pass repositories into our methods. :P

**Comment by tidy-dev** [comment]
As discussed,

This PR is attempting to just fix the current flow of retry/prompt for permanently delete when moving to trash fails by adding `rm` for untracked files.

Latest commits address PR comments and fixes where if the prompt check has been ticked it also removes untracked files.

https://github.com/user-attachments/assets/ba2ec138-7757-4a68-a6f8-f085a763f8d0

This means we always attempt to move a file to trash, we just may also remove untracked files manually if that fails. 

We will discuss another approach to the whole user scenario of "How to handle issues with move to trash problems" of changing this dialog to just be an error (no retry, no "don't show again"), but we add an app setting that allows users to opt out of moving to trash and we tell the user about that setting in the error dialog so they can go there and set that and then retry. This would also mean instead of attempting to move the file to trash every time, we can just skip that step.

**Review by niik — APPROVED** [review]
