### PR TITLE
fix: inconsistent rebase behaviour

### LINKED ISSUE #19816: Collection: Inconsistent Rebase Behaviour
### The problem

The rebase functionality of GHD has some flaws and differs from the git command line behaviour.
This issue is used to collect all reported behaviour in order to fix them alltogether.

## Related Issues and PRs
#19813
#19031
#17892
 #19014

## Test Setup
A dummy repository containing a single `ReadMe` file.
All possible rebase operations are tested via GHD menu and via command line to compare results.
Results for each test case are tracked as comments in this issue.

### Branches
- `develop`: default branch, contains 2 commits
- `ahead`: is 1 commit ahead of `develop`
- `behind`: is 1 commit behind `develop`
- `ahead-and-behind`: is 1 commit behind and 1 commit ahead of `develop`

### Release version

latest

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Select and checkout base branch.
2. Open menu `Branch` -> `Rebase current branch...`.
3. Select a source branch.
4. Try to rebase.

### PR DESCRIPTION
**Pull request by sfadschm**
Closes #19816, #19014,  #17892
Supersedes #19031

### CODE REVIEW

**Comment by sfadschm** [comment]
The current state now correctly handles all test cases in #19816.

File: app/src/ui/history/merge-call-to-action-with-conflicts.tsx [hunk 1]
```diff
@@ -250,7 +250,7 @@ export class MergeCallToActionWithConflicts extends React.Component<
     return (
       <div className="merge-message merge-message-loading">
         Checking for ability to {this.state.selectedOperation.toLowerCase()}{' '}
-        automatically…
+        automatically …
```
Comment (sergiou87) [inline app/src/ui/history/merge-call-to-action-with-conflicts.tsx]: Typo?
```suggestion
        automatically…
```

File: app/src/ui/history/merge-call-to-action-with-conflicts.tsx [hunk 2]
```diff
@@ -270,6 +270,7 @@ export class MergeCallToActionWithConflicts extends React.Component<
           <strong>{`${this.commitCount} ${pluralized}`}</strong>
           {` on top of `}
           <strong>{branch.name}</strong>
+          {`.`}
```
Comment (sergiou87) [inline app/src/ui/history/merge-call-to-action-with-conflicts.tsx]: I'd say it's better if we stick to the original style without `.` at the end of all these messages… sorry!
```suggestion
```

File: app/src/ui/lib/update-branch.ts [hunk 3]
```diff
@@ -24,7 +24,7 @@ export function getMergeOptions(): ReadonlyArray<IDropdownSelectButtonOption> {
     {
       label: 'Rebase',
       description:
-        'The commits from the selected branch will be rebased and added to the current branch.',
+        'The selected branch is applied as the new base commit of the current branch and the excess commits in the current branch are applied on top of the new base.',
```
Comment (sergiou87) [inline app/src/ui/lib/update-branch.ts]: I think this description is harder to understand than the previous one 🤔  Does it add any info I might be missing? 😳

File: app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx [hunk 4]
```diff
@@ -171,7 +171,7 @@ export class MergeChooseBranchDialog extends React.Component<
   }
 
   private renderLoadingMergeMessage() {
-    return <>Checking for ability to merge automatically...</>
+    return <>Checking for ability to merge automatically ...</>
```
Comment (sergiou87) [inline app/src/ui/multi-commit-operation/choose-branch/merge-choose-branch-dialog.tsx]:
```suggestion
    return <>Checking for ability to merge automatically…</>
```

File: app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx [hunk 5]
```diff
@@ -147,7 +148,7 @@ export class RebaseChooseBranchDialog extends React.Component<
   }
 
   private renderLoadingRebaseMessage() {
-    return <>Checking for ability to rebase automatically…</>
+    return <>Checking for ability to rebase automatically …</>
```
Comment (sergiou87) [inline app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx]:
```suggestion
    return <>Checking for ability to rebase automatically…</>
```

File: app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx [hunk 6]
```diff
@@ -157,25 +158,43 @@ export class RebaseChooseBranchDialog extends React.Component<
...
+    if (commitsBehindCount > 0 && commitsAheadCount <= 0) {
+      const pluralized = commitsBehindCount === 1 ? 'commit' : 'commits'
       return (
         <>
-          This branch is up to date with{` `}
-          <strong>{currentBranch.name}</strong>
+          This will fast-forward <strong>{currentBranch.name}</strong>
+          {` to `}
+          <strong>{baseBranch.name}</strong> by applying
+          <strong>{` ${commitsBehindCount} ${pluralized}`}</strong>.
```
Comment (sergiou87) [inline app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx]: Hmmm I think the `by applying X commits` shouldn't be necessary here, right? If it fast-forwards it should be clear they "become the say".

**Review by sergiou87 — CHANGES_REQUESTED** [review]
Thank you for your contribution! 💖 

Some style/copy changes before I re-check the logic. Please, remove all the trailing `.` from the messages!

File: app/src/ui/history/merge-call-to-action-with-conflicts.tsx (hunk 2 above)
Comment (sfadschm) [reply app/src/ui/history/merge-call-to-action-with-conflicts.tsx]: Okay, I just found some messages containing them and some not. My favorite was to round the message up with the dot, but I can revert that.

File: app/src/ui/lib/update-branch.ts (hunk 3 above)
Comment (sfadschm) [reply app/src/ui/lib/update-branch.ts]: I will pull this change out to a new PR, that migh make discussion a bit easier. But granted, the new description is not optimal too :-D

File: app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx (hunk 6 above)
Comment (sfadschm) [reply app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx]: "by applying" might be misleading, good point.
The goal was to give some more information about the consequences.

E.g., I want to fast forward to a small feature branch but choose the wrong one. A notification like "this will add 576 new commits" might save my day.

This is open for discussion though.

File: app/src/ui/lib/update-branch.ts (hunk 3 above)
Comment (sfadschm) [reply app/src/ui/lib/update-branch.ts]: Extracted.

**Comment by sfadschm** [comment]
Force pushed with style/punctuation changes.

File: app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx (hunk 6 above)
Comment (sfadschm) [reply app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx]: One more thing to consider:
The merge dialog states the number of commits and makes no distinction between fast-forward and non-ff operation.

https://github.com/desktop/desktop/blob/development/app%2Fsrc%2Fui%2Fmulti-commit-operation%2Fchoose-branch%2Fmerge-choose-branch-dialog.tsx#L191-L201

I would vote to keep the number for reading, but rephrase the message.

Comment (sergiou87) [reply app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx]: > The goal was to give some more information about the consequences.

That's a good point… maybe just `by adding X commits`? Or `including`? 🤔 

Or what about… `This will fast-forward <current-branch> X commits to match <base-branch>` ? I think this one is the most concise and no need to worry about verbs 😄

Comment (sfadschm) [reply app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx]: I like the second option, sounds sound 👍

Comment (sfadschm) [reply app/src/ui/multi-commit-operation/choose-branch/rebase-choose-branch-dialog.tsx]: Implemented.

**Comment by sfadschm** [comment]
Rebased.

**Review by sergiou87 — APPROVED** [review]
It looks good to me and works as expected, if I haven't done anything wrong (these things are confusing), but I'm gonna get a second pair of 👀  to double check I'm not missing anything!

**Comment by Leroy231** [comment]
Any movement on this? Seems it's just waiting on a second review

**Comment by sfadschm** [comment]
@niik @tidy-dev
Can any of you spare the time to review?

I consider this a Bugfix, as the current implementation hinders established git-workflows to be done with GHD (feature branches in this case).
Thank you!

**Review by tidy-dev — APPROVED** [review]
@sfadschm Thanks for your patience. This makes sense to me and I tested it and works as expected!

**Comment by sfadschm** [comment]
No worries, I think the staffing for the project has been clarified enough times for everyone to understand that this takes some time.

Looking forward to filtered changes :-)
