### PR TITLE
Fix not recognizing remote for partial clone/fetch

### LINKED ISSUE #16284: Doing a partial clone/fetch results in remote not being recognized
### The problem

If a repository is cloned or fetched with using a partial clone filter (ie using the --filter option), the GitHub Desktop application stops recognizing the remote and asks to publish the repository to GitHub:

image

This prevents the pulling and pushing of source from the remote and forces the end user to use other means to accomplish this.

Doing a partial clone/fetch is vital for large repositories where not all the blobs/tress are required to be pulled and is used to save transfer time, network traffic, and disk space.

### Release version

3.2.0

### Operating system

Windows 10 (10.0.19044)

### Steps to reproduce the behavior

(Running git 2.39.2.windows.1)

1. Clone repository from remote (GitHub, or GHES) via GitHub Desktop or other means
2. In git bash, run git fetch --filter=blob:none (partial fetch repository)
   - This will modify to the local .git/config:
   ```
   [remote "origin"]
        url = git@github.com:Org/repo
        fetch = +refs/heads/*:refs/remotes/origin/*
        promisor = true
        partialclonefilter = blob:none

   ```
3. Switch back to the GitHub Desktop and the application is asking to publish the repository as it has never been pushed before.

### Log files

_No response_

### Screenshots

_No response_

### Additional context

Not sure if this is a new functionality of the partial clone feature added to git that GitHub Desktop does not handle yet, or if this is something that is a regression with GitHub Desktop. I don't remember seeing this when using git prior to 3.29.

### PR DESCRIPTION
**Pull request by mkafrin**
Closes #16284

## Description

- `getRemotes` tries to parse out the lines from `git remote -v` relating to fetch by filtering for lines ending in "(fetch)". This however doesn't work for repos that were cloned using the `filter` flag, since the end of those lines end up instead looking like "(fetch) [blob:none]".
- This results in the remote of those repos not being recognized, which prevents pushing changes, but also breaks a lot of other features, like "Compare on Github", "View branch on Github", "Preview pull request", "Create pull request", etc.
- To fix this, the filter that checks if a line ends with "(fetch)" was changed to check if the line matches the regex where the line ends in "(fetch)" optionally followed by the git filter. This was the best way I thought to handle this, but if you can think of a better one I'm open to ideas.
- In addition, a new unit test was added to cover the behavior (and a new fixture for the test).
  - I copied the `repo-with-multiple-remotes` fixture for this and just changed the `config` file in _git to remove the second remote and make the origin remote a promisor remote (partial fetch/clone).

### Screenshots

This doesn't touch the UI, but the results are visible, so I'll post a before and after.

Before (notice disabled bottom menu options and "Publish Repository" button):
image

After (menu options enabled and "View on Github" instead of "Publish Repository"):
image

## Release notes

Notes:

### CODE REVIEW

File: app/test/unit/git/remote-test.ts [hunk 1]
```diff
@@ -61,6 +61,22 @@ describe('git/remote', () => {
       const remotes = await getRemotes(repository)
       expect(remotes).toHaveLength(0)
     })
+
+    it('returns promisor remote', async () => {
```
Comment (tidy-dev) [inline app/test/unit/git/remote-test.ts:65]: Would you mind updating this PR to this test and removing the new fixture. The fixtures are more useful if there is repository scenario used across multiple tests. 

```
it('returns promisor remote', async () => {
      const repository = await setupEmptyRepository()

      // Add a remote
      const url = 'https://github.com/desktop/not-found.git'
      await GitProcess.exec(
        ['remote', 'add', 'hasBlobFilter', url],
        repository.path
      )

      // Fetch a remote and add a filter
      await GitProcess.exec(['fetch', '--filter=blob:none'], repository.path)

      // Shows that the new remote does have a filter
      const rawGetRemote = await GitProcess.exec(
        ['remote', '-v'],
        repository.path
      )
      expect(rawGetRemote.stdout).toContain(url + ' (fetch) [blob:none]')

      // Shows that the `getRemote` returns that remote
      const result = await getRemotes(repository)
      expect(result).toHaveLength(1)
      expect(result[0].name).toEqual('hasBlobFilter')
    })
```

**Review by tidy-dev — CHANGES_REQUESTED** [review]
This is looking great! Thank you for working on this fix. 

I have one request and that is to remove the new test fixture in favor of using a test that doesn't require a fixture. We generally add fixtures when we need to repeat a repository setup across multiple tests or the setup is unduly complex. This scenario can be created by running a fetch against an repo with a remote. Thus, we can simplify this PR quite a bit.

File: app/test/unit/git/remote-test.ts (hunk 1 above)
Comment (mkafrin) [reply app/test/unit/git/remote-test.ts:65]: Yeah absolutely can do. Definitely seems better than having to add a new fixture.

**Comment by mkafrin** [comment]
> This is looking great! Thank you for working on this fix.
> 
> I have one request and that is to remove the new test fixture in favor of using a test that doesn't require a fixture. We generally add fixtures when we need to repeat a repository setup across multiple tests or the setup is unduly complex. This scenario can be created by running a fetch against an repo with a remote. Thus, we can simplify this PR quite a bit.

Thanks for the review. Will make that change. First time contributing to desktop so wasn't aware of the common practices for tests, so appreciate the info.

File: app/test/unit/git/remote-test.ts (hunk 1 above)
Comment (mkafrin) [reply app/test/unit/git/remote-test.ts:65]: Updated! Much simpler indeed!

**Review by tidy-dev — APPROVED** [review]
✨  Thank you for those changes!
