### PR TITLE
Don't show certificate error dialog when probing for endpoint kind

### LINKED ISSUE #18991: Certificate Validation issue with updated version of Gitlab
### The problem

We have an in-house GitLab server hosted at 172.16.7.121, accessible on our intranet. This IP is bound to the domain automationgit.meditab.com, and we've added the meditab.com domain certificate. Our repository, cloned using this domain URL, was working fine until now. However, with the latest GitLab version, we're encountering a certification validation error, as shown in the attached screenshot.

Note: The error message pop-up continues after clicking "Add certificate".

### Release version

3.4.2 (x64)

### Operating system

Windows Server 2019

### Steps to reproduce the behavior

1. Clone Repository
2. Pull Changes

### Log files

[2024-07-17.desktop.production.log](https://github.com/user-attachments/files/16261106/2024-07-17.desktop.production.log)

### Screenshots

Screenshot 2024-07-17 114845
Screenshot 2024-07-17 114913

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niik**
Closes #18991
Supersedes https://github.com/desktop/desktop/pull/19149

## Description

This PR supersedes #19149. Crucially this PR does not abandon the use of the Chromium network stack (by using the http/https node modules). Instead it suppresses the certificate error dialog for the specific probing URL by means of keeping track of a set of urls for which we shouldn't prompt for certificate errors.

Additionally this PR reduces the likelihood that Desktop makes a probing request in the first place by checking for the existence of several known third-party realms and assuming that a hostname of the format `github.somecorp.tld` is a GitHub Enterprise Server instance.
-->

## Release notes

Notes:

### CODE REVIEW

File: app/src/lib/api.ts [hunk 1]
```diff
@@ -2263,6 +2267,11 @@ export async function isGitHubHost(url: string) {
     return false
   }
 
+  // github.example.com,
+  if (/(^|\.)(github)\./.test(hostname)) {
+    return false
```
Comment (sergiou87) [inline app/src/lib/api.ts]: Shouldn't this be…? 🤔 

```suggestion
    return true
```

**Review by sergiou87 — COMMENTED** [review]
Looks good overall! Just wondering about a specific `return false` and whether or not it should be `return true` 🤔

File: app/src/lib/api.ts (hunk 1 above)
Comment (niik) [reply app/src/lib/api.ts]: Eesh, that would have been real bad. Nice catch!

**Review by sergiou87 — APPROVED** [review]
Works as expected here ✨ :shipit: ✨

**Comment by geomorillo** [comment]
Did not work for me still the popups "untrusted server" showing on Version 3.4.6 (x64)
