### PR TITLE
Error message when Enterprise is too old

### LINKED ISSUE #1628: Improve error message when Enterprise is too old
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

GitHub Desktop version 0.5.5 is having trouble connecting to my GitHub Enterprise instance.  The error it displays after entering my credentials is "Cannot read property 'Symbol(Symbol.iterator)' of undefined"

Server info and login credentials were thoroughly verified.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

GitHub Desktop version: 0.5.5

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Under Options --> Accounts --> Enterprise --> Sign in
2. Entered enterprise server address
3. Clicked Continue
4. Entered username and password
5. Clicked Sign in
6. Read error message
7. Copied error message
8. Submitted error report...

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #1628

### CODE REVIEW

**Comment by joshaber** [comment]
🏷 💃

File: app/src/lib/dispatcher/sign-in-store.ts [hunk 1]
```diff
@@ -23,6 +23,8 @@ function getUnverifiedUserErrorMessage(login: string): string {
   return `Unable to authenticate. The account ${login} is lacking a verified email address. Please sign in to GitHub.com, confirm your email address in the Emails section under Personal settings, and try again.`
 }
 
+const EnterpriseTooOldMessage = `The GitHub Enterprise version is too old. Talk to your server's administrator about upgrading to the latest version of GitHub Enterprise.`
```
Comment (shiftkey) [inline app/src/lib/dispatcher/sign-in-store.ts]: First sentence tweak: `The GitHub Enterprise version does not support GitHub Desktop.`

**Comment by joshaber** [comment]
🐈
