### PR TITLE
Fix error messages for non-repositories

### LINKED ISSUE #1747: Error messages for non-git repos
By dumping a bad file (application, photo, pdf, etc..) into Desktop it triggers two warning messages. Perhaps we could either define the first one or remove it as it isn't user friendly?

Reproduce
- Dump a jpeg into Desktop

screen shot 2017-05-24 at 1 24 50 pm

screen shot 2017-05-24 at 1 24 57 pm

0.5.8, OSX 10.11.5

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #1747 

Validating a potential repository path can be a standalone function. Then we can leave error reporting up to the caller.

screen shot 2017-05-31 at 4 56 43 pm

### CODE REVIEW

File: app/src/lib/dispatcher/app-store.ts [hunk 1]
```diff
@@ -1181,17 +1179,6 @@ export class AppStore {
   }
 
   /** This shouldn't be called directly. See `Dispatcher`. */
-  public async _validatedRepositoryPath(path: string): Promise<string | null> {
```
Comment (shiftkey) [inline app/src/lib/dispatcher/app-store.ts]: LOL why did we need this here in the first place? :fire:

Comment (joshaber) [inline app/src/lib/dispatcher/app-store.ts]: Lol yeah that was kinda my reaction. I assume it's from Earlier Days when we had less of an idea what we were doing.
