### PR TITLE
better ways to compare URLs

### LINKED ISSUE #5913: "open this in GitHub Desktop" link in pull requests is broken
## Description

Clicking the "open this in GitHub Desktop" link in pull requests refuses to open the pull request — instead, it constantly re-prompts me to clone the repository.

image

image

I have tried deleting and re-cloning numerous times, but the issue still persists.

## Version

* GitHub Desktop: 1.4.2

* Operating system: macOS Mojave (10.14)

## Steps to Reproduce

1. Locate a pull request on GitHub _for a repo that you've already cloned into GitHub Desktop._
2. Click the "open this in GitHub Desktop" link at the bottom of the pull request.

### Expected Behavior

GitHub Desktop opens the pull request (i.e. that branch is checked out).

### Actual Behavior

The GitHub Desktop app gains focus and prompts you to clone the repository:

image

### Logs

[2018-10-16.desktop.production.log](https://github.com/desktop/desktop/files/2484548/2018-10-16.desktop.production.log)

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #5913 

I want to verify other places where we use `gitHubRepository.cloneURL` and ensure we're not comparing incorrectly there too.

 - [x] add new API for matching repository URLs
 - [x] fix known regression
 - [x] scan codebase for other candidates, review API

### CODE REVIEW

File: app/src/lib/repository-matching.ts [hunk 1]
```diff
@@ -148,3 +148,29 @@ export function urlMatchesRemote(url: string | null, remote: IRemote): boolean {
...
   )
 }
+
+/**
+ * Match a URL-like string to the Clone URL of a GitHub Repository
+ *
+ * @param url A remote-like URL to verify against the existing information
+ * @param gitHubRepository GitHub API details for a repository
+ */
+export function urlMatchesCloneURL(
```
Comment (shiftkey) [inline app/src/lib/repository-matching.ts]: I settled on this function because it ended up feeling very similar to `urlMatchesRemote` which is also defined here, but compares the `url` string to an `IRemote`.

**Comment by billygriffin** [comment]
@shiftkey I noticed this also happens when using the icon in the PR files changed tab. 

screen shot 2018-10-18 at 3 38 15 pm

Does this solve for that scenario as well?

**Comment by shiftkey** [comment]
@billygriffin this all gets funnelled through the same checks, but I'll verify today that's the case

File: app/test/unit/infer-comparison-branch-test.ts [hunk 2]
```diff
@@ -46,7 +54,7 @@ function createTestGhRepo(
         ? defaultBranch.split('/')[1]
         : defaultBranch
     }`,
-    `${name.indexOf('/') !== -1 ? name.split('/')[1] : name}.git`,
```
Comment (shiftkey) [inline app/test/unit/infer-comparison-branch-test.ts]: @iAmWillShepherd I updated this test because the clone URLs originally set did not contain a host. They're all passing again, but let me know if you're still attached to this behaviour.

**Comment by shiftkey** [comment]
@outofambit done in c1e5868a95ca0bebee8176d49f6c1401c549ab43
