### PR TITLE
Option to disable discard stash popup

### LINKED ISSUE #15376: Impossibile to skip stash discard prompt
### The problem

The prompt for discarding stash changes always shows up, even if all prompt are disabled from settings.

### Release version

3.0.8

### Operating system

macOS 12.6

### Steps to reproduce the behavior

1. Create some changes and then stash them
2. Click the discard button to discard them
3. A prompt shows up

### Log files

_No response_

### Screenshots

Screenshot 2022-09-28 at 11 21 47
Screenshot 2022-09-28 at 11 24 52

### Additional context

https://github.com/desktop/desktop/pull/15243
https://github.com/desktop/desktop/issues/15134

### PR DESCRIPTION
**Pull request by tsvetilian-ty**
Closes #15376

## Description
-  Add an option to the `Prompts` menu that lets the user pick if conformation before discarding stash is required 

### Screenshots
discard-stash

### CODE REVIEW

**Review by sergiou87 — CHANGES_REQUESTED** [review]
Thank you for this @tsvetilian-ty !! However as other prompts, we'd like this one to have the usual "don't show this again" kind of checkbox, in addition to the setting you added.

**Comment by tsvetilian-ty** [comment]
@sergiou87 I did the changes... somehow I forgot about that checkbox 😮

File: app/src/lib/app-state.ts [hunk 1]
```diff
@@ -194,6 +194,9 @@ export interface IAppState {
   /** Whether we should show a confirmation dialog */
   readonly askForConfirmationOnDiscardChangesPermanently: boolean
 
+  /** Should the app propt the user to confirm a discard stash */
```
Comment (sergiou87) [inline app/src/lib/app-state.ts]: Nit:
```suggestion
  /** Should the app prompt the user to confirm a discard stash */
```

**Review by sergiou87 — CHANGES_REQUESTED** [review]
It works great! Only found a small typo (sorry about that nit 😅 ) but just correct that and I'll merge it right away 🚀 

Thanks again for your contribution! 🙇‍♂️

**Review by sergiou87 — APPROVED** [review]
