### PR TITLE
Dynamically updates pull request menu item label 

### LINKED ISSUE #2524: Create Pull Request should become Show Pull Request if one is already opened.
### Description

`Create Pull Request` opens GitHub to create PR even if one already exists.
It would be very handy to change it to `Show Pull Request` after PR was created.
This was the old behavior in GitHub for Mac

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** OS X 10.11.6 (15G1611)

### Steps to Reproduce

1. Push `Create Pull Request`
1. Create actual PR on GitHub

**Expected behavior:** `Create Pull Request` becomes `Show Pull Request`

**Actual behavior:** `Create Pull Request` opens GitHub to create a PR once again.

**Reproduces how often:** Always

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes #2524

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -1024,17 +1025,59 @@ export class AppStore {
...
+      return
+    }
+
+    const repositoryState = this.repositoryState.get(repository.hash)
+
+    if (!repositoryState) {
+      return
+    }
+
+    const pullRequests = await this.pullRequestStore.getPullRequests(
```
Comment (shiftkey) [inline app/src/lib/stores/app-store.ts]: :lipstick: we can move this down and only do the work if there's a valid branch

Comment (joshaber) [reply app/src/lib/stores/app-store.ts]: We shouldn't need to do this at all, really. We have `currentPullRequest` in the app state already.

File: app/src/lib/stores/app-store.ts [hunk 2]
```diff
@@ -1024,17 +1024,46 @@ export class AppStore {
   }
 
   /** Update the menu with the names of the user's preferred apps. */
-  private updatePreferredAppMenuItemLabels() {
+  private async updatePreferredAppMenuItemLabels(repository?: Repository) {
```
Comment (joshaber) [inline app/src/lib/stores/app-store.ts]: I think we should rename this method to something more general than being about "preferred apps".

File: app/src/lib/stores/app-store.ts [hunk 3]
```diff
@@ -1024,17 +1024,46 @@ export class AppStore {
...
+    const prLabel = await this.getPullRequestLabel(repository)
+
     updatePreferredAppMenuItemLabels({
       editor: editorLabel,
+      pullRequestLabel: prLabel,
       shell: `Open in ${this.selectedShell}`,
     })
   }
 
+  private async getPullRequestLabel(repository?: Repository) {
```
[the remark this answers is not in the document]
Comment (iAmWillShepherd) [reply app/src/lib/stores/app-store.ts]: Opted to check if `repository` is `undefined` in the caller function `updatePreferredAppMenuItemLabels`. This function can be called without a repository, so I will keep the signature `repository?: Repository`

**Comment by iAmWillShepherd** [comment]
🥇

File: app/src/lib/stores/app-store.ts [hunk 4]
```diff
@@ -1023,18 +1023,49 @@ export class AppStore {
...
+   */
+  private async updateMenuItemLabels(repository?: Repository) {
     const editorLabel = this.selectedExternalEditor
       ? `Open in ${this.selectedExternalEditor}`
       : undefined
 
+    let prLabel: string | undefined
+
+    if (repository) {
+      prLabel = await this.getPullRequestLabel(repository)
```
Comment (joshaber) [inline app/src/lib/stores/app-store.ts]: This doesn't need to be awaited anymore. I'm surprised TS doesn't complain about that 🤔

File: app/src/lib/stores/app-store.ts [hunk 5]
```diff
@@ -1023,18 +1023,49 @@ export class AppStore {
     return null
   }
 
-  /** Update the menu with the names of the user's preferred apps. */
-  private updatePreferredAppMenuItemLabels() {
+  /**
+   * Update menu labels for editor, shell, and pull requests.
+   */
+  private async updateMenuItemLabels(repository?: Repository) {
```
Comment (joshaber) [inline app/src/lib/stores/app-store.ts]: This shouldn't need to be `async` anymore.

File: app/src/lib/stores/app-store.ts [hunk 6]
```diff
@@ -1023,18 +1023,49 @@ export class AppStore {
...
+    const repositoryState = this.repositoryState.get(repository.hash)
+
+    if (!repositoryState) {
+      return
+    }
+
+    const branchState = repositoryState.branchesState
+
+    if (!branchState.currentPullRequest) {
+      return
```
Comment (joshaber) [inline app/src/lib/stores/app-store.ts]: Should we return "Create Pull Request" here? That way we're consistent in how we determine the label for the pull request menu item.

File: app/src/lib/stores/app-store.ts (hunk 4 above)
Comment (iAmWillShepherd) [reply app/src/lib/stores/app-store.ts]: Yes, that is weird indeed, I typically rely on `tsc` to tell me this kind of stuff... Do you think our linter may be suppressing some of this feedback?

Comment (joshaber) [reply app/src/lib/stores/app-store.ts]: I doubt it. Linting and compilation are separate parts of the build process.

File: app/src/lib/stores/app-store.ts (hunk 6 above)
Comment (iAmWillShepherd) [reply app/src/lib/stores/app-store.ts]: We could, but I followed the pattern of having a default value in the function signature. If I return a string here, it would be doing the same thing that happens now. 

https://github.com/desktop/desktop/blob/2b881e67083d08989d018671238eec23afb1ef1f/app/src/main-process/menu/build-default-menu.ts#L16-L24

I personally prefer returning a string vs undefined.

Comment (joshaber) [reply app/src/lib/stores/app-store.ts]: >I personally prefer returning a string vs undefined.

Agree, let's do it 👍

**Comment by iAmWillShepherd** [comment]
> When the label is "Show Pull Request", clicking it should open directly to the PR instead of going to github.com/repo/name/pull/new/branch_name.

Got it, currently opening the url `github.com/[repo]/[name]/pull/[number]`

File: app/src/main-process/menu/build-default-menu.ts [hunk 7]
```diff
@@ -294,10 +298,13 @@ export function buildDefaultMenu(
         click: emit('compare-branch'),
       },
       {
-        label: __DARWIN__ ? 'Create Pull Request' : 'Create &pull request',
+        label: pullRequestLabel,
         id: 'create-pull-request',
         accelerator: 'CmdOrCtrl+R',
-        click: emit('create-pull-request'),
+        click:
+          pullRequestLabel === defaultPullRequestLabel
```
Comment (joshaber) [inline app/src/main-process/menu/build-default-menu.ts]: Using using-facing strings as the basis for logic makes me nervous. How about we emit a single command (e.g., `show-or-create-pull-request`) and make the decision in the app store based on whether we have a current PR.

Comment (iAmWillShepherd) [reply app/src/main-process/menu/build-default-menu.ts]: Decided to move the check into `app.tsx`. I wanted to leave the two functions: `_createPullRequest` and `_showPullRequest` in `app-store.ts` alone since they do two very different things.

**Comment by iAmWillShepherd** [comment]
🔢

**Comment by joshaber** [comment]
This looks good ✨ Just needs a merge in from `master` 👍

**Comment by iAmWillShepherd** [comment]
💬
