### PR TITLE
Fix "Reveal in Finder"

### LINKED ISSUE #2909: Reveal in Finder opens in Default Program
### Description

If you try to "Reveal in Finder" a file, you'll find GitHub Desktop actually opening the file in the default program. "Open with Default Program" will also open the file in the default program.

### Version

**GitHub Desktop version:** 1.0.2

**OS version:** macOS 10.12.6

### Steps to Reproduce

1. In a repo, have at least one changed file
1. Right click on the file, select Reveal in Finder

**Expected behavior:** Finder will be opened, at the place where the file is located

**Actual behavior:** Opens the file in the default program

**Reproduces how often:** Always

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #2909

### CODE REVIEW

File: app/src/main-process/main.ts [hunk 1]
```diff
@@ -313,7 +313,7 @@ app.on('ready', () => {
           return
         }
 
-        if (stats.isDirectory) {
+        if (stats.isDirectory()) {
```
Comment (shiftkey) [inline app/src/main-process/main.ts]: 🤦‍♂️  probably why I should have `=== true` here
