### PR TITLE
Dynamic constraints for resizable components

### LINKED ISSUE #2745: Column widths are limited — would love to remove those widths
### Description

(forgive me if this is an issue already, I looked and couldn't find it)

The various columns in the application are constrained to certain max widths — which makes using the app on larger screens frustrating. Particularly when being able to expand a column to see all the data would be very helpful. The application should not place a width limit on columns so that the user of the application can determine the column widths desired at any time.

github-columns

### Version

**GitHub Desktop version:** 0.8.2

**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

1. Try to resize a column in the app to any width wider than the limit

**Expected behavior:** Column should resize to any size user would like

**Actual behavior:** Columns have a max-width limit

### PR DESCRIPTION
**Pull request by niik**
Closes #2745 

## Description

Since the very first versions of GitHub Desktop we've enforced a max width for our resizable components (the changes/history list, and the file list in the stashed changes view and in the selected commit view).

These constraints were put in place to ensure that you couldn't resize these components to a point where you could no longer use parts of the UI because they were now being rendered outside of the window bounds. 

The constraints we set where based on running the app in the minimum window size such that it wouldn't be possible to maximize the app, resize the panes, and then restore the window size and find yourself in a situation where parts of the UI were being rendered outside of the window bounds.

This was always intended to be a temporary solution until we could get around to implementing a dynamic max-width that got recalculated based on the layout of the app and the window size (see https://github.com/desktop/desktop/issues/1588#issuecomment-329405096). There's been several attempts by community contributors to address this issue that we've unfortunately had to reject since they focused on removing/increasing the constraints, not making the constraints themselves adapt to the window dimensions.

In this PR we're making the resizable panes remember their "desired" value and dynamically calculate their max width depending on the width of other resizable panes that affect the available space and the windows dimensions while making sure the the UI is usable.

By keeping track of the desired width we can support resizing the application in a consistent way where maximizing the app, resizing the panes then restoring its size will cause the panes to shrink to fit their constraints but (unless modified again) they will inflate to their desired size again once the app is maximized again.

### Screenshots

image
image
image

## Release notes

Notes:

image

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -6826,3 +6886,11 @@ function isLocalChangesOverwrittenError(error: Error): boolean {
     error.result.gitError === DugiteError.LocalChangesOverwritten
   )
 }
+
+function constrain(
+  value: IConstrainedValue | number,
+  min = -Infinity,
```
Comment (tidy-dev) [inline app/src/lib/stores/app-store.ts:6892]: TIL: You can specify infinity as a number 🤯

**Review by tidy-dev — APPROVED** [review]
✨  Looks great and tested it out and feels oddly freeing 😸

File: app/src/lib/stores/app-store.ts (hunk 1 above)
Comment (niik) [reply app/src/lib/stores/app-store.ts:6892]: It's the negative infinity that cracks me up! :smile:
