### PR TITLE
Gotta start somewhere with a11y

### LINKED ISSUE #1662: "Changed files" label is off-center
### Description

screen shot 2017-05-20 at 11 53 33

Looks like the "changed files" label is centered _between_ the checkbox and the divider, when I would expect the label to be centered between the divider and the edge of the window.

### Version

**GitHub Desktop version:** 0.5.5
**OS version:** macOS 10.12.4

### Steps to Reproduce

1. Install for the first time, and set up
1. Add an existing repository to the app

### PR DESCRIPTION
**Pull request by niik**
This is a starting point for providing users that are consuming the app through screen readers or other assistive technologies a little relief.

Note that this is not intended to be the end all of a11y, far from it. It's only a starting point and playground for figuring out what works and not with regards to a11y, specifically focusing on screen readers for now.

I'm testing this using [NVDA](https://www.nvaccess.org) but we should probably expand testing to include other readers such as VoiceOver. The Windows narrator does not seem to be able to peer into electron at the moment though I might be doing something wrong there.

cc #227 
Fixes #1662

### CODE REVIEW

**Comment by niik** [comment]
I'm gonna call this ready for review. This is by no means the end-all of accessibility but it's miles ahead of what we've got and we'll keep iterating on it in separate PRs

File: app/src/ui/list.tsx [hunk 1]
```diff
@@ -560,7 +594,9 @@ export class List extends React.Component<IListProps, IListState> {
 
     return (
       <Grid
+        aria-label={''}
```
Comment (joshaber) [inline app/src/ui/list.tsx]: Are this and `role` intended to be empty strings? If so, we shouldn't need the wrapping curlies.

File: app/src/ui/dialog/dialog.tsx [hunk 2]
```diff
@@ -106,6 +107,13 @@ interface IDialogState {
    * grace period or not.
    */
   readonly isAppearing: boolean
+
+  /**
+   * An optional id for the h1 element that contains the title of this
+   * dialog. Used to aid in accessibility. Undefined if the dialog does
+   * not have a title or the component has not yet been mounted.
+   */
+  readonly titleId?: string
```
Comment (joshaber) [inline app/src/ui/dialog/dialog.tsx]: It's not immediately obvious to be how this aids in accessibility?

File: app/src/ui/list.tsx (hunk 1 above)
Comment (niik) [inline app/src/ui/list.tsx]: Yes, they are. Unfortunately we can't set them to `undefined` since the Grid has `defaultProps` that then take precedence. We can't set to null either because the type definitions don't allow it so this was the best I could come up with. Thinking about this some more though I think perhaps the best solution would be to use `null!` since we really don't want the attributes to render. I'll give that a shot

File: app/src/ui/dialog/dialog.tsx (hunk 2 above)
Comment (niik) [inline app/src/ui/dialog/dialog.tsx]: Addressed this in the documentation but the aria system only supports referring to other elements by id.

**Comment by niik** [comment]
🎸

**Comment by Oire** [comment]
Hi guys,  
First of all, thanks for bringing your attention to our needs.  
I'm the (annoying) guy who created #353 :). I acknowledge you can't (and shouldn't, I believe) test with all possible screen readers, namely because some of them are payed.  
I would like to participate in your work and do my best to help you. I could test accessibility with JAWS for Windows as I've been using it for nearly 20 years now. I've been working in accessibility for many years, so I think I might be helpful here :).  
Thanks!

**Comment by shiftkey** [comment]
@Oire you are more than welcome to submit issue or PRs on the things you identify!
