### PR TITLE
Only sanitize forbidden fs characters when creating repo

### LINKED ISSUE #20973: Creating a repo from a folder with spaces in its name doesn't work anymore.
### The problem

I used to create repos from folders with space in their names without any issues, but when I tried it today, I got this:

Image

And a new empty folder with the changed name.

I get that repo names can't have spaces in them, but that folder is used by my game engine, I can't just willy nilly change its name. Is this a bug, or do I have to change the way I've been doing things from now on, and go back a decades worth of repos, and find everything that's broken by this change?

### Release version

3.5.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1- Create a folder with spaces in the name
2- Try to make a repo out of it.

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niik**
Closes #20973

## Description

See this discussion in #20973. This PR removes the repository name sanitization entirely on macOS (+Linux) and makes it much more forgiving on Windows, only sanitizing characters that are forbidden on Windows file systems.

## Release notes

Notes:

### CODE REVIEW

**Review by tidy-dev — APPROVED** [review]

File: app/src/ui/add-repository/create-repository.tsx [hunk 1]
```diff
@@ -10,7 +10,6 @@ import {
   getRepositoryType,
   RepositoryType,
 } from '../../lib/git'
-import { sanitizedRepositoryName } from './sanitized-repository-name'
```
Comment (SEUB66) [inline app/src/ui/add-repository/create-repository.tsx:13]: Omg ok

**Comment by shrawanshrawanlekhala-max** [comment]
Hi
