### PR TITLE
Fix copying text within a line

### LINKED ISSUE #2492: Copying selected text inside diff doesn't copy all that is visibly selected
I'm in 0.8.0 on macOS. When I select some text in the diff and hit Cmd-C to copy it, the first letter is omitted from what is copied:

select-text-doesnt-copy-all-github-desktop-loop

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #2492

I don't know why this didn't occur to me when I was writing this originally 🙈

We should only trim diff line markers when the selection includes the 0th character.

### CODE REVIEW

File: app/src/ui/diff/index.tsx [hunk 1]
```diff
@@ -650,15 +650,33 @@ export class Diff extends React.Component<IDiffProps, {}> {
...
-      .split('\n')
-      .map(l => l.substr(1))
-      .join('\n')
-    clipboard.writeText(textWithoutMarkers)
+    // Remove the diff line markers from the copied text. The beginning of the
+    // selection might start within a line, in which case we don't have to trim
+    // the diff type marker. But for selections that span multiple lines, we'll
+    // trim it.
+    const doc = editor.getDoc()
+    const lines: ReadonlyArray<string> = (doc as any).getSelections()
```
Comment (joshaber) [inline app/src/ui/diff/index.tsx]: PR opened adding this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19128

Comment (shiftkey) [inline app/src/ui/diff/index.tsx]: This has been merged. Will circle back after this PR to get it in.
