### PR TITLE
Fix commits missing in History tab

### LINKED ISSUE #3704: a commit disappears from change history of a branch
### Description
I have a repositoty (https://github.com/vincent3569/zenphoto-perso) that is a fork from another repo (https://github.com/zenphoto/zenphoto)

In my repo, I have 2 branchs (master and perso).
in perso branch, I added a personnal dev
in master branch, I updated some translations and I made a pull request to the initial repo.

after that
I merge master branch into perso branch (so I have all commits of my new feature + my translations update)

after the pull request has been merged into upstream/master, 
I want to keep my fork sync with upstream (although it seems to be useless since my repo is up to date because I am at the initiative of the changes).

on my_repo/master I made a "merge into current branch" from upstream/master.
and on my_repo/perso I made a "merge into current branch" from master.

**after that, my personnal commit on my_repo/perso desapears from changes history of this branch.
I still see it on github.**

### Version

**GitHub Desktop version:** [github desktop 1.0.12-beta0]

**OS version:** [Microsoft Windows 10.0.16299.125]

### Steps to Reproduce
See above

### Logs
[2017-07-31.desktop.production.log](https://github.com/desktop/desktop/files/1594853/2017-07-31.desktop.production.log)

#### Additional Information
screenshots of github desktop

zenphoto -- master
zenphoto-perso -- master
zenphoto-perso -- perso
zenphoto-perso -- perso on github
zenphoto-perso -- master on github

### LINKED ISSUE #12506: Commit missing in history view
### Describe the bug

I'm looking at a specific feature branch on my github repo in the browser and on the Github Desktop app. There is a specific commit that exists and shows up in the browser, but I cannot find it in the "History" tab of the Desktop app (yes I have fetched origin, and the code edits from that commit are showing in my code editor). I noticed that a recent update allowed commits to be reordered, so I wonder if something went wonky there? Commits have always shown in reverse order by date, and there is a distinct gap on the date when this commit took place.

### Version & OS

Version 2.9.0, macOS 11.3.1.

### Steps to reproduce the behavior
Not sure it can be reproduced without access to this repo, which is private. This is the first commit I have seen affected. But I'll describe my steps anyway in case it helps:
1) Toggle to feature branch in Desktop app.
2) Fetch origin.
3) Look for commit where particular change was made, scrolling in the History tab down to the date of the change. Scratch head (commit missing).
4) Navigate browser to list of commits for this feature branch in github. Confirm that commit exists there.

### Expected behavior

I expect to see the commit I'm looking for at the date that it was committed.

### Actual behavior

Commit is missing from History tab in Desktop app.

### Screenshots

Without showing too much, since this is a private repo, here's a snippet of the commit list from the browser (with the commit from January 20):
Screen Shot 2021-06-24 at 4 07 47 PM

And a snippet of the History tab from the Desktop app (without the commit):
Screen Shot 2021-06-24 at 4 08 11 PM

### Logs

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #12506
Closes #3704

## Description

I think https://github.com/desktop/desktop/issues/12506#issuecomment-872409814 gives good context about the reason behind this bug. Luckily, `git` has a `--skip` parameter, so with the changes in this PR, when we need to load a new page of commits, we'll run `git log` from `HEAD` and skip the X first commits.

In order to test this, you can create a repository with two branches alternating commits between two branches and finally merging them, using this script:

```bash
mkdir test-repo
cd test-repo
git init

git checkout -b main
echo "initial file" > 0
git add 0
git commit -m "initial commit"

git checkout -b sub

for F in {1..300}; do
  echo "hello $F" > $F

  # if F is even, then commit from main
  if [ $((F%2)) -eq 0 ]; then
    git checkout main
    git add $F
    git commit -m "commit $F"
  else
    # if F is odd, then commit from sub
    git checkout sub
    git add $F
    git commit -m "commit $F"
  fi
done

git checkout main
git merge sub
```

### Screenshots

Without the fix, after the second page is loaded, you only see commits from one of the branches (either odd or even numbers in the test repo):

https://user-images.githubusercontent.com/1083228/124259683-14922500-db2f-11eb-8c6f-fbe3f09b473a.mov

With the fix, you always see both odd and even numbers:

https://user-images.githubusercontent.com/1083228/124259807-39869800-db2f-11eb-8d0f-db8eac823eef.mov

## Release notes

Notes: [Fixed] History tab shows all commits as the user scrolls down

### CODE REVIEW

File: app/src/lib/stores/git-store.ts [hunk 1]
```diff
@@ -201,52 +201,21 @@ export class GitStore extends BaseStore {
...
-    if (!commits) {
-      return
-    }
-
-    this._history = this._history.concat(commits.map(c => c.sha))
-    this.storeCommits(commits)
-    this.requestsInFight.delete(requestKey)
-    this.emitUpdate()
-  }
-
```
Comment (sergiou87) [inline app/src/lib/stores/git-store.ts:234]: This wasn't used at all anymore 😅

**Review by tidy-dev — APPROVED** [review]
✨  Tested it out. Works great! Awesome debugging to figure that one out. The never ending joy of merge commits. 😸 

gitMerge

**Review by billygriffin — APPROVED** [review]
Amazing job finding the culprit @sergiou87! ✨
