### PR TITLE
Use open dialog when cloning on windows

### LINKED ISSUE #12812: Clone Selecting Directory Requires a file instead of a folder
### Describe the bug
The bug is inside the clone repository window. When I want to select a directory to clone the repo, It's actually a file dialog and it requires a file instead of a folder

### Version & OS

Version 2.9.0 (x64) on Windows 10

### Steps to reproduce the behavior

1. Click on File
2. Choose Clone Repository
3. Click on "Choose..." button

### Expected behavior

It should be a directory dialog so I can choose a folder

### Actual behavior

It's a file dialog so I'm not able to select a folder

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes #12812

## Description
Reverted clone dialog to from save to open dialog on windows.

### Screenshots
https://user-images.githubusercontent.com/75402236/159717300-078251d4-0e98-4b44-8e96-c580dc29fd11.mov

## Release notes
Notes: [Fixed] Clone dialog "choose" button uses an open dialog for directory selection on mac.

### CODE REVIEW

**Review by billygriffin — COMMENTED** [review]
Awesome! Just a question - do we use the feature flag pattern for differentiating between Windows and macOS anywhere else? I'm wondering if this will be clear for others who come upon this in the future.

**Comment by tidy-dev** [comment]
> Awesome! Just a question - do we use the feature flag pattern for differentiating between Windows and macOS anywhere else? I'm wondering if this will be clear for others who come upon this in the future.

Not really - we do have one other feature flag with arm64 updating that is flagged to macOs.  This save vs open dialog is more of unique case because we are providing different feature per OS, where usually macOS vs windows is either wording or because some underlying process (like spawn) doesn't work the same.

That said, I moved it into the code so that it would be more visible to a future devs that we are doing something different per OS and added some documentation as to why since it is a unique case.

Other notes: I took out the feature flag since it isn't really providing anything at this point and we could easily add back since we are still flagging by os if we so choose.

File: app/src/lib/feature-flag.ts [hunk 1]
```diff
@@ -80,7 +80,7 @@ export function enableUpdateFromEmulatedX64ToARM64(): boolean {
 
 /** Should we allow using the save dialog when choosing where to clone a repo */
 export function enableSaveDialogOnCloneRepository(): boolean {
```
Comment (j-f1) [inline app/src/lib/feature-flag.ts]: Is this function used anymore? If not, should it be removed?

**Review by j-f1 — DISMISSED** [review]
This makes a lot of sense — especially after seeing the new dialog on Windows, it much better matches the current macOS experience!

File: app/src/lib/feature-flag.ts (hunk 1 above)
Comment (tidy-dev) [reply app/src/lib/feature-flag.ts]: Nope! Good catch. I thought I did remove it, but didn't save that file. 😳

**Comment by Nonso15** [comment]
Legit company to invest and trade your Bitcoin and earn your profits daily safely withdrawal instantly.
🎲🎲🎲🎲🎲🎲🎲🎲🎲
https://Jomo-trade.com
https://Jomo-trade.com

Legit✅✅
No withdrawal fee✅✅
Instant withdraw ✅✅
https://Jomo-trade.com
https://Jomo-trade.com

**Review by sergiou87 — APPROVED** [review]
🐸 🕴️ ❗
