### PR TITLE
Render ahead/behind tooltip using custom Tooltip

### LINKED ISSUE #15583: Dual tooltip on Repository status icon
### The problem

When there are changes that can be pushed in a repository, the repository shows an up arrow icon. That icon has a title and the whole row has a custom tooltip resulting in a double tooltip. The icon title needs changed to a custom tool tip and ensure that only one tooltip shows at a time.

### Release version

3.1.3-beta2

### Operating system

MacOS

### Steps to reproduce the behavior

1. Open a repository
2. Make a couple commits
3. Open Repository List
4. Hover over "Up Arrow" icon on repository name.

### Log files

N/A

### Screenshots

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niik**
Closes #15583

## Description

Render the ahead/behind tooltip as a Tooltip so that it accurately closes the previous ancestor tooltip.

### Screenshots

image

## Release notes

Notes: [Fixed] Stick to one tooltip at a time in the repository list

### CODE REVIEW

**Review by sergiou87 — APPROVED** [review]
Works perfectly 🙌

File: app/src/ui/repositories-list/repository-list-item.tsx [hunk 1]
```diff
@@ -193,10 +193,14 @@ const renderAheadBehindIndicator = (aheadBehind: IAheadBehind) => {
...
-    <div className="ahead-behind" title={aheadBehindTooltip}>
+    <TooltippedContent
+      className="ahead-behind"
+      tagName="div"
+      tooltip={aheadBehindTooltip}
+    >
       {ahead > 0 && <Octicon symbol={OcticonSymbol.arrowUp} />}
       {behind > 0 && <Octicon symbol={OcticonSymbol.arrowDown} />}
-    </div>
+    </TooltippedContent>
```
Comment (Nathaniel97299) [inline app/src/ui/repositories-list/repository-list-item.tsx:203]: Arrest warrants deactivater

Comment (srwrr) [reply app/src/ui/repositories-list/repository-list-item.tsx:203]: سلام ممنون دوست عزیزم تشکر ازهید یه شما

**Comment by srwrr** [comment]
ممنون دوست عزیزم [6037701726651810](lRR )

**Comment by srwrr** [comment]
IRR

**Review by srwrr — COMMENTED** [review]
>URL
