### PR TITLE
WSL CLI Fix [#4998]

### LINKED ISSUE #4998: Fail to start from WSL
## Description

In a [WSL(Windows Subsystem for Linux)](https://docs.microsoft.com/en-us/windows/wsl/about) exclusively available on Windows 10, running `github` CLI command fail to start Github Desktop. 

## Version

* GitHub Desktop: 
Version 1.2.3

* Operating system: 
Microsoft Windows [Version 10.0.17134.112]
WSL enabled with Ubuntu 18.04

## Steps to Reproduce

1. Install WSL on a Windows 10 system by following [Microsoft's Guide](https://docs.microsoft.com/en-us/windows/wsl/install-win10), Ubuntu 18.04 is installed for example.
2. Install Github Desktop.
2. Start `bash`, `wsl` from Start Menu, or start from your installed Linux distro app `ubuntu`
3. Run `github` and you can observe the error message

### Expected Behavior

By running `github` in WSL should the application start as expected as it does in cmd, PowerShell and Git bash on Windows 10.

### Actual Behavior

The application won't start and a script error is printed.
```
sh: 0: Can't open /mnt/d/bob/AppData/Local/GitHubDesktop/bin/..\app-1.2.3\resources\app\static\github.sh
```

## Additional Information

As @shiftkey suggested, [this script](https://github.com/desktop/desktop/blob/master/app/static/win32/github.sh) which do start the application properly in Git Bash, cmd and PowerShell on Windows 10, should be modified to cover WSL.

If it is caused by unexpected behavior from WSL, we might need to check [WSL Github](https://github.com/Microsoft/WSL).

Since WSL keeps adding [more Linux distro](https://aka.ms/wslstore), they should be considered as well.

And regarding to #4641, WSL will be added to supported shell options, so this issue should be fixed by then so Github Desktop can start and be started from WSL.

### PR DESCRIPTION
**Pull request by shawnfunke**
Closes #4998

## Description

This PR fixes issue #4998 

## Release notes

Notes:
  - Fixed not being able to run the `github` command from the WSL CLI

### CODE REVIEW

**Comment by shawnfunke** [comment]
@shiftkey Any news on this?

**Comment by shiftkey** [comment]
@shawnfunke I'm no longer working on GitHub Desktop. Providing more context about what the fix is and how to verify the fix locally could help with getting someone to work on it.

**Comment by shawnfunke** [comment]
I've looked at the worked you've started and pretty much just finished it. I've tested this with Git Bash, Debian WSL, CMD and PowerShell on my local machine.

**Comment by dennisameling** [comment]
@shawnfunke would you mind rebasing this PR on the upstream `development` branch? There's been some pretty significant dependency updates (e.g. Electron v5 to v7 upgrade). Would be happy to test this PR on WSL then :)

**Comment by shawnfunke** [comment]
@dennisameling sure, i'll rebase and test this :)

**Comment by shawnfunke** [comment]
@dennisameling I've rebased my by branch but after trying for hours I'm not able to test it. I'm always getting the error below when trying to build the project, are you able to test it? It could be because I'm not running the latest stable Windows 10 release.

```
[Error: ENOENT: no such file or directory, rename 'C:\shfk\desktop\dist\GitHubDesktop-dev-win32-x64\electron.exe' -> 'C:\shfk\desktop\dist\GitHubDesktop-dev-win32-x64\GitHubDesktop-dev.exe'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'C:\\shfk\\desktop\\dist\\GitHubDesktop-dev-win32-x64\\electron.exe',
  dest: 'C:\\shfk\\desktop\\dist\\GitHubDesktop-dev-win32-x64\\GitHubDesktop-dev.exe'
}
```

**Comment by dennisameling** [comment]
I can't seem to build desktop with `npm run build:prod` (might be a temporary problem with the `development` branch):

```
[WEBPACK] Finished building highlighter.js within 53.054 seconds
i ｢atl｣: Checking started in a separate process...
× ｢atl｣: Checking finished with 1 errors
[WEBPACK] Build failed after 70.296 seconds
[WEBPACK] Errors building ask-pass.js
[at-loader] ./app/src/lib/git/core.ts:372:22
    TS2339: Property 'TagAlreadyExists' does not exist on type 'typeof GitError'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:prod: `yarn compile:prod && cross-env NODE_ENV=production ts-node -P script/tsconfig.json script/build.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\denni\AppData\Roaming\npm-cache\_logs\2020-04-13T20_13_59_734Z-debug.log
```

Maybe it's related to the error you're seeing? Maybe better to rebase based on the latest release version (https://github.com/desktop/desktop/releases/tag/release-2.4.0) which is from 20 days ago. This version was updated to Electron 7 so the major dependency upgrade is done in it. You should be able to rebase based on a certain tag (release-2.4.0): https://stackoverflow.com/a/12469904/4337765

**Comment by shawnfunke** [comment]
@dennisameling not sure, it's weird that the CI builds were successful. I will try to rebase it with the tag tomorrow and try that instead.

**Comment by shiftkey** [comment]
@dennisameling ensure you have done a `yarn` to sync your installed dependencies because that error is related to a new version of `dugite` that was merged recently - https://github.com/desktop/desktop/pull/9461

**Comment by dennisameling** [comment]
Go it to work now, had to completely remove `node_modules` and `app/node_modules` prior to running `yarn` to ensure a clean state. Thanks for the heads-up @shiftkey, will go ahead and test now

File: app/static/win32/github.sh [hunk 1]
```diff
@@ -2,8 +2,27 @@
...
+		CLI=$(wslpath -m "$CONTENTS/resources/app/cli.js")
+	else
+		# If running under older WSL, don't pass cli.js to Electron as
+		# environment vars cannot be transferred from WSL to Windows
+		# See: https://github.com/Microsoft/BashOnWindows/issues/1363
+		#      https://github.com/Microsoft/BashOnWindows/issues/1494
+		"$ELECTRON" "$@"
+		exit $?
+	fi
+elif [ "$(expr substr $(uname -s) 1 9)" == "CYGWIN_NT" ]; then
```
Comment (dennisameling) [inline app/static/win32/github.sh:20]: Could you please change `==` to `=` as it causes the following message in WSL2 (Ubuntu):

```
dennis@DESKTOP-HIGHLVU:/mnt/c/Users/denni$ github
/mnt/c/Users/denni/AppData/Local/GitHubDesktop/bin/../app-2.4.1-beta1/resources/app/static/github.sh: 20: [: Linux: unexpected operator
```

When I changed it to `=` [as per these instructions](https://stackoverflow.com/a/3411105/4337765), I didn't get the warning anymore.

Comment (shawnfunke) [reply app/static/win32/github.sh]: done! :)

**Comment by shawnfunke** [comment]
@dennisameling Hey, is this supposed to be already merged or are we waiting for a specific release to drop?

**Comment by dennisameling** [comment]
@shawnfunke I'm not a member of the GitHub Desktop repository 😊 The only thing I can do is to help test PRs so that it's easier for the core team to verify and merge them. Let's hope they will merge this fix soon!

**Comment by shawnfunke** [comment]
@dennisameling Ah, okay thanks for the insight :)

File: app/src/main-process/squirrel-updater.ts [hunk 2]
```diff
@@ -92,12 +98,20 @@ function writeBatchScriptCLITrampoline(binPath: string): Promise<void> {
...
-  const versionedPath = resolveVersionedPath(
+  const rawVersionedPath = resolveVersionedPath(
     binPath,
     'resources/app/static/github.sh'
   )
 
+  const versionedPath = __WIN32__
+    ? rawVersionedPath.replace(/\\/g, '/')
+    : rawVersionedPath
+
```
Comment (niik) [inline app/src/main-process/squirrel-updater.ts:114]: `writeShellScriptCLITrampoline` is only called when on Windows. macOS has a [separate method](https://github.com/desktop/desktop/blob/2a9d7d6d45c4fe1876008803f9e5c6d51d24eb14/app/src/ui/lib/install-cli.ts) for installing its CLI trampoline.

With that in mind I think we can simplify this

```suggestion
  const versionedPath = resolveVersionedPath(
    binPath,
    'resources/app/static/github.sh'
  ).replace(/\\/g, '/')
```

File: app/src/main-process/squirrel-updater.ts [hunk 3]
```diff
@@ -92,12 +98,20 @@ function writeBatchScriptCLITrampoline(binPath: string): Promise<void> {
   return writeFile(trampolinePath, trampoline)
 }
 
+/** We have to make sure the versioned path in the script has the correct format
+ * even if its Windows otherwise there can be edge cases with WSL see issue:
+ * https://github.com/desktop/desktop/issues/4998
+ */
```
Comment (niik) [inline app/src/main-process/squirrel-updater.ts:104]: Love this comment but I think it would make more sense to have it be a regular code comment and to put it right next to the `.replace` call. We can skip the bit about "even if its Windows" (see below) and it'd be great if we could clarify what the "correct format" is. Perhaps something like

```
// The path we get from `resolveVersionedPath` is a Win32 relative
// path (something like `..\app-2.5.0\resources\app\static\github.sh`).
// We need to make sure it's a POSIX path in order for WSL to be able
// to resolve it. See https://github.com/desktop/desktop/issues/4998

File: app/src/main-process/squirrel-updater.ts [hunk 4]
```diff
@@ -66,7 +66,13 @@ function getBinPath(): string {
...
 function resolveVersionedPath(binPath: string, relativePath: string): string {
   const appFolder = Path.resolve(process.execPath, '..')
-  return Path.relative(binPath, Path.join(appFolder, relativePath))
+
+  const computedPath = Path.relative(
+    binPath,
+    Path.join(appFolder, relativePath)
+  )
+
+  return Path.normalize(computedPath)
```
Comment (niik) [inline app/src/main-process/squirrel-updater.ts:75]: It surprises me that we need to do a normalization step here, I thought `Path.relative` already took care of that, i.e:

```
> path.relative('c:\\one-win32-path', 'c:\\one-posix-path/foo/bar')
'..\\one-posix-path\\foo\\bar'
```

Unless you're sure this is necessary could we revert this change?

```suggestion
  return Path.relative(binPath, Path.join(appFolder, relativePath))
```

**Comment by shawnfunke** [comment]
@niik , yes you understood it correctly. Thanks for your review, I agree with your suggestions and I will go ahead and add them to this PR!

**Comment by say25** [comment]
Sorry for coming to this thread late, does this work for both WSL and WSL 2?
