### PR TITLE
set the publish branch message based on GitHub API info

### LINKED ISSUE #1498: "Publish branch" button mentions GitHub for non-GitHub repos
### Description

publish-branch

For a non-GitHub repo, that button doesn't actually publish to GitHub. (It doesn't seem publish anywhere because it's not picking up authentication… but that's a different bug.)

### Version

**GitHub Desktop version:** 0.5.3
**OS version:** 10.12.4

### Steps to Reproduce

1. Open a repo that has a non-GitHub remote

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #1498

For a GitHub repository:

For a remote we don't recognize:

### CODE REVIEW

File: app/src/ui/toolbar/push-pull-button.tsx [hunk 1]
```diff
@@ -162,7 +162,10 @@ export class PushPullButton extends React.Component<IPushPullButtonProps, {}> {
       return 'Publish this repository to GitHub'
     }
     if (!this.props.aheadBehind) {
-      return 'Publish this branch to GitHub'
+      const isGitHub = this.props.repository.gitHubRepository !== null
```
Comment (joshaber) [inline app/src/ui/toolbar/push-pull-button.tsx]: I don't think we should generally compare to `null` strictly since it won't also catch `undefined`. Instead we could do `!!this.props.repository.gitHubRepository` or `this.props.repository.gitHubRepository != null`.

**Comment by shiftkey** [comment]
🍎
