### PR TITLE
Repo association investigation and fixes

### LINKED ISSUE #1727: Unable to push commits to the website after this week's updates
### Description

After updating to 0.5.6 and 0.5.7 I'm no longer able to push my branch's commits. This works from the command line as well as the native client but no longer works in this client. I'm unsure if this was an issue with 0.5.5 but last week I was able to push my commits just fine.

### Version
**GitHub Desktop version:** 0.5.6, 0.5.7
**OS version:** Win10 Creators Update (10.0.15063)

### Steps to Reproduce

I'm not sure if this is reproducible elsewhere, but it keeps happening on the repo I'm working in even after updating from 0.5.6 to 0.5.7.

I'm pressing the button to push my changes to origin, as well as using the push menu. Both result in similar errors to this.

image

**Expected behaviour:** My new commits should be pushed to GitHub

**Actual behaviour:** I get an error message and nothing is pushed

**Reproduces how often:** Every time I try to push for this repo

### Logs

There are no log files in `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

#### Additional Information

It looks like the issue is being triggered by `-c credential.helper=` because when I include that on the command line I'm prompted for my username & password. According to the application I'm logged in.

### PR DESCRIPTION
**Pull request by niik**
~~This is an in-progress PR trying to get to the bottom of the authentication issues described in #1727~~

This addresses the problem of the development app overwriting the production app's OAuth token and vice versa which was the underlying cause of #1727. It also tweaks our logic for matching repositories, addressing issues I suspected to be the cause while investigating. While they turned out to not be the root cause in the end I still believe that they are valid changes that should be discussed and pulled in.

Fixes #1727

### CODE REVIEW

File: app/src/lib/dispatcher/app-store.ts [hunk 1]
```diff
@@ -1130,9 +1131,7 @@ export class AppStore {
   }
 
   private async guessGitHubRepository(repository: Repository): Promise<GitHubRepository | null> {
-    const gitStore = this.getGitStore(repository)
-    const remote = gitStore.remote
-
+    const remote = await getDefaultRemote(repository)
```
Comment (niik) [inline app/src/lib/dispatcher/app-store.ts]: This change was made because in testing I found that there was sometimes a race condition where the `gitStore` hadn't finished loading yet and therefore the remote was null. We could fix this by waiting on the store to become ready but unless I'm mistaken we should, if for no other reason than consistency, try to guess the remote based on the default remote and not based on whichever branch is open at the time. If anyone has a reason why we shouldn't I'm all ears

File: app/src/lib/remote-parsing.ts [hunk 2]
```diff
@@ -19,10 +19,11 @@ interface IGitRemoteURL {
 export function parseRemote(url: string): IGitRemoteURL | null {
   // Examples:
   // https://github.com/octocat/Hello-World.git
+  // https://github.com/octocat/Hello-World.git/
   // git@github.com:octocat/Hello-World.git
   // git:github.com/octocat/Hello-World.git
   const regexes = [
-    new RegExp('^https?://(.+)/(.+)/(.+?)(?:\.git)?$'),
+    new RegExp('^https?://(.+)/(.+)/(.+?)(?:\.git/?)?$'),
```
Comment (niik) [inline app/src/lib/remote-parsing.ts]: This was added because I saw a log files where someone had their remote url set to the full url with a trailing slash. I suspect that URL was either added manually or by another tool but since GitHub happily supports it I figured we should as well.

File: app/src/lib/repository-matching.ts [hunk 3]
```diff
@@ -26,7 +26,8 @@ function matchRemoteWithAccount(account: Account, remote: string): GitHubReposit
 
   const owner = parsedRemote.owner
   const name = parsedRemote.name
-  if (parsedRemote.hostname === host && owner && name) {
+
+  if (host && parsedRemote.hostname.toLowerCase() === host.toLowerCase() && owner && name) {
```
Comment (niik) [inline app/src/lib/repository-matching.ts]: This was a wild guess that I had early on when investigating that never turned out to be meaningful but I still think that comparing host names should be done without taking case into account

File: app/src/lib/dispatcher/app-store.ts (hunk 1 above)
Comment (joshaber) [inline app/src/lib/dispatcher/app-store.ts]: >but unless I'm mistaken we should, if for no other reason than consistency, try to guess the remote based on the default remote and not based on whichever branch is open at the time

Hmm, that's interesting distinction 👍

**Comment by joshaber** [comment]
Looks good, but has conflicts 🙈

**Comment by niik** [comment]
🐨

**Comment by niik** [comment]
Conflict free since '93

**Comment by joshaber** [comment]
CI is :hurtrealbad:
