### PR TITLE
[Branch protection] Use new API endpoint

### LINKED ISSUE #7023: I accidentally commit locally to protected branches
**Please describe the problem you think should be solved**

"I frequently commit locally to a branch that's protected on GitHub and one that I can therefore never push to. After I realize I committed to the wrong branch, then I have to either Undo however many commits I've made, switch branches, and do the commits again on a new branch or I have to use a different method to get those commits over to a different branch."

Branches on GitHub are protected for a reason (so there's a particular level of scrutiny before code makes its way onto them), and it doesn't make sense why GitHub Desktop shouldn't have knowledge of this central concept of GitHub's overall model.

A version of this was brought up in #1021 and we explored this a bit in #4647, but I'd like to refocus the discussion around the problem before we move toward solutions.

Reference GitHub protected branch docs: https://help.github.com/en/articles/about-protected-branches

**Open questions**

1. Is this only relevant for protected branches, or are there other instances where people never want to commit to a particular branch? One that has come up previously is the default (often `master`) branch, but I want to question that assumption.
2. If a branch is protected, is there *ever* a reason someone would want to commit to that branch locally? Our assumption thus far is no.

If you have thoughts about either of the open questions, we're really interested in understanding this better.

**Success metrics**

1. If our assumptions are correct and we succeed in solving this problem, we'd anticipate that the number of commits in Desktop to a branch that's protected would drop significantly (by at least half, or potentially even to zero).

### PR DESCRIPTION
**Pull request by kuychaco**
Closes #7023

## Description

Use new `push_control` endpoint introduced in https://github.com/github/github/issues/127973 to determine whether the user's current branch is protected.

Relevant work PRs that this builds on top of: #7826, #7595 and #7529

### Screenshots

GitHub_Desktop-dev_and_first_pass_at_UI_for_warning_about_protected_branches_by_shiftkey_·_Pull_Request__7826_·_desktop_desktop

### Testing
Manually tested the following cases on review-lab:
- owner has no warning if admin not included and review is required
- owner has warning if admin is included and review is required
- collaborator on allow list has no warning
- collaborator on team on allow list has no warning
- collaborator not on allow list has warning
- collaborator on allow list has warning if review is required

## Release notes

Notes: [Feature] Suggest moving to a branch prior to committing to a protected branch

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -1474,6 +1495,13 @@ export class AppStore extends TypedBaseStore<IAppState> {
     repository: Repository,
     previouslySelectedRepository: Repository | CloningRepository | null
   ): Promise<Repository | null> {
+    this.refreshBranchProtectionState(repository)
+
+    // This is now purely for metrics collection for `commitsToRepositoryWithBranchProtections`
+    // Understanding how many users actually contribute to repos with branch protections gives us
+    // insight into who our users are and what kinds of work they do
+    this.updateBranchProtectionsFromAPI(repository)
```
Comment (kuychaco) [inline app/src/lib/stores/app-store.ts]: Now that we're only using the `repos/${owner}/${name}/branches?protected=true` endpoint to gather metrics about if a user is committing to a repository that has protected branches, we can afford to update the data less frequently (individual rule changes don't matter to us, only if the repo has a non-zero number of protected branches). So for now I'm opting to simply update it on repo change.

File: app/src/lib/stores/app-store.ts [hunk 2]
```diff
@@ -825,19 +825,40 @@ export class AppStore extends TypedBaseStore<IAppState> {
...
+        const {
+          allow_actor,
+          required_status_checks,
+          required_approving_review_count,
+        } = await api.fetchPushControl(owner, name, branchName)
+
+        const pushableByUser =
+          allow_actor &&
+          required_status_checks.length === 0 &&
+          required_approving_review_count === 0
```
Comment (outofambit) [inline app/src/lib/stores/app-store.ts]: could this go into a helper method that lives somewhere in `lib/`? this is pretty crucial logic and i want to make sure its clearly encapsulated and documented.

i'm also a little unclear why we need to use the required status checks and review counts. are these enforced for pushing directly to a branch and not just for merges?

File: app/src/lib/stores/app-store.ts (hunk 1 above)
Comment (outofambit) [reply app/src/lib/stores/app-store.ts]: 💯!

File: app/src/lib/stores/repositories-store.ts [hunk 3]
```diff
@@ -638,41 +638,6 @@ export class RepositoriesStore extends BaseStore {
 
     return branchProtectionsFound
   }
-
-  /**
-   * Check if the given branch for the repository is protected through the
-   * GitHub API.
-   */
```
[the remark this answers is not in the document]
Comment (outofambit) [reply app/src/lib/stores/repositories-store.ts]: 🔥 😍

File: app/src/lib/api.ts [hunk 4]
```diff
@@ -232,6 +232,41 @@ export interface IAPIRefStatus {
...
+  allow_actor: boolean
+
+  /**
+   * Currently unused properties
+   */
+  pattern: string | null
+  required_signatures: boolean
+  required_linear_history: boolean
+  allow_deletions: boolean
+  allow_force_pushes: boolean
```
Comment (outofambit) [inline app/src/lib/api.ts]: i like that we're including these so its easy to use them later if we need to

File: app/src/lib/api.ts [hunk 5]
```diff
@@ -719,6 +754,33 @@ export class API {
     return await parsedResponse<IAPIRefStatus>(response)
   }
 
+  public async fetchPushControl(
```
Comment (outofambit) [inline app/src/lib/api.ts]: a little doc for this method please? i think its worth calling out that if it can't get the info, it defaults to assuming full access for the user (which i think is the right approach btw).
