### PR TITLE
Prevent Dialog dismissal when clicking title bar

### LINKED ISSUE #2056: Dialogs are closed when moving main window (macOS)
### Description

Open a dialog, for example, `File -> Clone Repository`. Try to move GitHub Desktop window. Dialog is closed. Sometimes I start to enter data in dialog's fields. And when I not finished I need to move the app window. Dialog is closed, data is lost. I need to reenter data again.

### Version

**GitHub Desktop version:** 0.6.1

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** macOS Sierra 10.12.5

### Steps to Reproduce

1. Open a dialog
2. Move app window
3. Dialog is closed

**Expected behaviour:** dialog shouldn't close.

**Actual behaviour:** dialog closes.

**Reproduces how often:** always.

### PR DESCRIPTION
**Pull request by RhysBower**
Performs a check to determine if click was within the title bar and if so prevents Dialog dismissal.

I don't like how titleBarHeight is a hard coded number. Is there a way to pull this from the css variables?

Closes #2056

### CODE REVIEW

File: app/src/ui/dialog/dialog.tsx [hunk 1]
```diff
@@ -215,6 +215,14 @@ export class Dialog extends React.Component<IDialogProps, IDialogState> {
       return
     }
 
+    const titleBarHeight = __DARWIN__ ? 22 : 28
```
Comment (joshaber) [inline app/src/ui/dialog/dialog.tsx]: Could we pull this out into a constant at the top level?

File: app/src/ui/dialog/dialog.tsx [hunk 2]
```diff
@@ -10,6 +10,11 @@ import { createUniqueId, releaseUniqueId } from '../lib/id-pool'
  */
 const dismissGracePeriodMs = 250
 
+/**
+ * Title bar height in pixels. Values taken from 'app/styles/_variables.scss'.
```
Comment (joshaber) [inline app/src/ui/dialog/dialog.tsx]: This is great! Would you mind also adding a note in `_variables.scss` pointing to this file?

**Comment by joshaber** [comment]
Thank you!
