### PR TITLE
Fix unified diff discard changes availability

### LINKED ISSUE #15003: "Discard added/modified/removed lines" broken in recent builds
### The problem

Not entirely sure when this started happening, but I noticed the "Discard added/modified/removed lines" option is currently broken. I can repro this repos from different folders and origins (eg. GitHub, or ADO linked with a personal access token).

Discarding a whole file seems to work, but doing so for a group of lines doesn't seem to work at all anymore.

### Release version

3.0.5 (x64)

### Operating system

W11 22000.795

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Open a repo
3. Make any changes
4. Right click on a group of changes lines
5. Click "Discard ..."

### Log files

```
2022-07-20T15:28:34.942Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-07-20T15:28:35.741Z - info: [ui] [AppStore] loading 31 repositories from store
2022-07-20T15:28:35.744Z - info: [ui] [AppStore] found account: Sergio0694 (Sergio Pedri)
2022-07-20T15:28:35.820Z - info: [ui] [BranchPruner] Last prune took place 6 minutes ago - skipping
2022-07-20T15:28:35.920Z - info: [ui] launching: 3.0.5 (Windows 10.0.22000)
2022-07-20T15:28:35.922Z - info: [ui] execPath: 'C:\Users\sergiopedri\AppData\Local\GitHubDesktop\app-3.0.5\GitHubDesktop.exe'
2022-07-20T15:28:36.374Z - info: [ui] Subscribed 'Sergio0694' to Alive channel
2022-07-20T15:28:37.709Z - info: [ui] Stats reported.
```

Not really seeing anything in here. I tried to discard some changes 3 times, nothing was apparently logged for that.

### Screenshots

github_desktop_issue

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes #15003

## Description
It appears we overlooked disabling the context menu items to discard changes in the unified diff when whitespace changes are hidden. This pr adds that check.

Additionally, there was regression on fixing [another popover bug](https://github.com/desktop/desktop/pull/14256) in that, when unified diff gutter is clicked when whitespace changes are hidden, the whitespace informative popover doesn't stay open. This is due to how the whitespace popover is added to the react dom dynamically so a click event to show it is also getting registered in the whitespace popover which effectively dismisses it as being the doc clicked outside the popover. Originally, the popover click outside event was triggered for the mousedown event and not the click event which already fires before this is registered... thus sidestepping this timing issue. This PR adds the mousedown event back in while also leaving the click event in place so that we can use which ever works best for the given use case.

### Screenshots

https://user-images.githubusercontent.com/75402236/180268139-4602ee1b-9a91-439e-84f3-1258d5223254.mov

## Release notes

Notes: 
[Fixed] Unified diff line gutter context menu items for discard changes no longer enabled when whitespace is hidden.
[Fixed] "Show Whitespace Changes" popover appears as expected on unified diff.

### CODE REVIEW

File: app/src/ui/diff/text-diff.tsx [hunk 1]
```diff
@@ -747,6 +747,7 @@ export class TextDiff extends React.Component<ITextDiffProps, ITextDiffState> {
         {
           label: this.getDiscardLabel(range.type, range.to - range.from + 1),
           action: () => this.onDiscardChanges(file, range.from, range.to),
+          enabled: !this.props.onHideWhitespaceInDiffChanged,
```
Comment (sergiou87) [inline app/src/ui/diff/text-diff.tsx]: I think that's the wrong prop and it disables the context menu option even when whitespace changes are hidden:
```suggestion
          enabled: !this.props.hideWhitespaceInDiff,
```

File: app/src/ui/diff/text-diff.tsx [hunk 2]
```diff
@@ -762,7 +763,9 @@ export class TextDiff extends React.Component<ITextDiffProps, ITextDiffState> {
         {
           label: this.getDiscardLabel(range.type, 1),
           action: () => this.onDiscardChanges(file, lineNumber),
-          enabled: range.type !== DiffRangeType.Mixed,
+          enabled:
+            range.type !== DiffRangeType.Mixed &&
+            !this.props.onHideWhitespaceInDiffChanged,
```
Comment (sergiou87) [inline app/src/ui/diff/text-diff.tsx]: Same:
```suggestion
            !this.props.hideWhitespaceInDiff,
```

**Review by sergiou87 — CHANGES_REQUESTED** [review]

**Review by sergiou87 — APPROVED** [review]
All works great! Thanks for those changes :shipit: ✨
