### PR TITLE
Escape branch name

### LINKED ISSUE #14631: branch name with '#' doesn't open when "View branch of Github"
### The problem

branch name with '#' doesn't open when "View branch of Github"

My branch name: `ab#4176-use-badge-style-for-job-status-job-list`
> it links me to: 
> github.com/.../ab#4176-use-badge-style-for-job-status-job-list

> the right link:
> github.com/.../ab%234176-use-badge-style-for-job-status-job-list

### Release version

3.0.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Name branch with '#'
2. From GitHub desktop from menu click Branch > View Branch in Github

### Log files

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tsvetilian-ty**
Closes #14631

## Description
As an author of #14231 I had to fix this one 😄 

- Fix for unencoded branch name that causes issues with "View Branch on GitHub" and "Compare on GitHub".

### Screenshots
test-branch-name-fix

### CODE REVIEW

**Review by tidy-dev — DISMISSED** [review]
:sparkles: Thanks for that quick fix @tsvetilian-ty!

File: app/src/ui/app.tsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import * as React from 'react'
 import * as crypto from 'crypto'
+import { escape } from 'querystring'
```
Comment (niik) [inline app/src/ui/app.tsx]: The `querystring` module is marked as legacy in the Node docs. Could you please use [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) instead? It won't have any practical effect but that's what we're using elsewhere and it's well documented.

**Review by niik — CHANGES_REQUESTED** [review]
Echoing @tidy-dev's thanks here @tsvetilian-ty. I just had one small request that I'm hoping we could get in before merging

File: app/src/ui/app.tsx (hunk 1 above)
Comment (tidy-dev) [reply app/src/ui/app.tsx]: If you update that, could you also remove it's its usage in  `_openCreatePullRequestInBrowser` in the `app-store.tsx`? 

That was the reason I didn't realize it was different then rest of app, cause I saw it used there and assumed it was what we used.. even tho in the back of my mind I was thinking there was something else. Thanks @niik!

Comment (tsvetilian-ty) [reply app/src/ui/app.tsx]: Nice catch @niik! I changed both instances of `escape` to `encodeURIComponent`. 

In the original PR, I used the encoding in `_openCreatePullRequestInBrowser` as a reference. That's why I picked `escape` in the first place.

**Review by niik — APPROVED** [review]

**Comment by niik** [comment]
Thanks @tsvetilian-ty!
