### PR TITLE
a better "push needs pull" dialog to avoid race condition

### LINKED ISSUE #2738: The repository has been updated since you last pulled. Try pulling before pushing.
If this error shows up, would it be possible to change the button "Push origin" to "Pull origin"?

image

Now I'm left with only the push option, which doesn't work, so I have to hunt in the menu to find a pull command or use command line.

Actually, now after about 40 seconds, it changed to "Pull origin" by itself. Guess there might be something wrong with the update of it.

### LINKED ISSUE #5451: Pull option does not appear when "Pull first before pushing" error is thrown
## Description

On MacOS I create a commit, also on Windows machine for the same repository from another account was pushed another commit before, when I press Push on MacOS machine is gave me the error about "Pull first before pushing...blabla" but no Pull is displayed...so i am stuck.

## Version

* GitHub Desktop:1.3.3

* Operating system:
macOS High Sierra 10.13.6

## Steps to Reproduce

In our case it was reproduced like this:
1. From windows machine push to master a commit
2. From macOS machine commit to master
3. From macOS machine try to Push (Github Desktop is showing 1 Push)
4. Appears an error something like - "You have to pull before pushing"
5. Github Desktop continues to show that there is no Pull...
### Expected Behavior
After the step 4 usually GitHub Desktop loads the commit and updates UI -> so we see that there is a Pull, and after pulling we can Push.

### Actual Behavior

In the UI I always see that I have 1 Push and 0 Pulls and whatever I tried(restart Github Desktop, try Pushing again, adding one more commit to push), it doesn't help, It simply don't load the commit that had to be pulled before pushing.

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

Fixes #2738
Fixes #5451

While troubleshooting #6593 and doing some groundwork testing for the upcoming rebase flows, I noticed a bug with the classic "push needs pull" error handling that meant you could get stuck in a loop and never be able to see what's changed.

## Description

The easiest way to reproduce this issue:

 - create a new repository with a default branch and some commits, push it to GitHub
 - create a new branch, and publish it to GitHub **without making any commits**
 - switch over on GitHub, add a commit to the branch 
 - back in the app, create a different commit
 - try to push the commit

The generic Git error handler is displayed [with a message](https://github.com/desktop/desktop/blob/64367a525e09bb4497b495efedb225162b63f01d/app/src/lib/git/core.ts#L198), and `Dispatcher.fetch` fires in the background:

https://github.com/desktop/desktop/blob/64367a525e09bb4497b495efedb225162b63f01d/app/src/lib/dispatcher/error-handlers.ts#L243-L246

It's at this point that I'd expect to see the push/pull button update to show there's both a commit ahead and behind, but it never updates:

What's happening underneath is the concurrent network operation check (which was set to `true` when the `push` was started) has not been cleared (the error handing is being performed, but this flag is only cleared after the error handling completes), so the `fetch` is considered re-entrant and it's not perforrmed. 

https://github.com/desktop/desktop/blob/64367a525e09bb4497b495efedb225162b63f01d/app/src/lib/stores/app-store.ts#L2579-L2582

I suspect this only way this eventually "comes good" is when the background fetch eventually kicks in, and nothing changes while the impatient user (i.e me) repeatedly presses "Push" and wonders what happened.

This PR replaces that "fire and forget" fetch with a proper dialog to better explain the situation and run the fetch outside the error handler. I haven't finalized the flow yet, but here's the current message you will see:

I'd love your ideas about what we want to explain here @desktop/product @desktop/design 

## TODO

 - [x] confirm bug is resolved
 - [x] polish dialog message
 - [x] cleanup tracing work

## Release notes

Notes: fix "push needs pull" flow to explain context and actions better

### CODE REVIEW

**Comment by outofambit** [comment]
> and run the fetch outside the error handler.

@shiftkey what do you mean by this? Are you planning to modify the underlying handling of fetching while another network operation is in process or is this PR only dealing with the dialog displayed?

**Comment by shiftkey** [comment]
@outofambit I don't plan to change the concurrent network check in this PR. #6141 leverages this behaviour to address some long-running issues, and the only motivator for changing this behaviour that I can currently think of is #1011.

The new behaviour is to perform the `fetch` when the user presses `Fetch` in the new dialog.

File: app/src/ui/push-needs-pull/push-needs-pull-warning.tsx [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        }
+        onDismissed={this.props.onDismissed}
+        onSubmit={this.onFetch}
+        type="warning"
+      >
+        <DialogContent>
+          <p>
+            Desktop is unable to push commits to this branch because there are
+            new commits on the remote. It needs to fetch these new commits to
+            figure out how to reconcile these changes with your local commits.
```
Comment (billygriffin) [inline app/src/ui/push-needs-pull/push-needs-pull-warning.tsx]: I wonder if it's possible to make this a bit more beginner-friendly with a small change.

"Desktop is unable to push commits to this branch because there are commits on the remote that are not present on your local branch. It needs to fetch these new commits before pushing in order to reconcile them with your local commits."

I don't love it so feel free to suggest alternatives (or disagree).

**Comment by allthesignals** [comment]
I am also seeing this - I'm not sure if I have my remote tracking set up incorrectly or not, but there is no option anywhere to sync with origin or pull latest commits from the branch.

I know I have commits on the remote but I can't pull them down through this interface. Fine, I can just do it through command line, but then this is pretty disruptive of a common git workflow.

**Comment by shiftkey** [comment]
Dropping in some updated screenshots of the dialog (my screen recording setup is busted right now, apologies for the lo-fi info):



I also added in a Loading spinner to the fetch button because the user might not see the fetch progress because of how the dialog steals the attention (screenshot is a bit darker because I literally had to `debugger` to take a decent shot):



I went down this path because it felt like a little "what is happening" moment and showing some progress before closing the dialog seemed like a good way to help transition the user back to try and pull again.

**Comment by shiftkey** [comment]
I've assigned this to `1.7.0` because it's was something I encountered easily while testing rebase flows, but this could be pulled in sooner if we want to address the original bug #2738 before then.

File: app/src/ui/push-needs-pull/push-needs-pull-warning.tsx [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+        dismissable={!this.state.isLoading}
+        onDismissed={this.props.onDismissed}
+        onSubmit={this.onFetch}
+        type="warning"
+      >
+        <DialogContent>
+          <p>
+            Desktop is unable to push commits to this branch because there are
+            commits on the remote that are not present on your local branch. It
+            needs to fetch these new commits before pushing in order to
```
Comment (say25) [inline app/src/ui/push-needs-pull/push-needs-pull-warning.tsx]: Maybe drop the `It needs to `
```suggestion
            Fetch these new commits before pushing in order to
```

Comment (shiftkey) [reply app/src/ui/push-needs-pull/push-needs-pull-warning.tsx]: There's a preceding `It` on the last line that means I had to push e38b7f9 rather than take this in.

**Comment by shiftkey** [comment]
Just merged `development` into this branch because of some conflicts with #6755
