### PR TITLE
Move items to trash from main process

### LINKED ISSUE #13433: Unable to Discard Files
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Version 2.9.6-beta1 (x64)
Windows 10

### Steps to reproduce the behavior

1. Make a change
2. Click right click discard changes on file
3. See application hang

### Expected behavior

File is discarded

### Actual behavior

App hangs, you are unable to cancel discard changes as well.

### Screenshots

image

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

This is the first version with new Electron and there are Electron changes around file discards

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #13433

## Description

With the upgrade to Electron 13 in #13426 we introduced a regression in the app when running on Windows where `electron.shell.trashItem` would fail with `Failed to create FileOperation instance`. According to https://github.com/electron/electron/issues/29598 the solution (at least for now) is to invoke that `trashItem` method from the main process.

On macOS, this doesn't seem to be necessary. However, since this approach works too, I preferred to keep the same implementation for both OS.

## Release notes

Notes: no-notes

### CODE REVIEW

File: app/src/lib/app-shell.ts [hunk 1]
```diff
@@ -35,7 +35,28 @@ export interface IAppShell {
...
+        ) => {
+          if (error === null) {
+            resolve()
+          } else {
+            reject(error)
+          }
+        }
+      )
+
+      ipcRenderer.send('move-to-trash', { path })
```
Comment (niik) [inline app/src/lib/app-shell.ts]: Could we use [ipcRenderer.invoke](https://www.electronjs.org/docs/latest/api/ipc-renderer#ipcrendererinvokechannel-args) instead of send here to avoid setting up our own single use listener? Seems like the this approach could suffer problems should we happen to call it before the previous invocation completed.

**Review by niik — CHANGES_REQUESTED** [review]

File: app/src/lib/app-shell.ts (hunk 1 above)
Comment (sergiou87) [reply app/src/lib/app-shell.ts]: Absolutely! FWIW I used `.send` because (1) I had no idea about that and (2) the rest of the methods below in this very same file also use `.send`. Should we change all of those too? (If not now, at some point)

Comment (niik) [reply app/src/lib/app-shell.ts]: > the rest of the methods below in this very same file also use .send. Should we change all of those too? (If not now, at some point)

Send is fine when you don't need a result and the operation can't fail (or we don't care that it fails) but yeah, we should definitely change that `openExternal` to use `invoke` instead. I imagine `invoke` didn't exist at the time that was written or we just didn't catch it.

Comment (sergiou87) [reply app/src/lib/app-shell.ts]: @niik fixed in 6ea87e0bb09ab2ec8c73f78b468d24427ef9fc1d

Took me a while to rebuild and retest everything, sorry! But seems to work now on macOS and Windows 😌

**Review by niik — APPROVED** [review]
