### PR TITLE
fix for when Git detects an ambiguous ref

### LINKED ISSUE #1736: Unable to resolve reference 'refs/heads/heads/Microsoft/master'
### Description

Pushing commits on [my TypeScript fork](https://github.com/SaschaNaz/TypeScript) shows this error:

Push works well regardless of the error.

### Version

**GitHub Desktop version:** 0.5.7

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Push any commit on forked repository
1. See error
1. Click anywhere to dismiss the error dialog

**Expected behaviour:**

* Error shouldn't occur
* Error shouldn't be dismissed by clicking backdrop area

**Actual behaviour:** Error occurs and be dismissed by clicking backdrop area

**Reproduces how often:** 100%

### Logs

No logs.

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #1736

If you happen to name a branch the same as a remote ref, Git will make it unambiguous in the output. Consider this example, where I have a branch named `Microsoft/master` which is tracking a remote named `Microsoft` and it's ref named `master`:

```
$ git for-each-ref --format="%(refname) - %(refname:short) - %(upstream:short)" refs/heads
refs/heads/Microsoft/master - heads/Microsoft/master - remotes/Microsoft/master
refs/heads/es3-d-ts - es3-d-ts - origin/es3-d-ts
refs/heads/master - master - origin/master
```

When we fetch the list of local and remote branches, Git will add the `heads/` prefix for the local ref and `remotes/` to the remote ref to ensure both values are unambiguous.

As part of our background fetching, we need to convert the local branch into a fully qualified ref before invoking `update-ref`. However our formatting didn't consider this case and so we duplicate `heads` and cause Git to error.

Oh, and in case you think that this is good habit, please don't. Git warns you about it from the CLI:

```
$ git checkout Microsoft/master
warning: refname 'Microsoft/master' is ambiguous.
...
```

### CODE REVIEW

**Comment by joshaber** [comment]
>Consider this example, where I have a branch named Microsoft/master which is tracking a remote named Microsoft and it's ref named master

ur a monster

File: app/src/lib/git/refs.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+  if (name.startsWith('heads/')) {
+    // In some cases, Git will report this name explicitly to distingush from
+    // a remote ref with the same name - this ensures we format it correctly.
+    return `refs/${name}`
+  } else {
+    // By default Git will drop the heads prefix unless absolutely necessary
+    // - include this to ensure the ref is fully qualified.
+    return `refs/heads/${name}`
+  }
+}
```
Comment (joshaber) [inline app/src/lib/git/refs.ts]: Newline 🙏

Comment (shiftkey) [inline app/src/lib/git/refs.ts]: 76d5da3f22d2f0f37ac88786b9ef4b61fffd41db
