### PR TITLE
Disable all menu items while in welcome flow

### LINKED ISSUE #1529: actions unrelated to welcome wizard are blocked while welcome wizard is active
### Version

**GitHub Desktop version:** 0.5.3

**OS version:** MacOS 10.12.3

### Steps to Reproduce

1. do a fresh install of Desktop
1. select the top `GitHub Desktop` menu item
1. click Preferences

**Expected behaviour:** application shows Preferences

**Actual behaviour:** nothing

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes #1529

### CODE REVIEW

File: app/src/lib/menu-update.ts [hunk 1]
```diff
@@ -127,13 +127,18 @@ function getMenuState(state: IAppState): Map<MenuIDs, IMenuItemState> {
     'show-history',
     'show-repository-list',
     'show-branches-list',
+    'new-repository',
+    'add-local-repository',
+    'clone-repository',
```
Comment (niik) [inline app/src/lib/menu-update.ts]: @iAmWillShepherd These three doesn't look like they're repository scoped, i.e they don't require a selected repository. We should move this to explicit enable/disable calls further down.

Comment (iAmWillShepherd) [inline app/src/lib/menu-update.ts]: Nice catch.

**Comment by iAmWillShepherd** [comment]
🥇

File: app/src/lib/menu-update.ts [hunk 2]
```diff
@@ -162,14 +168,18 @@ function getMenuState(state: IAppState): Map<MenuIDs, IMenuItemState> {
     menuStateBuilder.disable('view-repository-on-github')
     menuStateBuilder.disable('push')
     menuStateBuilder.disable('pull')
+
+    menuStateBuilder.disable('new-repository')
+    menuStateBuilder.disable('add-local-repository')
+    menuStateBuilder.disable('clone-repository')
```
Comment (niik) [inline app/src/lib/menu-update.ts]: So I don't think this is quite right either (if I'm reading this correctly) since we're still disabling these items when there's no repository selected and we shouldn't.

**Comment by iAmWillShepherd** [comment]
👍

File: app/src/lib/menu-update.ts [hunk 3]
```diff
@@ -164,12 +166,29 @@ function getMenuState(state: IAppState): Map<MenuIDs, IMenuItemState> {
...
+    'create-branch',
+  ]
+
+  if (inWelcomeFlow) {
+    for (const id of welcomeScopedIds) {
+      menuStateBuilder.disable(id)
+    }
+  } else {
+    for (const id of welcomeScopedIds) {
+      menuStateBuilder.enable(id)
```
Comment (niik) [inline app/src/lib/menu-update.ts]: So it seems to me like this would unconditionally enable `create-branch` even though the `TipState` is unknown which is probably not what we want.

Additionally (and this is an edge case, I'll grant you). It's possible to both have a repository selected and be in the welcome flow at the same time by clearing the `localStorage` key so I think we should make `repositoryActive` take `inWelcomeFlow` into account

```ts
const repositoryActive = windowOpen && repositorySelected && !state.showWelcomeFlow
```

By doing that and removing the `create-branch` I think we'd get rid of this particular problem. This logic is pretty hard to reason about. Anytime we have an intersection of items in both the `repositoryScopedIds` and `inWelcomeFlow` we're in for a bad time. I don't have a better solution for now though but perhaps a warning comment would be in order?

File: app/src/lib/menu-update.ts [hunk 4]
```diff
@@ -164,12 +166,29 @@ function getMenuState(state: IAppState): Map<MenuIDs, IMenuItemState> {
     menuStateBuilder.disable('pull')
   }
 
+  const welcomeScopedIds: ReadonlyArray<MenuIDs> = [
```
Comment (niik) [inline app/src/lib/menu-update.ts]: We should probably include the about and preferences menu items here as well since we're not showing any dialogs while in the welcome flow

File: app/src/lib/menu-update.ts (hunk 3 above)
Comment (iAmWillShepherd) [inline app/src/lib/menu-update.ts]: By removing `create-branch` don't we also get rid of our intersection problem?

File: app/src/lib/menu-update.ts (hunk 4 above)
Comment (iAmWillShepherd) [inline app/src/lib/menu-update.ts]: In agreement on the **Preferences**, but shouldn't **About** be accessible no matter what state the app is in? Since it's a [standard macOS menu item](https://electron.atom.io/docs/api/menu/#standard-menu-item-actions), I'd say yes.

Comment (niik) [inline app/src/lib/menu-update.ts]: > shouldn't About be accessible no matter what state the app is in? Since it's a standard macOS menu item, I'd say yes.

I'd say yes as well if it actually did anything. As it stands right now we're not able to show dialogs while in the welcome flow. When (if) that changes I agree that it should be enabled.

File: app/src/lib/menu-update.ts (hunk 3 above)
Comment (niik) [inline app/src/lib/menu-update.ts]: We do, but I believe we still need the logic for flipping `repositoryActive` to false if we're showing the welcome flow since it's possible that we have an active repository selection _and_ are showing the welcome flow at the same time.

**Comment by iAmWillShepherd** [comment]
💯
