### PR TITLE
fix: pull from paginated local vs head-n based on last commit

### LINKED ISSUE #20882: Commit history doesn't show more than 100 unpushed commits at once
### The problem

I have a repository with over 100 unpushed commits (don't ask me why, private solo repository, needed for version tracking), and the UI correctly shows the number of commits to push on "Push origin" button, but the commit list only shows push icons (arrows) on the last 100 commits. It has caused me some trouble because I am using unpushed commits to figure out where to start tracking my changes since the last public release, and I had to instead resort to comparing commit dates to release dates.

I attached a screenshot where I've selected the last 100 commits and I show that the push icon stops appearing beyond those 100 commits, despite me having almost 200 unpushed commits.

### Release version

3.5.2 x64

### Operating system

Windows 10

### Steps to reproduce the behavior

_No response_

### Log files

_No response_

### Screenshots

Image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ashdawngary**
Closes #20882

## Description

Upgrades `loadLocalCommits` to support paginated loading of local commits.  Achieves this via a `skip` parameter which preserves behavior when undefined, otherwise retrieves commits from an offset on a range.  

The original bug was due to `loadLocalCommits` only being called once with its initial batch size of 100 (hence why only 100 records will have the local commit tag on them), and the rest were loaded via `loadCommitBatch`.  Now `_loadNextCommitBatch` will choose between loading locally or `loadCommitBatch` based on whether the last commit in the flattened page list is a local commit.  If the original method fails or produces 0 entries, we use the latter as a backup too.

### Screenshots

https://github.com/user-attachments/assets/db2ef0fc-5d92-4432-831b-dd06e8945802

Tests Various conditions (< 100 commits), more than 100 commits etc

## Release notes

Fixed issue of only up to 100 unpushed commits loading in history

Notes:

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -1717,13 +1717,29 @@ export class AppStore extends TypedBaseStore<IAppState> {
...
+        newCommits = await gitStore.loadCommitBatch('HEAD', commits.length)
+      }
+
+      if (!newCommits) {
         return
       }
 
       this.repositoryStateCache.updateCompareState(repository, () => ({
-        commitSHAs: commits.concat(newCommits),
+        commitSHAs: commits.concat(newCommits ?? []),
```
Comment (sergiou87) [inline app/src/lib/stores/app-store.ts]: No need for this change, as there is a `if (!newCommits)` above
```suggestion
        commitSHAs: commits.concat(newCommits),
```

File: app/src/lib/stores/git-store.ts [hunk 2]
```diff
@@ -597,39 +597,61 @@ export class GitStore extends BaseStore {
    * Load local commits into memory for the current repository.
    *
    * @param branch The branch to query for unpublished commits.
+   * @param skip The amount of commits to skip to support pagination loading of local commits. If skip is undefined,
+   * this will reset the local commits cache and treat it as a pagination reset.
```
Comment (sergiou87) [inline app/src/lib/stores/git-store.ts:601]: Add `@returns` line explaining what it returns

**Review by sergiou87 — CHANGES_REQUESTED** [review]
Changes make sense and works as advertised, nice fix!

Only a couple of minor requests before merging.

**Comment by ashdawngary** [comment]
> Changes make sense and works as advertised, nice fix!
> 
> Only a couple of minor requests before merging.

all set, thanks!

**Comment by ashdawngary** [comment]
> Changes make sense and works as advertised, nice fix!
> 
> Only a couple of minor requests before merging.

@sergiou87 this should be in a mergable state

**Review by sergiou87 — DISMISSED** [review]
Great work!!! :shipit: 

And thank you for the ping, it's been a hectic month and I forgot about this 😬 😳

**Comment by sergiou87** [comment]
@ashdawngary I think you need to run `yarn lint:fix` to fix the lint issues 😅  Let me know when that's done! Thank you 🙇‍♂️

**Comment by sergiou87** [comment]
Sorry @ashdawngary 😭  But the macOS runner image we used for CI builds just got deprecated, I updated it in https://github.com/desktop/desktop/pull/21362

Do you mind updating your branch with the latest `development` so we can see all checks pass? 🙏 

Thank you!

**Comment by ashdawngary** [comment]
> Sorry @ashdawngary 😭 But the macOS runner image we used for CI builds just got deprecated, I updated it in #21362
> 
> Do you mind updating your branch with the latest `development` so we can see all checks pass? 🙏
> 
> Thank you!

all set

**Review by sergiou87 — APPROVED** [review]
Alll good!! Thanks again for your patience 🙇‍♂️
