### PR TITLE
tidy up initial "external editor" experience

### LINKED ISSUE #2551: "Open in Atom" menu item despite Atom not being installed
### Description

The `Repository` menu presents me with the `Open in Atom` option despite Atom not being installed.

When I click it, I get an error message:

In the configuration, only VSCode and Sublime are available (which is correct, both are installed). VSCode _seems_ to be selected, but as indicated by the menu item, it's not internally / in GitHub Desktop's config.

Selecting Sublime and switching back to VSCode fixes it:

### Version

**GitHub Desktop version:** 0.8.0
**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Install GitHub Desktop (_or_ clear the local storage files in `AppData\Roaming\GitHub Desktop\Local Storage`)
1. Open the `Repository` menu
1. Observe the non-functional `Open in Atom` menu

**Expected behavior:** the menu item should match the selected external editor in `Options -> Advanced` with a fresh config
**Actual behavior:** it's always Atom

**Reproduces how often:** 100%

#### Additional Information

Atom used to be installed on my system, so maybe something is left-over that makes GitHub Desktop think it's still around. This seems unlikely as it's not presented in the external editor dropdown-menu however.

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2551 in a few ways:

 - [x] checks what you have installed when initializing the application state
 - [x] assign first found editor to local storage if found
 - [x] if no matching editors, display "Open in External Editor" for menu items
 - [x] when trying to launch with no editors, user should see existing dialog about recommending Atom
 - [x] fix bug about item switching being required to actually persist

### CODE REVIEW

File: app/src/ui/preferences/advanced.tsx [hunk 1]
```diff
@@ -48,38 +43,31 @@ export class Advanced extends React.Component<
...
 
-  public async componentDidMount() {
-    const [availableEditors, availableShells] = await Promise.all([
-      getAvailableEditors(),
-      getAvailableShells(),
-    ])
-
-    const editors = availableEditors.map(editor => editor.editor)
-    let selectedExternalEditor = this.props.selectedExternalEditor
+  public async componentWillReceiveProps(nextProps: IAdvancedPreferencesProps) {
```
Comment (shiftkey) [inline app/src/ui/preferences/advanced.tsx]: A quick note about what I stumbled on as part of #2551 and the preferences dialog:

 - `Preferences.tsx` (parent) has a `componentWillMount` function, and `Advanced.tsx` (child) had a `componentDidMount` function
 - In theory, I was hoping to see these functions fire in order relative to the hierarchy, but here is what I was seeing at runtime:
   - `Advanced.componentDidMount: selecting new editor: 'Visual Studio Code'`
   - `Preferences.onSelectedEditorChanged: got 'Visual Studio Code'`
   - `Preferences.componentWillMount: setting state: 'Atom'` 
 - Looks like any state change from child is discarded due to it being too early in the lifecycle 

So rather than hacking around this constraint, I've moved the state around computing the editor/shell list up into `Preferences` and used `componentWillReceiveProps` (later in the component lifecycle) to flow changes back when there's a mismatch between the selected editor and the list of available editors.
