### PR TITLE
handle diff-too-large scenario with less crashes

### LINKED ISSUE #1524: RangeError: Invalid string length
We're getting a few RangeError, looks like it's limited to one or a few installations at the moment ([rollup](https://haystack.githubapp.com/desktop/rollups/d4250d5fcd308f07ca9a2a64cce72626))

```
RangeError: Invalid string length
    at Socket.onChildStdout (child_process.js:279:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

[This issue](https://github.com/nodejs/node-v0.x-archive/issues/14170) seems to indicate it could be due to not being able to allocate enough memory but it's a very old issue so I don't know how much to read into it. Regardless it'd be real nice if we could get a sense of what command we were executing when this occurred.

### LINKED ISSUE #1818: Repeated 'Error: "toString()" failed' on launch.
### Description

As of yesterday, whenever I try to open Desktop, it tries to sync and then crashes.

### Version

**GitHub Desktop version:**
Unknown - (Latest I think?)

**OS version:**
Windows 10 (Home), Version 1703, Build 15063.296

### Steps to Reproduce

1. Open GitHub Desktop...
2. Wait for it to try and sync...
3. Watch your hopes and dreams crumble.

I have two repos cloned in Desktop; https://github.com/rivermont/spidy and https://github.com/rivermont/instagram-graph.

It opens to spidy, and it appears that there is a push that it never manages to send before crashing.

**Expected behaviour:**
Open GitHub Desktop without problems.

**Actual behaviour:**
After opening, Desktop tries to sync and then crashes.

**Reproduces how often:**
100% of the time.

### Attempted Debugging

  - Force quit Desktop from Task Manager
  - Restart computer.
  - Push the commit really fast before it crashes.
  - Run `Update.exe` from `\AppData\Local\GitHubDesktop\`

###Logs

**Crash Report**
Displayed in a nice red box with a single `Quit` button:

>GitHub Desktop encountered an uncaught exception, leaving it in an invalid state.

>Error: "toString()" failed
    at Uint8Array.Buffer.toString (buffer.js:503:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at readableAddChunk (_stream_readable.js:164:31)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)

**Crash Logs**
Stolen from `\AppData\Roaming\GitHub Desktop\logs\`:

>2017-05-29T02:21:13.993Z - error: Uncaught exception on renderer process
Error: "toString()" failed
    at Uint8Array.Buffer.toString (buffer.js:503:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at readableAddChunk (_stream_readable.js:164:31)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)

### PR DESCRIPTION
**Pull request by shiftkey**
~~🌵 🌵 🌵 Depends on #1897 - go review that first 🌵 🌵 🌵~~

Fixes #1818
Fixes #1524

This switches diff parsing over to use a `spawn` based API so we can lazily encode the diff and handle the scenario where a file diff exceeds the `kMaxLength` limitation Node enforces when creating strings. There's probably some performance improvements we can address in here afterwards, but we need to be mindful of this limitation because it's a hard limit which can lead to tearing down the process.

screen shot 2017-06-05 at 11 34 27 am

- ~~[ ] identify why multiple invocations are occurring - can we eliminate these?~~ :boot:

 - [x] diff tests are impacted by this change, gotta figure out if this can be supported

### Uncovered Issues

While fixing this I've identified a couple of performance areas we should look at:

 - there's no indicator going on for when a diff takes more than a moment to render. In this extreme case, the execution of Git can take up to 20 seconds. It would be nice to show some sort of "working" indicator in these situations: #1913
 - `git status` may take multiple seconds to complete, which is really noticeable on the initial load for this repository as we don't have any repository state to work with. In lieu of speeding that up, perhaps we need some sort of indicator there too: #1914
 - `AppStore._loadStatus` will always try and redraw the diff, and it doesn't get caught by our existing checks for when a diff can be skipped or ignored. It'd be nice to abort a Git invocation (we could do [this](https://nodejs.org/api/child_process.html#child_process_child_kill_signal) now), but promises don't support this directly so it'll require some more refactoring to the abstractions: #1915

~~I'll move these out to other issues before this gets closed out, I just wanted to write them down now while they're in front of me. Let me know your feels on these above things.~~

### CODE REVIEW

File: app/src/lib/git/diff.ts [hunk 1]
```diff
@@ -54,24 +109,49 @@ export function getWorkingDirectoryDiff(repository: Repository, file: WorkingDir
...
-    opts = { successExitCodes: new Set([ 0, 1 ]) }
-    args = [ 'diff', '--no-ext-diff', '--no-index', '--patch-with-raw', '-z', '--no-color', '--', '/dev/null', file.path ]
+    successExitCodes = new Set([ 0, 1 ])
+
+    args = [ 'diff', '--no-ext-diff', '--no-index', '--patch-with-raw', '-z', '--no-color' ]
+
+    // enable --binary unless we know it's an image format
+    const extension = Path.extname(file.path)
+    if (!imageFileExtensions.has(extension)) {
+      args.push('--binary')
```
Comment (shiftkey) [inline app/src/lib/git/diff.ts]: This check makes me feel bad but if we enable this for known binary formats Git is actually eager to create a patch that can be applied for these binary files, so it no longer shows the "Binary files differ" message. Annoying, but perhaps there's some flag I've missed here.

Comment (shiftkey) [inline app/src/lib/git/diff.ts]: Nevermind, this isn't important to the PR - I just need to force node to output binary content.

There's still something weird up with the diff changes here that I need to get to the bottom of though :hurtrealbad:

File: app/src/models/diff.ts [hunk 2]
```diff
@@ -45,11 +47,20 @@ export interface IBinaryDiff {
   readonly kind: DiffType.Binary
 }
 
+export interface IDiffTooLarge {
+  readonly kind: DiffType.TooLarge
+  /**
+   * The length of the diff output from Git which exceeds the runtime limits
```
Comment (joshaber) [inline app/src/models/diff.ts]: Could you include the units (presumably bytes)?

File: app/test/unit/git/rev-parse-test.ts [hunk 3]
```diff
@@ -16,8 +16,9 @@ describe('git/rev-parse', () => {
 
   let repository: Repository | null = null
 
-  beforeEach(() => {
+  beforeEach(async () => {
```
Comment (joshaber) [inline app/test/unit/git/rev-parse-test.ts]: The changes in this file look unnecessary?

File: script/test-setup [hunk 4]
```diff
@@ -4,8 +4,12 @@
 
 const fs = require('fs')
 const path = require('path')
+const cp = require('child_process')
 const { getUserDataPath } = require('./dist-info')
 
+const output = cp.execSync('git config -l --show-origin', { encoding: 'utf-8' })
+console.log(`${output}\n\n`)
```
Comment (joshaber) [inline script/test-setup]: What's this for?

File: app/src/lib/git/diff.ts [hunk 5]
```diff
@@ -10,6 +10,72 @@ import { DiffType, IRawDiff, IDiff, IImageDiff, Image } from '../../models/diff'
...
+
+    const startTime = (performance && performance.now) ? performance.now() : null
+
+    const process = GitProcess.spawn(args, path)
+    process.stdout.setEncoding('binary')
+
+    const stdout = new Array<Buffer>()
+
+    process.stdout.on('data', (chunk) => {
+      if (chunk instanceof Buffer) {
```
Comment (joshaber) [inline app/src/lib/git/diff.ts]: Since we set the encoding above to `binary`, wouldn't we always get a `Buffer`?

File: app/src/lib/git/diff.ts [hunk 6]
```diff
@@ -10,6 +10,72 @@ import { DiffType, IRawDiff, IDiff, IImageDiff, Image } from '../../models/diff'
...
+      // as we cannot proceed without the contents of the stdout stream
+      if (startTime) {
+        const rawTime = performance.now() - startTime
+        if (rawTime > 1000) {
+          const timeInSeconds = (rawTime / 1000).toFixed(3)
+          log.info(`Executing ${commandName} (took ${timeInSeconds}s)`)
+        }
+      }
+
+      const maximumStringSize = 268435441
```
Comment (joshaber) [inline app/src/lib/git/diff.ts]: Since this is a pretty important magic number, what do you think about pulling it up to file scope and documenting it?

File: app/src/lib/git/diff.ts [hunk 7]
```diff
@@ -10,6 +10,72 @@ import { DiffType, IRawDiff, IDiff, IImageDiff, Image } from '../../models/diff'
...
 
+function wrapAndParseDiff(args: string[], path: string, name: string, callback: (diff: IRawDiff) => Promise<IDiff>, successExitCodes?: Set<number>): Promise<IDiff> {
+
+  return new Promise<IDiff>((resolve, reject) => {
+    const commandName = `${name}: git ${args.join(' ')}`
+    log.debug(`Executing ${commandName}`)
+
+    const startTime = (performance && performance.now) ? performance.now() : null
+
+    const process = GitProcess.spawn(args, path)
```
Comment (joshaber) [inline app/src/lib/git/diff.ts]: It'd be nice to standardize on `spawn` so that we only have one codepath, but that can wait. Mind opening an tech debt issue to track it tho?

**Comment by joshaber** [comment]
>While fixing this I've identified a couple of performance areas we should look at:

Yeah, breaking this up into separate issues would be ✨

File: script/test-setup (hunk 4 above)
Comment (shiftkey) [inline script/test-setup]: Dumping the current state of the git config before running the test suite. I've ported this over to #1910 as it helped with investigating config differences between my environment and CI.

File: app/src/lib/git/diff.ts (hunk 5 above)
Comment (shiftkey) [inline app/src/lib/git/diff.ts]: Good shout :metal:

File: app/src/lib/git/diff.ts (hunk 7 above)
Comment (shiftkey) [inline app/src/lib/git/diff.ts]: @joshaber are you talking about ditching `GitProcess.exec` for `GitProcess.spawn`, or just using `child_process.spawn`?

Comment (joshaber) [inline app/src/lib/git/diff.ts]: >re you talking about ditching GitProcess.exec for GitProcess.spawn

This one ☝️

Comment (shiftkey) [inline app/src/lib/git/diff.ts]: @joshaber #1911

File: app/src/lib/git/diff.ts (hunk 5 above)
Comment (shiftkey) [inline app/src/lib/git/diff.ts]: We get failing tests instead, so I guess not :trollface:

**Comment by joshaber** [comment]
This looks good but needs a merge now 🙈

**Comment by joshaber** [comment]
👍
