### PR TITLE
Home/End keys

### LINKED ISSUE #6295: Home/End keys do not work in diff view
## Description
It can be convenient to jump to the end of a long list of changed files using the End key. It can also be convenient to jump to the end of a long diff by pressing the End key.

The first one works, the second doesn't 😢 

## Version

* GitHub Desktop: 1.5.0
* Operating system: macOS 10.13.6

## Steps to Reproduce

1. Open a repo and make changes to multiple files, so that the list does not fit in the window height
2. Click a file name
3. Press End and Home to jump to the bottom and top of the list
4. Click on a file that has a large diff that does not fit in the window height
5. Click on the diff to focus it
6. Press End and Home to attempt to jump to the button and top of the diff
7. Be slightly disappointed when nothing happens in 6.

### Expected Behavior
The diff can be navigated using Home and End keys.

### Actual Behavior
Diff window does not respond to Home and End keys (it does respond to PgUp and PgDn).
Changed files list only responds when the focused file is on screen. If it scrolls outside the visible area, keys no longer function.

### PR DESCRIPTION
**Pull request by AndreiMaga**
Closes #6295

## Description

- Added shortcuts for home/end keys
- ```Home``` will jump to the start of the diff
- ```End``` will jump to the end of the diff
- Added shortcuts for ```Cmd+ Up/Down```

## Release notes

Notes: <kbd>Home</kbd> and <kbd>End</kbd> buttons will now work in all lists, also <kbd>Cmd + Up/Down</kbd>will emulate <kbd>Home</kbd>/<kbd>End</kbd>.

### CODE REVIEW

**Comment by AndreiMaga** [comment]
I implemented : ```Cmd/Ctrl + Up/Down``` as stated in the issue, but as I don't own a mac and I'm not sure my solution works with ```Cmd``` also.

**Comment by AndreiMaga** [comment]
@tierninho
I've tested this on windows quite a lot and I think it's ready for review

**Comment by tierninho** [comment]
@AndreiMaga Thanks for the update! Added the review label for someone on the team to take a look.

**Comment by Str8SmArt** [comment]
Get the fuck out of my account!

**Comment by jrock4eva** [comment]
Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

File: app/src/ui/lib/list/list.tsx [hunk 1]
```diff
@@ -397,6 +399,8 @@ export class List extends React.Component<IListProps, IListState> {
         this.props.selectionMode !== 'single'
       ) {
         this.addSelection('up', event)
+      } else if (event.ctrlKey) {
```
Comment (niik) [inline app/src/ui/lib/list/list.tsx:402]: Same question here as with <kbd>Ctrl+Down</kbd>

File: app/src/ui/lib/list/list.tsx [hunk 2]
```diff
@@ -386,6 +386,8 @@ export class List extends React.Component<IListProps, IListState> {
         this.props.selectionMode !== 'single'
       ) {
         this.addSelection('down', event)
+      } else if (event.ctrlKey) {
```
Comment (niik) [inline app/src/ui/lib/list/list.tsx:389]: Is <kbd>Ctrl+Down</kbd> a common pattern for navigating lists on Windows or macOS? It's not a pattern I'm familiar with so I'd feel a lot more confident in merging this change if you could provide some links to platform-specific documentation or list some built-in apps that use this pattern. If it's just one of the platforms then we should conditionalize it to that platform.

<kbd>Ctrl+Up</kbd> and <kbd>Ctrl+Down</kbd> seems to be system shortcuts on macOS related to Window management.

image

**Comment by AndreiMaga** [comment]
> 
> 
> Hey @AndreiMaga, thanks so much for wanting to contribute. I apologize for this having sat for so long without a review. We're working through a bit of a backlog.
> 
> Is this change something you're still keen on getting into the Desktop app? If so I'm overall happy with the change with the exception of the Ctrl+Up / Ctrl+Down addition in lists where I'd like to see some documentation about that being an established pattern. It seems like your main objective with this PR was to add the `Home/End` buttons so unless you feel strongly about the Ctrl+Up / Ctrl+Down addition we can remove that and merge this PR with just the Home/End change.

Hey @niik, don't worry about the delay. The Up/Down keys were mentioned by @tierninho in the issue and that's why I've implemented them.
And as far as I know, they are kind of [common shortcuts on mac](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing) and it started to bleed into windows [as browsers started using them](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_current-page).

**Comment by niik** [comment]
Thanks for getting back to us @AndreiMaga!

> And as far as I know, they are kind of [common shortcuts on mac](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing) and it started to bleed into windows [as browsers started using them](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_current-page).

Looking at that page I only see `Command+Up` and `Command+Down` being common shortcuts on macOS, not `Ctrl+Up/Down`. If you'd like to implement that specifically for macOS that'd be great (it'd be something like `__DARWIN__  && e.metaKey` instead of `e.ctrlKey` if I'm not mistaken.

Let me know if you'd like to keep it but conditionalized to macOS and the Command key.

**Comment by AndreiMaga** [comment]
> Let me know if you'd like to keep it but conditionalized to macOS and the Command key.

Well, if it's there(the shortcut list) might as well keep it, I'm working on it right now.

**Comment by AndreiMaga** [comment]
@niik should be good, I don't own a mac so I can't test it.

**Comment by tierninho** [comment]
Sorry for the bother, but where did we end up with this change? Was it this 👇 ?

Windows: Home/End, no Ctrl-up/down keys
Mac: Home/End , plus Ctrl-up/down keys

**Comment by AndreiMaga** [comment]
> 
> 
> Sorry for the bother, but where did we end up with this change? Was it this 👇 ?
> 
> Windows: Home/End, no Ctrl-up/down keys
> Mac: Home/End , plus Ctrl-up/down keys

For Mac is <kbd>Cmd</kbd> instead of <kbd>Ctrl</kbd>

**Comment by tierninho** [comment]
Oops, typo. So that the is the functionality that is expected at this point?

**Comment by niik** [comment]
Hey again @AndreiMaga, thanks for sticking with this!

One thing that I noticed while playing with this is that the selected row doesn't update when you'e using the home/end keys. I.e. they only scroll the list. This seems contrary to how Home/End works in native Windows applications like Explorer. I took a stab at addressing this and got it working. Would you mind if I pushed those changes to this branch and then we could have another engineer do a review on my changes? If not I'm happy to either open a PR targeting this branch or close this PR and incorporate your changes into a new PR.

**Comment by AndreiMaga** [comment]
Hey @niik .
Sure, I don't mind you pushing the changes to this branch, do I need to configure something on my fork?

**Comment by niik** [comment]
> Sure, I don't mind you pushing the changes to this branch

Awesome, I've just done that. [Take a look](https://github.com/desktop/desktop/pull/8644/files/a3d2f0f0966a15754c679f159981520301f40606..27ff46bbe88060978b29d48cb6e5d1eaf7caea71) and let me know what you think! I'm going to ask @rafeca to review this now that I've contributed to it. He's out this week but I'm sure we can get it reviewed again next week.

> do I need to configure something on my fork?

Nope! Your PR was created with the [Allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) option.

@tierninho Care to take this for another spin? Cmd+ArrowUp/Cmd+ArrowDown on macOS and Home/End on Windows should move the selection to the first or last item in a list. It's helpful to test if you've got a list with a lot of items in it so either generate a bunch of changed files in your working directory or find a large merge commit in the history view that contains a lot of changed files (I've been using the merge commit in this branch: a3d2f0f09)

image

**Comment by AndreiMaga** [comment]
@niik This looks awesome, you went a lot deeper than what the initial issue was, I'm glad you took a swing at this.

**Comment by niik** [comment]
> For the Desktop team: If we plan to support these same key functions on other parts of the app, like the Repo list and Branch list, please let me know. Thanks.

This affects all lists in Desktop but the branches and PR lists are suffering from unrelated issues that make it behave quite wonky on them. Seems to be working decently on the repository list though.

File: app/src/ui/lib/list/selection.ts [hunk 3]
```diff
@@ -140,3 +140,25 @@ export function findNextSelectableRow(
...
+/**
+ * Find the last selectable row in either direction, used
+ * for moving to the first or last selectable row in a list,
+ * i.e. Home/End key navigation.
+ */
+export function findLastSelectableRow(
+  direction: SelectionDirection,
+  rowCount: number,
+  canSelectRow: (row: number) => boolean
+) {
```
Comment (rafeca) [inline app/src/ui/lib/list/selection.ts:153]: This could have been implemented also as something like to take advantage of the other method:

```ts
let row = direction === 'up' ? rowCount - 1 : 0
const traverseDirection = direction === 'up' ? 'down' : 'up'

return findNextSelectableRow(rowCount, {direction: traverseDirection, row, wrap: true }, canSelectRow)
```

Bun I honestly don't know if it's easier to read/understand LOL, so feel free to ignore this 😅

Comment (niik) [reply app/src/ui/lib/list/selection.ts:153]: Ah, clever you! I don't have strong feelings about it but I don't want to bother you with another review so I'm gonna merge as is 😛

**Comment by niik** [comment]
Thank you so much @AndreiMaga :heart:
