### PR TITLE
Fix staged file renamed with changes showing no diff

### LINKED ISSUE #6014: Changes from renamed files are ignored
## Description

Files can simultaneously be renamed and changed, but GitHub Desktop ignores content changes from renamed files.

## Version

* GitHub Desktop: 1.4.3

* Operating system: Windows 10

### Expected Behavior

GitHub Desktop should show content changes.

### Actual Behavior

It ignores any content change.

### PR DESCRIPTION
**Pull request by ssigwart**
- Closes desktop/desktop#6014

## Description
Fixes the case where a staged file is moved and modified. Previously, it would say it was moved with no changes.

### Screenshots

image

### CODE REVIEW

File: app/src/lib/git/status.ts [hunk 1]
```diff
@@ -163,12 +163,23 @@ function convertToAppStatus(
...
+      entry.workingTree === GitStatusEntry.Modified ||
+      (entry.renameOrCopyScore !== undefined && entry.renameOrCopyScore < 100)
+    ) {
+      renameIncludesModifications = true;
+    }
     return {
       kind: AppFileStatusKind.Renamed,
       oldPath,
       submoduleStatus: entry.submoduleStatus,
+      renameIncludesModifications,
```
Comment (tidy-dev) [inline app/src/lib/git/status.ts]:
```suggestion
    return {
      kind: AppFileStatusKind.Renamed,
      oldPath,
      submoduleStatus: entry.submoduleStatus,
      renameIncludesModifications: entry.workingTree === GitStatusEntry.Modified ||
      (entry.renameOrCopyScore !== undefined && entry.renameOrCopyScore < 100),
```

We[ prefer Immutability when possible.](https://github.com/desktop/desktop/blob/development/docs/contributing/engineering-values.md#immutability-is-good)

File: app/src/lib/git/log.ts [hunk 2]
```diff
@@ -70,20 +70,24 @@ function mapStatus(
...
-    return { kind: AppFileStatusKind.Renamed, oldPath, submoduleStatus }
+    const renameIncludesModifications = (status !== "R100");
+    return { kind: AppFileStatusKind.Renamed, oldPath, submoduleStatus, renameIncludesModifications }
   }
 
   // git log -C --name-status will return a CXXX - where XXX is a percentage
   if (status.match(/C[0-9]+/) && oldPath != null) {
-    return { kind: AppFileStatusKind.Copied, oldPath, submoduleStatus }
+    const renameIncludesModifications = false;
+    return { kind: AppFileStatusKind.Copied, oldPath, submoduleStatus, renameIncludesModifications }
```
Comment (tidy-dev) [inline app/src/lib/git/log.ts]: Nit: I think this would be cleaner if we did the assigning on the object 

{
 ... 
 renameIncludesModifications: false
 }

File: app/src/ui/diff/index.tsx [hunk 3]
```diff
@@ -229,11 +231,24 @@ export class Diff extends React.Component<IDiffProps, IDiffState> {
...
+          )
+        }
+        else
+        {
+          return (
+            <div className="panel renamed">
+              The file was renamed but not changed
+            </div>
+          )
+        }
```
Comment (tidy-dev) [inline app/src/ui/diff/index.tsx]:
```suggestion
          return (
            <div className="panel renamed">
              The file was renamed but not changed
            </div>
          )
```

Nit: Unnecessary else statement

**Review by tidy-dev — CHANGES_REQUESTED** [review]
@ssigwart  Thanks for this contribution. I apologize for the long delay in review (small team, pr's are as we can get to them). I understand if you do not want to pick this back up after so much time. But if you do, here is some feedback:

I believe it is fairly non-invasive approach to having better messaging and appears to work as expected.  I have left some code-base stylistic comments. Also, I can tell that if the CI had triggered, the linter would have failed. Thus, to get this PR another review, we will need to bring it up to date with development, address the pr suggestions, and run yarn:lint:fix. At that point, I will do more testing. 

As said above, totally understand if you do not want to pick this back up. If that is the case we will close it in a couple of weeks.

**Comment by ssigwart** [comment]
Thanks, @tidy-dev. I rebased and applied the updates you suggested. The GitHub actions don't run without approval for me, but I ran `yarn lint` and `yarn lint:fix` locally.

**Comment by tidy-dev** [comment]
@ssigwart We have some failing unit test since the status module has changed. Can you address those?

To run unit tests, use `yarn test:unit`.
To only run unit tests for only one of those files, you can run something like `yarn test:unit log` to do the log-test file and `yarn test:unit status` for the status-test file.

Showing four failed unit tests

**Comment by ssigwart** [comment]
@tidy-dev, I fixed them. Thanks for the pointers on how to run the tests that failed.

**Comment by ssigwart** [comment]
@tidy-dev, I noticed that the unit tests ran today and there were some lint errors, so I ran `yarn lint:fix` and pushed a new commit.

**Review by tidy-dev — APPROVED** [review]
Works as expected. Thank you!

**Comment by ssigwart** [comment]
Thanks for reviewing and merging, @tidy-dev!
