### PR TITLE
whenever we refresh the history view, update the list of local-only commits

### LINKED ISSUE #3698: When you sync a repo, "View on GitHub" will need a tab change to be used
### Description

When you sync a repository with "History" open, you will need to alternate the tabs to use "View on GitHub for the recent commits.

### Version

**GitHub Desktop version:** 1.0.11
**OS version:** Windows 10 v1709 c16299.125

### Steps to Reproduce

1. Clone a repository from GitHub
1. Create a commit
1. Select the History tab with that commit
1. Sync the repo
1. Right-click and try to select "View on GitHub"

Repro

**Expected behavior:** The "View on GitHub" option should be available after the sync.

**Actual behavior:** The option is disabled even if the commit is already on GitHub.
Capture

**Reproduces how often:** Every time.

### Logs
[2017-12-29.desktop.production.log](https://github.com/desktop/desktop/files/1593467/2017-12-29.desktop.production.log)

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #3698

The internal state of Desktop uses a list of SHAs to represent the commits on the current branch which are local-only. These are computed in [`GitStore`](https://github.com/desktop/desktop/blob/58de2f3a95de16876f74790de79aba9a81d7b3da/app/src/lib/stores/git-store.ts#L414):

```ts
    let localCommits: ReadonlyArray<Commit> | undefined
    if (branch.upstream) {
      const revRange = `${branch.upstream}..${branch.name}`
      localCommits = await this.performFailableOperation(() =>
        getCommits(this.repository, revRange, CommitBatchSize)
      )
    } else {
      localCommits = await this.performFailableOperation(() =>
        getCommits(this.repository, 'HEAD', CommitBatchSize, [
          '--not',
          '--remotes',
        ])
      )
    }
```

These then flow through props as a list to be computed inside [`CommitList`](https://github.com/desktop/desktop/blob/58de2f3a95de16876f74790de79aba9a81d7b3da/app/src/ui/history/commit-list.tsx#L47):

```ts
    const isLocal = this.props.localCommitSHAs.indexOf(commit.sha) > -1

    return (
      <CommitListItem
        key={commit.sha}
        gitHubRepository={this.props.repository.gitHubRepository}
        isLocal={isLocal}
        commit={commit}
        user={avatarUser}
        emoji={this.props.emoji}
        onRevertCommit={this.props.onRevertCommit}
        onViewCommitOnGitHub={this.props.onViewCommitOnGitHub}
      />
    )
```

We already have a function that gets called whenever the History tab needs to be refreshed, so let's just add this additional work into there.

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -1485,6 +1485,14 @@ export class AppStore {
    * This will be called automatically when appropriate.
    */
   private async refreshHistorySection(repository: Repository): Promise<void> {
+    const gitStore = this.getGitStore(repository)
+    const state = this.getRepositoryState(repository)
+
+    if (state.branchesState.tip.kind === TipState.Valid) {
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/app-store.ts]: This can be shortened by introducing `const tip = state.branches.tip`.

File: app/src/lib/stores/app-store.ts [hunk 2]
```diff
@@ -1485,6 +1485,14 @@ export class AppStore {
...
+      const currentBranch = state.branchesState.tip.branch
+      await gitStore.loadLocalCommits(currentBranch)
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/app-store.ts]: We could then use it here: `await gitStore.loadLocalCommits(tip.branch)`

**Comment by shiftkey** [comment]
:apple:
