### PR TITLE
Log `shell.openExternal` errors

### LINKED ISSUE #8156: Fix `shell.openExternal` calls now that it's an async method
With the upgrade to Electron 5 `shell.openExternal` is now an async method (see https://github.com/electron/electron/pull/16176).

So we want to update the following accordingly... https://github.com/desktop/desktop/blob/e23328a063e3c7702993c41714bdfcaa5eaf3bbe/app/src/main-process/main.ts#L483-L484

As it is now, we prematurely send the 'open-external-result' event. And we won't be alerted if this operation fails, as we're not handling the promise rejection. From what I can tell we're not actually doing anything with `result`, so nothing is breaking due to the fact that its value is now a promise rather than a boolean, as was previously returned from `shell.openExternal`.

To fix this we can either use [`shell.openExternalSync`](https://electronjs.org/docs/api/shell#shellopenexternalsyncurl-options) or await the promise that is now returned from [`shell.openExternal`](https://electronjs.org/docs/api/shell#shellopenexternalurl-options). 

Note that strangely `shell.openExternalSync` returns a `boolean` whereas `shell.openExternal` returns `Promise<void>`. I'm generally in favor of using the async method, unless we rely on the `boolean` return value for subsequent logic in our code.

There are several other places that we use `shell.openExternal` in the code, so we'll want to do a thorough audit and make sure to use the appropriate method in each case.

/cc @vilmibm

### PR DESCRIPTION
**Pull request by kuychaco**
## Overview

This is a follow-on PR to #8220, which had **closed #8156**

## Description

Electron's `shell.openExternal` changed to become async so in order to ensure that errors don't get lost in the async void we need to explicitly catch them.

I'm choosing to log them rather than throw because surfacing the error to the user doesn't add any value. They'll notice that something is wrong by virtue of the fact that their browser didn't open correctly.

The logging will be helpful for us developers when we're debugging what went wrong and save us time identifying the root cause.

## Release notes

Notes: no-notes

### CODE REVIEW

File: app/src/main-process/menu/build-default-menu.ts [hunk 1]
```diff
@@ -425,32 +425,40 @@ export function buildDefaultMenu({
   const submitIssueItem: Electron.MenuItemConstructorOptions = {
     label: __DARWIN__ ? 'Report Issue…' : 'Report issue…',
     click() {
-      shell.openExternal('https://github.com/desktop/desktop/issues/new/choose')
+      shell
+        .openExternal('https://github.com/desktop/desktop/issues/new/choose')
+        .catch(err => log('error', `Call to openExternal failed: '${err}'`))
```
Comment (niik) [inline app/src/main-process/menu/build-default-menu.ts]: It seems this file erroneously imports the `log` method from `log.ts` which shadows the [globally available `log` object](https://github.com/desktop/desktop/blob/284e374294289fc44d45bd115031027b3ce1f136/app/src/lib/globals.d.ts#L100-L168) (installed [here for the main process](https://github.com/desktop/desktop/blob/284e374294289fc44d45bd115031027b3ce1f136/app/src/lib/logging/main/install.ts) and [here for the renderer](https://github.com/desktop/desktop/blob/284e374294289fc44d45bd115031027b3ce1f136/app/src/lib/logging/renderer/install.ts)).

Once you've removed that import you should get access to `log.error` which takes an error message as its first parameter and an optional exception as its second. By passing the exception separately we can globally decide how to format our error messages in the log file.

I'd be looking for something similar to this

```suggestion
        .catch(err => log.error('Failed opening issue creation page', err))
```

File: app/src/main-process/menu/build-default-menu.ts [hunk 2]
```diff
@@ -425,32 +425,40 @@ export function buildDefaultMenu({
...
     label: __DARWIN__ ? 'Show Keyboard Shortcuts' : 'Show keyboard shortcuts',
     click() {
-      shell.openExternal(
-        'https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop'
-      )
+      shell
+        .openExternal(
+          'https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop'
+        )
+        .catch(err => log('error', `Call to openExternal failed: '${err}'`))
```
Comment (mislav) [inline app/src/main-process/menu/build-default-menu.ts]: Nit: since there are multiple `shell.openExternal` calls in this file and each handles errors in an identical way, would we sometimes opt to DRY up these calls by creating an intermediate method to handle errors, or would we rather keep repeat these and treat is as incidental duplication?

```js
const openExternal = (...args) =>
  shell.openExternal(...args).catch(err => log('...'))
```

**Comment by outofambit** [comment]
took a quick pass at this to get it across the line after discussing briefly with @kuychaco on friday. i had misunderstood 

> Electron's `shell.openExternal` changed to become async so in order to ensure that errors don't get lost in the async void we need to explicitly catch them.
