### PR TITLE
Make commit attribution check case-insensitive

### LINKED ISSUE #11691: Commit Attribution Check is Case-Sensitive
### Describe the bug

The "commit misattribution" popup shows even when the email is a different case. 

### Version & OS

2.6.4
Windows 10 Professional

### Steps to reproduce the behavior

1. Change the case of your email in your git config
2. Open GitHub desktop

### Expected behavior

The capitalization of the email is ignored in GitHub desktop as it is on GitHub.

### Actual behavior

The capitalization is not ignored

### Screenshots

image

### Logs

N/A

### Additional context

I've had no issues with commit attribution on GitHub.

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #11691

## Description

This PR makes a change in the way we check if the user's current email in git config is one of the emails registered in their account.

More specifically, this PR makes that check case insensitive. However, it's important to note that this case insensitive check is done only when deciding if the user should be warned about the possibility of unattributed commits, and not in other circumstances.

Thanks to this, if the user had `My.Email@domain.com` registered in their account, they could still choose to use `my.email@domain.com` (all lowercase) without (1) being overridden by `My.Email@domain.com` and (2) without being warned about getting misattributed commits.

Aside from that, this PR also fixes an annoying UI glitch that could happen when the user, while typing a custom email address, if at some point that email address turned into one of the account emails, the textfield would just disappear:

https://user-images.githubusercontent.com/1083228/110106378-e6cbe800-7da9-11eb-9620-93aa133f73ea.mov

### Screenshots

https://user-images.githubusercontent.com/1083228/110106716-4d510600-7daa-11eb-8e42-aed4e600aeba.mov

## Release notes

Notes: [Fixed] Commit attribution warning is not shown for emails with different capitalization.

### CODE REVIEW

**Review by tidy-dev — APPROVED** [review]
✨

**Comment by Nenginyo** [comment]
> Closes #11691
> 
> ## Description
> This PR makes a change in the way we check if the user's current email in git config is one of the emails registered in their account.
> 
> More specifically, this PR makes that check case insensitive. However, it's important to note that this case insensitive check is done only when deciding if the user should be warned about the possibility of unattributed commits, and not in other circumstances.
> 
> Thanks to this, if the user had `My.Email@domain.com` registered in their account, they could still choose to use `my.email@domain.com` (all lowercase) without (1) being overridden by `My.Email@domain.com` and (2) without being warned about getting misattributed commits.
> 
> Aside from that, this PR also fixes an annoying UI glitch that could happen when the user, while typing a custom email address, if at some point that email address turned into one of the account emails, the textfield would just disappear:
> 
>  git-email-glitch.mov 
> ### Screenshots
>  git-config-case-insensitive.mov 
> ## Release notes
> Notes: [Fixed] Commit attribution warning is not shown for emails with different capitalization.

**Comment by Nenginyo** [comment]
https://github.com/github/docs.git

**Comment by kevingigi12235** [comment]
> https://github.com/github/docs.git

> [](url)

**Comment by twocountriestrus** [comment]
Gracias

File: app/src/lib/is-account-email.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
+/**
+ * Checks if a given email address is included (case-insensitively) among the
```
Comment (savariya28) [inline app/src/lib/is-account-email.ts:2]: $75000

**Comment by savariya28** [comment]
- [ ] Jay here

**Review by savariya28 — COMMENTED** [review]
$75000
