### PR TITLE
Discard changes with retry on error moving to recycling bin

### LINKED ISSUE #13888: Application hangs when trying to discard changes
### Describe the bug
When trying to discard changes, the application becomes unresponsive.

### Version & OS
2.9.7 (x64)
Windows 10 21H2 (19044.1526)

### Steps to reproduce the behavior
1. Change a file in any repository
2. Open the Changes tab
3. Right click on the applicable file
4. Click _Discard changes_ in the context menu
5. Click _Discard changes_ in the confirmation dialog

### Expected behavior
* The changes are discarded

### Actual behavior
* A spinner icon appears in the dialog title bar
* The whole application becomes unresponsive
* Nothing happens when clicking Discard changes or Cancel
* The changes are not discarded

### Screenshots
github-discard

### Logs
Not much relevant content in the logs. This is the only line written:
```log
2022-02-15T11:32:53.506Z - info: [ui] No submodules found. Skipping "git submodule status"
```

### Additional context
* I have waited about 10 minutes for the operation to finish
* The only solution is to terminate the application from Task Manager
* I have checked that there are no other processes using the file
* I have tried to discard multiple file types (.js, .html, .json)
* I have tried multiple repositories. All repositories are non-GitHub.
* I have tried deleting _%AppData%\GitHub Desktop_ to start "fresh" 
* Downgrading to 2.9.6 fixes the problem
* Not directly related, but the application seems slower to start in 2.9.7

I was unsure whether I should open a new issue or comment on #13433 or #13661, but those appear closed by #13436.

### PR DESCRIPTION
**Pull request by tidy-dev**
Closes #13888

## Description
A possible solution to #13888 see #13899 for more details. This allows a user to retry discarding changes if it fails due to inability to move items to the recycling bin. Prior to 2.9.7, Desktop silently does this making those changes unknowingly unrecoverable. After Electron 16 upgrade, we must at least catch the error (or else bug seen in #13888). Another solution would be to just silent capture it, but this is misleading since our warning popup says you can recover changes in the recycling bin. 

### Screenshots

https://user-images.githubusercontent.com/75402236/154281170-9db4eee9-eee3-43a6-85dc-ef3ca84d9084.mov

## Release notes
Notes: [Fixed] App does not hang when discarding changes in some scenarios.

### CODE REVIEW

File: app/src/lib/stores/git-store.ts [hunk 1]
```diff
@@ -1459,13 +1460,21 @@ export class GitStore extends BaseStore {
...
         // as many animation frames as it needs to.
-        await this.shell.moveItemToTrash(
-          Path.resolve(this.repository.path, file.path)
-        )
+        try {
+          await this.shell.moveItemToTrash(
+            Path.resolve(this.repository.path, file.path)
+          )
+        } catch (e) {
+          throw new ErrorWithMetadata(e, {})
```
Comment (tidy-dev) [inline app/src/lib/stores/git-store.ts]: Using  `new ErrorWithMetadata(e, {})` as hacky way to distinguish an error thrown by the `moveItemToTrash` method somewhere else in this function...  needs more thought into this approach.... Either moving the `moveItemToTrash` up to the app-store (but then it's not in that queue) and handling the error there.. or some sort of direct return type indicating this specific failure.

File: app/src/ui/app-error.tsx [hunk 2]
```diff
@@ -239,6 +248,28 @@ export class AppError extends React.Component<IAppErrorProps, IAppErrorState> {
     )
   }
 
+  private renderRetryFooter(error: Error) {
```
Comment (tidy-dev) [inline app/src/ui/app-error.tsx]: Was sort of surprised we didn't already have a means to have a retry-able error without making a custom error dialog. Seems like the retry clone stuff here could have been more generic.

File: app/src/lib/stores/git-store.ts (hunk 1 above)
Comment (tidy-dev) [reply app/src/lib/stores/git-store.ts]: (Ignore from first stab)

File: app/src/ui/app-error.tsx (hunk 2 above)
Comment (tidy-dev) [reply app/src/ui/app-error.tsx]: (ignore from first stab)

File: app/src/ui/discard-changes/discard-changes-retry-dialog.tsx [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+  }
+
+  private renderFooter() {
+    return (
+      <DialogFooter>
+        <OkCancelButtonGroup
+          okButtonText={
+            __DARWIN__
+              ? 'Retry Discard Changes and Continue'
+              : 'Retry discard changes and continue'
```
Comment (sergiou87) [inline app/src/ui/discard-changes/discard-changes-retry-dialog.tsx]: I think I prefer more explicit wording in these actions, something like: 'Discard Changes Forever' or 'Discard Changes Anyway' and 'Cancel'  instead of 'Close'.

File: app/src/ui/discard-changes/discard-changes-retry-dialog.tsx [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+          }
+          okButtonTitle={`This will discard changes and they will be unrecoverable.`}
+          cancelButtonText="Close"
```
Comment (sergiou87) [inline app/src/ui/discard-changes/discard-changes-retry-dialog.tsx]: We should add a `destructive={true}` attribute here probably 🤔 
```suggestion
          cancelButtonText="Close"
          destructive={true}
```

**Review by sergiou87 — CHANGES_REQUESTED** [review]
As mentioned in my comment, I'd rather have a more explicit wording in the buttons (especially on the destructive one). Also, it seems like users with these Recycle Bin settings will always get this new popup, right? Shouldn't we add a "Don't bother me again" kind of checkbox for it?

**Comment by palhal** [comment]
Sorry to interfere, but did anyone complain about the lack of warning in 2.9.6? I understand that the error was silently ignored, but wasn't that a good thing? If I choose to disable the recycle bin, it's because I don't care about recovery. I just want the changes gone, without additional interactions.

Another approach could be to rephrase the initial text with something like "Changes can _usually_ be restored by ..." or "Unless the recycle bin is disabled, changes can be restored by ...". (I know that none of them are optimal.)

Anyway thanks for a very quick follow up on this!

**Comment by tidy-dev** [comment]
@palhal Thank you for the suggestions! We are try our best to help users not step into painful situations easily. Here that would be accidentally permanently discarding a change. Thus, we want to make sure the user is aware of what going forwards means. That said, I am sure this popup is annoying for users who have intentionally set their system settings this way. To help with that, I have just added the "Don't show this again" check box so users can choose not to receive this warning again.

File: app/src/ui/discard-changes/discard-changes-retry-dialog.tsx [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+          okButtonText={
+            __DARWIN__
+              ? 'Permanently Discard Changes and Continue'
+              : 'Permanently discard changes and continue'
+          }
+          okButtonTitle={`This will discard changes and they will be unrecoverable.`}
+          cancelButtonText="Cancel"
+          destructive={true}
+        />
+      </DialogFooter>
```
Comment (sergiou87) [inline app/src/ui/discard-changes/discard-changes-retry-dialog.tsx]: I find that button too verbose 😅  Can we at least remove the `and continue` part?
image

**Review by sergiou87 — COMMENTED** [review]
Code looks great, I tested it and worked as expected! Only have one suggestion/comment about the retry/confirmation dialog, which doesn't look great with that button title, IMHO 😅

File: app/src/ui/discard-changes/discard-changes-retry-dialog.tsx (hunk 5 above)
Comment (tidy-dev) [reply app/src/ui/discard-changes/discard-changes-retry-dialog.tsx]: done!

**Comment by palhal** [comment]
@tidy-dev I get your point. I thought I could save you and the code reviewers some time 😄

By the way, I think the message _These changes will be unrecoverable from the {TrashNameLabel}_ is a bit verbose. If the changes are unrecoverable, I guess it doesn't matter from where?

**Review by sergiou87 — APPROVED** [review]
:shipit:
