### PR TITLE
Fix PRs appearing to be created in the future

### LINKED ISSUE #14238: PR relative dates are in the future
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

Relative dates on the PR tab are in the future. Instead of `in x days` and `tomorrow` it should `x days ago` and `yesterday`.

### Release version

2.9.12

### Operating system

Windows 10

### Steps to reproduce the behavior

_No response_

### Log files

_No response_

### Screenshots

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niik**
Closes #14238

## Description

Fixes the issue with pull requests, and one log message (skipping background fetch), being shown as happening in the future due to me mistakenly switching the sign order.

## Release notes

Notes: [Fixed] Pull requests adhere to temporal laws again 

(we should come up with a better changelog entry)

### CODE REVIEW

File: app/src/lib/format-relative.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ const getRelativeFormatter = mem(
 export function formatRelative(ms: number) {
   const formatter = getRelativeFormatter('en-US', { numeric: 'auto' })
 
-  const sign = ms < 0 ? 1 : -1
+  const sign = ms < 0 ? -1 : 0
```
Comment (tidy-dev) [inline app/src/lib/format-relative.ts]: Setting the sign here to 0 seems strange to me.. but I guess that is to follow the assumption that we should not have future dates.

**Review by tidy-dev — DISMISSED** [review]
✨  Appears to work as expected and spot checked a couple other places. 

Also, that release note is awesome. 🚀

File: app/src/lib/format-relative.ts (hunk 1 above)
Comment (niik) [reply app/src/lib/format-relative.ts]: No, it's just straight up strange. As in wrong. As in attempting to squeeze in a fix on a Friday afternoon is a terrible idea. I'll fix it.

**Review by sergiou87 — APPROVED** [review]

**Review by tidy-dev — APPROVED** [review]
