### PR TITLE
autocomplete ignores mouse down events

### LINKED ISSUE #2674: Selecting Issue in Summary doesn't autofill issue number
### Description

When you type #, GitHub Desktop provides you with a list of issues.   But if you select one of the issues, it doesn't populate the number for you.  I just have to use it as a reference and type the number myself.

### Version

**GitHub Desktop version:** 0.8.1
**OS version:** OSX 10.12.6

### Steps to Reproduce

1. Start typing a summary and type #.
1. Click on one of the issues
1. The summary does not populate the issue number

**Expected behavior:** I expect that when I click on the issue, it should populate the summary with the issue number.

**Actual behavior:** Nothing happens when you click the issue.

**Reproduces how often:** 100%

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2674

The core of this problem is that the autocomplete list ensures an item is always selected (the first item on initial render, then whichever item is under the mouse cursor (this is `this.props.selectOnHover`), and `onSelectionChanged` won't be raised when it considers the list item already selected.

I landed on this fix because I didn't want to change the internal behaviour of `List` this close to 1.0 and re-test everywhere, and stripping back the `selectOnHover` behaviour felt off.

### CODE REVIEW

**Comment by joshaber** [comment]
🏷 ❓

**Comment by shiftkey** [comment]
🏷 ❗️

File: app/src/ui/list.tsx [hunk 1]
```diff
@@ -136,6 +135,13 @@ interface IListProps {
   readonly onRowKeyDown?: (row: number, event: React.KeyboardEvent<any>) => void
 
   /**
+   * A handler called whenever a mouse down event is received on the
+   * row container element. Unlike onSelectionChanged, this is raised
+   * for every mouse down event, whether the row is selected or not.
+   */
+  readonly onRowMouseDown?: (row: number, event: React.MouseEvent<any>) => void
```
Comment (joshaber) [inline app/src/ui/list.tsx]: Could we use https://github.com/desktop/desktop/blob/0c4a86ac4bad7b458aaad028e2420354a2b44137/app/src/ui/list.tsx#L665 instead of adding this? Entirely possible there's some nuance I've missed here.

Comment (shiftkey) [reply app/src/ui/list.tsx]: That's already wired up to insert a completion, but the underlying DOM event wasn't firing for me for this case and I couldn't understand why that's (not) happening.

Comment (joshaber) [reply app/src/ui/list.tsx]: /shrug
