### PR TITLE
ignore handled Enter event in FocusContainer keydown event handler

### LINKED ISSUE #5344: keyboard navigation and enter will execute menu item twice
## Description
When I use the keyboard to open menu and select 'Open in Git Bash', two instances of Git Bash is opened.

## Version

* GitHub Desktop:
1.3.2

* Operating system:
Microsoft Windows [Version 10.0.17134.167]

## Steps to Reproduce
1. Press `Alt`
2. Press `R`
2.1. Opens the Repository menu
3. Use arrow down to select 'Open in Git Bash'
4. Press `Enter`

### Expected Behavior
One Git Bash instance should be opened.

### Actual Behavior
Two instances of Git Bash is opened.

## Additional Information

I've added notes to the following screenshot gif files.

Here is the reproduce gif.

spawn-issue

Here is the expected behavior when I use the mouse.

spawn-issue-mouse

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

**Closes #5344**

The easiest way to test this is to use the "Open in Shell" menu item on Windows **using only keyboard navigation** - you should seeing two instances of the desired shell launch, which can be traced back to this event handling.

## Description

I've been wrestling with this one for a while, but after plodding through the event handlers yet again I think I've stumbled upon the best solution for this.

First, I first need to walk through the bug itself. Have a read of [event bubbling](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture) as that's relevant to the behaviour we're currently seeing.

 1. user uses keyboard navigation to expand menu and select an menu item to execute
 2. user presses <kbd>Enter</kbd>

3. [`List.onRowKeyDown`](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/lib/list/list.tsx#L401) fires - this is the event handler attached to each `ListRow` component inside the `Grid`
     - this invokes [`MenuPane.onRowKeyDown`](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/app-menu/menu-pane.tsx#L220) as it's the active row
     - which then invokes [`AppMenu.onItemKeyDown`](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/app-menu/app-menu.tsx#L168)
     - this doesn't handle the event 🙅‍♂️ 
     - back in `List.onRowKeyDown` we check that <kbd>Enter</kbd> [has not been handled](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/lib/list/list.tsx#L412-L418) and `toggleSelection` fires
     - `List.toggleSelection` fires the `onRowClick` prop for `List`
     - ... which runs `MenuPane.onRowClick` 
     - ... which runs `AppMenu.onItemClicked`
     - which performs the IPC call to execute the menu item :ok:
 
4. [`List.onKeyDown`](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/lib/list/list.tsx#L421) fires - this is the click handler for the `FocusContainer` that wraps the `Grid`
     - this checks for <kbd>Enter</kbd> or the space key and runs `toggleSelection` again
     - `List.toggleSelection` fires the `onRowClick` prop for `List`
     - ... which runs `MenuPane.onRowClick` 
     - ... which runs `AppMenu.onItemClicked`
     - which performs the IPC call to execute the menu item again  ❌ 

 5. finally [`List.handleKeyDown`](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/lib/list/list.tsx#L363) fires - this is the click handler for the `div` which hosts the contents
     - this again invokes [`MenuPane.onRowKeyDown`](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/app-menu/menu-pane.tsx#L220) because the row is considered "selected" due to the hover state
     - which again invokes [`AppMenu.onItemKeyDown`](https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/app-menu/app-menu.tsx#L168)
     - which still doesn't handle the event 🙅‍♂️  

The MDN docs about [event bubbling](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture) talk about using `event.stopPropagation()` to prevent the parent elements from handling events, but I feel this is heavy-handed and goes against the way we've been designing these components.

Instead I think the fix here is ensure that `List.onKeyDown` event handler ignores the event if `defaultPrevented` has been set. We do this inside `List.handleKeyDown` and `List.onRowKeyDown`, so I think this was just an oversight whenever we were making changes in here.

https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/lib/list/list.tsx#L370-L374

https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/lib/list/list.tsx#L412-L418

Of course, this event handler was implemented as part of multi-select support in #4188 so I want to confirm there are no side effects from this before we can close it out.

 - [x] test multi-select in Changes list with keyboard navigation only
 
## Release notes

Notes: fixed keyboard event handling in app menu on Windows

### CODE REVIEW

**Comment by shiftkey** [comment]
In my writeup of this issue I got _so confused_ about these related event handlers (even after adding logging and careful reading) that I've added a4a354f97c8106239ffbbe939be1c7e6f7b0100e to this PR to rename them to try and avoid future confusion.

File: app/src/ui/lib/list/list.tsx [hunk 1]
```diff
@@ -398,7 +398,7 @@ export class List extends React.Component<IListProps, IListState> {
     }
   }
 
-  private onRowKeyDown = (
+  private handleRowKeyDown = (
```
Comment (niik) [inline app/src/ui/lib/list/list.tsx]:
```suggestion
  private onRowKeyDown = (
```

File: app/src/ui/lib/list/list.tsx [hunk 2]
```diff
@@ -418,8 +418,11 @@ export class List extends React.Component<IListProps, IListState> {
     }
   }
 
-  private onKeyDown = (event: React.KeyboardEvent<any>) => {
-    if (event.key === 'Enter' || event.key === ' ') {
+  private handleFocusContainerKeyDown = (event: React.KeyboardEvent<any>) => {
```
Comment (niik) [inline app/src/ui/lib/list/list.tsx]:
```suggestion
  private onFocusContainerKeyDown = (event: React.KeyboardEvent<any>) => {
```

File: app/src/ui/lib/list/list.tsx [hunk 3]
```diff
@@ -633,7 +636,7 @@ export class List extends React.Component<IListProps, IListState> {
         selected={selected}
         ariaMode={this.props.ariaMode}
         onRowClick={this.onRowClick}
-        onRowKeyDown={this.onRowKeyDown}
+        onRowKeyDown={this.handleRowKeyDown}
```
Comment (niik) [inline app/src/ui/lib/list/list.tsx]:
```suggestion
        onRowKeyDown={this.onRowKeyDown}
```

File: app/src/ui/lib/list/list.tsx [hunk 4]
```diff
@@ -739,7 +742,7 @@ export class List extends React.Component<IListProps, IListState> {
     return (
       <FocusContainer
         className="list-focus-container"
-        onKeyDown={this.onKeyDown}
+        onKeyDown={this.handleFocusContainerKeyDown}
```
Comment (niik) [inline app/src/ui/lib/list/list.tsx]:
```suggestion
        onKeyDown={this.onFocusContainerKeyDown}
```

**Comment by shiftkey** [comment]
@niik gonna also push a commit to tidy up `handleKeyDown` while I'm in here:

https://github.com/desktop/desktop/blob/f4efc0af4ef610f9abcc91403aa8f5547282fd0f/app/src/ui/lib/list/list.tsx#L681

**Comment by shiftkey** [comment]
:apple:
