### PR TITLE
Checkout default branch when branch is deleted during a compare

### LINKED ISSUE #5256: Can't View History After Deleting Branch While in "Behind" / "Ahead" View
## Description
If you are in the comparison view between branches ("Behind" / "Ahead") and you delete the last branch besides the master, you will be stuck in "Behind" / "Ahead" view.  You can't get back to the history of master unless you go to the menu option `View > Show History`.  Clicking the history button will not bring it back.

## Version
* GitHub Desktop: v1.2.6
* Operating system: macOS 10.13.6

## Steps to Reproduce
1. Use a repo that has only a master branch
2.  Create new branch and make sure you are currently in that branch
3. Change to the history tab, select `select branch to compare`, and pick the `master`
4. Delete new branch and find yourself stuck in that view.  You will notice that the branch name inside the compare field is still stuck on `master` and that it is greyed out.   You are not able to see the commit history until you use the menu option `View > Show History`.

### Expected Behavior
I expected the history button to bring me back to the history or for it to show up automatically after the branch was deleted, since there was no branch to compare to now that the new one was deleted.

### Actual Behavior
I am stuck in the "Behind" / "Ahead" view

history bug

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes #5256

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -866,29 +866,28 @@ export class AppStore extends TypedBaseStore<IAppState> {
...
+        return
+      }
 
-        this.updateOrSelectFirstCommit(repository, commits)
+      this.updateCompareState(repository, () => ({
+        formState: {
+          kind: ComparisonView.None,
+        },
+        commitSHAs: commits,
+        filterText: '',
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/app-store.ts]: These two lines are the only real change. Everything else is just cleanup.

File: app/src/ui/delete-branch/delete-branch-dialog.tsx [hunk 2]
```diff
@@ -94,12 +95,17 @@ export class DeleteBranch extends React.Component<
...
-      this.state.includeRemoteBranch
-    )
+  private deleteBranch = async () => {
+    await Promise.all([
+      this.props.dispatcher.deleteBranch(
+        this.props.repository,
+        this.props.branch,
+        this.state.includeRemoteBranch
+      ),
+      this.props.dispatcher.executeCompare(this.props.repository, {
```
Comment (shiftkey) [inline app/src/ui/delete-branch/delete-branch-dialog.tsx]: This seems really unrelated to the delete branch workflow - can we add a comment here indicating why this is important?

**Comment by iAmWillShepherd** [comment]
💯
