### PR TITLE
line endings are hard, lets go shopping

### LINKED ISSUE #3514: "Ignore" context-menu option incorrectly adds carriage return to .gitignore
### Description

When I select a file to ignore from the list of modified files, and then choose "Ignore" from the context menu, the filename is appended to `.gitignore` as desired—but incorrectly suffixed with a `\r` (`^M`).

### Version

**GitHub Desktop version:** 1.0.10
**OS version:** Mac OS X El Capitan, 10.11.6 (15G17023)

### Steps to Reproduce

1. Modify a file in the current repository.
1. Select file in "Changes"; choose "Ignore" from context menu.
1. Open .gitignore with text editor.

**Expected behavior:** Filename of ignored file added to .gitignore, suffixed with `\n`.
**Actual behavior:** Filename of ignored file added to .gitignore, suffixed with `\r\n`.
**Reproduces how often:** Always?

### Logs

[2017-12-06.desktop.production.log](https://github.com/desktop/desktop/files/1535093/2017-12-06.desktop.production.log)

#### Additional Information

A suitable setting of `core.autocrlf` will ensure that the carriage return is not actually committed, but it should not have been added in the first place.

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #3514

### CODE REVIEW

File: app/src/lib/stores/repository-settings-store.ts [hunk 1]
```diff
@@ -110,6 +110,12 @@ async function formatGitIgnoreContents(
       return
     }
 
+    // fallback to Git default behaviour
```
Comment (iAmWillShepherd) [inline app/src/lib/stores/repository-settings-store.ts]: I think this should be a part of an else block since it's very much related to the previous condition.

File: app/test/unit/repository-settings-store-test.ts [hunk 2]
```diff
@@ -82,4 +76,34 @@ describe('RepositorySettingsStore', () => {
...
+
+      // do not do any conversion of line endings when committing
+      await GitProcess.exec(
+        ['config', '--local', 'core.autocrlf', 'input'],
+        repo.path
+      )
+
+      const path = repo.path
+
+      await sut.saveGitIgnore('node_modules')
```
Comment (iAmWillShepherd) [inline app/test/unit/repository-settings-store-test.ts]: I don't think we need this line.

Comment (iAmWillShepherd) [reply app/test/unit/repository-settings-store-test.ts]: Nvm, looks like this is being used to easily add a file to the repo.

**Comment by shiftkey** [comment]
:apple:
