### PR TITLE
Fixed recent branch renaming

### LINKED ISSUE #6155: Renaming a branch removes it from Recent Branch category
If a branch is renamed then it should not be removed from the Recent Branch category in the branch list.

screen shot 2018-11-09 at 2 29 54 pm

Repro:
- Select any branch but default, that is in the Recent branch category
- Rename it
- The branch is pushed down into the Other category, sometimes out of sight if there are a lot of branches

Expected result: branch remains in Recent Branches category with the new name

1.5.0-beta5, mac

### PR DESCRIPTION
**Pull request by gnehcc**
## Overview

**Closes #6155**

## Description

- Fixed issue: renamed branch's been removed from recent branches category

### CODE REVIEW

**Comment by outofambit** [comment]
hi @gnehcc! thanks for opening a fix for this issue. can i mark this ready for review?

**Comment by gnehcc** [comment]
Just made a quick fix for style check, @outofambit please help mark this pr ready for review, cheers.

**Comment by tierninho** [comment]
Tested the UI and LGTM!

**Comment by agisilaos** [comment]
Hello @gnehcc since this is a UI change can you please attach a before/after photo or a gif so we can check out how it looks like? It would be much easier for the reviewer to get a glimpse of the UI change without building the project and running the app locally. Thanks.

**Comment by gnehcc** [comment]
Added screenshots

- before
before

- after
after

File: app/src/lib/git/reflog.ts [hunk 1]
```diff
@@ -9,7 +9,10 @@ export async function getRecentBranches(
   // "git reflog show" is just an alias for "git log -g --abbrev-commit --pretty=oneline"
   // but by using log we can give it a max number which should prevent us from balling out
   // of control when there's ginormous reflogs around (as in e.g. github/github).
-  const regex = new RegExp(/.*? checkout: moving from .*? to (.*?)$/i)
+  const regex = new RegExp(
+    /.*? (renamed|checkout)(?:: moving from|\s*) (?:refs\/heads\/|\s*)(.*?) to (?:refs\/heads\/|\s*)(.*?)$/i
```
Comment (iAmWillShepherd) [inline app/src/lib/git/reflog.ts]: This expression can be simplified a bit.
```suggestion
   /.*?\srefs\/heads\/(.*?)\sto\srefs\/heads\/(.*?)$/i
```

If the `\s` don't read well, they can be substituted for literal whitespace characters, but that's really a matter of personal style.

File: app/src/lib/git/reflog.ts [hunk 2]
```diff
@@ -31,14 +34,26 @@ export async function getRecentBranches(
...
+  // exclude master from recent branches
+  const excludedNames = new Set<String>(['master'])
+
   for (const line of lines) {
     const result = regex.exec(line)
-    if (result && result.length === 2) {
-      const branchName = result[1]
-      names.add(branchName)
+    if (result && result.length === 4) {
+      const operationType = result[1]
```
Comment (iAmWillShepherd) [inline app/src/lib/git/reflog.ts]: This won't be necessary if the regex above is changed. If there is a match, it is necessarily a branch rename.

File: app/src/lib/git/reflog.ts [hunk 3]
```diff
@@ -31,14 +34,26 @@ export async function getRecentBranches(
...
+      const excludeBranchName = result[2]
+      const branchName = result[3]
+
+      if (operationType === 'renamed') {
```
Comment (iAmWillShepherd) [inline app/src/lib/git/reflog.ts]: This condition would also be unnecessary with the suggested changes. We'd want to keep the addition of `excludeBranchName` to the set.

**Comment by iAmWillShepherd** [comment]
One thing I noticed is that when the branch is renamed, the icon flashes from selected to the branch icon for a split second. I'm not sure how big of a deal this is, so hoping @desktop/product can advise.

File: app/src/lib/git/reflog.ts (hunk 1 above)
Comment (gnehcc) [reply app/src/lib/git/reflog.ts]: @iAmWillShepherd  thanks for the code review.
actually we need both renamed and new checkout (created) branches at the same time, otherwise, the recent branch list will not be complete and there will be only renamed branches under the category

Comment (iAmWillShepherd) [reply app/src/lib/git/reflog.ts]: Just tested app with `/.*?(renamed|checkout) refs\/heads\/(.*?) to refs\/heads\/(.*?)$/i` and seems to work OK (I ended up subbing `\s` for literal whitespace).

**Comment by billygriffin** [comment]
I'd also be fine with doing that in a separate PR.

**Comment by iAmWillShepherd** [comment]
> I'd also be fine with doing that in a separate PR.

I'd appreciate a separate PR. Those changes may not be straight-forward and this PR shouldn't be held up over a minor visual issue.

I created a tracking issue: https://github.com/desktop/desktop/issues/6320
@gnehcc it's yours if you want it, but don't feel pressured to take it on if you don't want to. We're grateful for what you've done in this PR 🥇
