### PR TITLE
review unit tests and make config setup more explicit

### LINKED ISSUE #6924: unable to run unit tests locally when pull.rebase is set to true in global gitconfig
## Description

I've been working on the rebase flows and it turns out that some tests rely on the defaults for `pull.rebase` being unset. This is annoying because I want to test things with `pull.rebase` enabled and I'm sick of having to unset and then set this again in config. 

## Version

* GitHub Desktop: 1cf334bc304e0a361b3172df0f5884e7beb53ffc
* Operating system: macOS

## Steps to Reproduce
1. `git config --global pull.rebase true`
2. `yarn` to ensure dependencies are up to date
2. `yarn test:unit` to run all Git tests

### Expected Behavior

No errors reported.

### Actual Behavior

```
...

Summary of all failing tests
FAIL test/unit/git/pull/only-behind-test.ts (10.885s)
  ● git/pull › only behind tracking branch › with pull.ff=false set in config › creates a merge commit

    expect(received).toHaveLength(length)

    Expected value to have length:
      2
    Received:
      ["20f77e80666cbe45ac2e20dc4748358aad927fd1"]
    received.length:
      1

      109 |       it('creates a merge commit', async () => {
      110 |         expect(newTip.sha).not.toBe(previousTip.sha)
    > 111 |         expect(newTip.parentSHAs).toHaveLength(2)
          |                                   ^
      112 |       })
      113 |
      114 |       it('is different from remote branch', async () => {

      at Object.it (test/unit/git/pull/only-behind-test.ts:111:35)

  ● git/pull › only behind tracking branch › with pull.ff=false set in config › is different from remote branch

    expect(received).not.toBe(expected) // Object.is equality

    Expected: "ec5268a042195b6f8c76fbaeb4cb7d75a8963073"
    Received: "ec5268a042195b6f8c76fbaeb4cb7d75a8963073"

      114 |       it('is different from remote branch', async () => {
      115 |         const remoteCommit = await getRefOrError(repository, remoteBranch)
    > 116 |         expect(remoteCommit.sha).not.toBe(newTip.sha)
          |                                      ^
      117 |       })
      118 |
      119 |       it('is now ahead of tracking branch', async () => {

      at Object.it (test/unit/git/pull/only-behind-test.ts:116:38)

  ● git/pull › only behind tracking branch › with pull.ff=false set in config › is now ahead of tracking branch

    expect(received).toEqual(expected)

    Expected value to equal:
      {"ahead": 1, "behind": 0}
    Received:
      {"ahead": 0, "behind": 0}

    Difference:

    - Expected
    + Received

      Object {
    -   "ahead": 1,
    +   "ahead": 0,
        "behind": 0,
      }

      121 |
      122 |         const aheadBehind = await getAheadBehind(repository, range)
    > 123 |         expect(aheadBehind).toEqual({
          |                             ^
      124 |           ahead: 1,
      125 |           behind: 0,
      126 |         })

      at Object.it (test/unit/git/pull/only-behind-test.ts:123:29)

FAIL test/unit/git/pull/ahead-and-behind-test.ts (12.057s)
  ● git/pull › ahead and behind of tracking branch › by default › creates a merge commit

    expect(received).toHaveLength(length)

    Expected value to have length:
      2
    Received:
      ["336ab75af8ff09ad6106db3ce5e57eeb1367f91e"]
    received.length:
      1

      71 |
      72 |         expect(newTip.sha).not.toBe(previousTip.sha)
    > 73 |         expect(newTip.parentSHAs).toHaveLength(2)
         |                                   ^
      74 |       })
      75 |
      76 |       it('is different from remote branch', async () => {

      at Object.it (test/unit/git/pull/ahead-and-behind-test.ts:73:35)

  ● git/pull › ahead and behind of tracking branch › by default › is ahead of tracking branch

    expect(received).toEqual(expected)

    Expected value to equal:
      {"ahead": 2, "behind": 0}
    Received:
      {"ahead": 1, "behind": 0}

    Difference:

    - Expected
    + Received

      Object {
    -   "ahead": 2,
    +   "ahead": 1,
        "behind": 0,
      }

      86 |
      87 |         const aheadBehind = await getAheadBehind(repository, range)
    > 88 |         expect(aheadBehind).toEqual({
         |                             ^
      89 |           ahead: 2,
      90 |           behind: 0,
      91 |         })

      at Object.it (test/unit/git/pull/ahead-and-behind-test.ts:88:29)

  ● git/pull › ahead and behind of tracking branch › with pull.ff=false set in config › creates a merge commit

    expect(received).toHaveLength(length)

    Expected value to have length:
      2
    Received:
      ["b2237737d9f43ef47dd3f9582a8d3389fc1e39b5"]
    received.length:
      1

      112 |       it('creates a merge commit', async () => {
      113 |         expect(newTip.sha).not.toBe(previousTip.sha)
    > 114 |         expect(newTip.parentSHAs).toHaveLength(2)
          |                                   ^
      115 |       })
      116 |
      117 |       it('is ahead of tracking branch', async () => {

      at Object.it (test/unit/git/pull/ahead-and-behind-test.ts:114:35)

  ● git/pull › ahead and behind of tracking branch › with pull.ff=false set in config › is ahead of tracking branch

    expect(received).toEqual(expected)

    Expected value to equal:
      {"ahead": 2, "behind": 0}
    Received:
      {"ahead": 1, "behind": 0}

    Difference:

    - Expected
    + Received

      Object {
    -   "ahead": 2,
    +   "ahead": 1,
        "behind": 0,
      }

      122 |
      123 |         const aheadBehind = await getAheadBehind(repository, range)
    > 124 |         expect(aheadBehind).toEqual({
          |                             ^
      125 |           ahead: 2,
      126 |           behind: 0,
      127 |         })

      at Object.it (test/unit/git/pull/ahead-and-behind-test.ts:124:29)


Test Suites: 2 failed, 83 passed, 85 total
Tests:       7 failed, 3 skipped, 719 passed, 729 total
Snapshots:   0 total
Time:        16.344s
```

## Additional Information

N/A

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

**Closes #6924**

## Description

```shellsession
$ git config --global pull.rebase
true
$ yarn test:unit
yarn run v1.13.0
$ cross-env ELECTRON_RUN_AS_NODE=1 ./node_modules/.bin/electron ./node_modules/jest/bin/jest --detectOpenHandles --silent --config ./app/jest.unit.config.js
...

Test Suites: 85 passed, 85 total
Tests:       3 skipped, 724 passed, 727 total
Snapshots:   0 total
Time:        14.635s
✨  Done in 15.57s.
```

And the opposite:

```shellsession
$ git config --global pull.rebase
false
$ yarn test:unit                                                                                                                                            
yarn run v1.13.0
$ cross-env ELECTRON_RUN_AS_NODE=1 ./node_modules/.bin/electron ./node_modules/jest/bin/jest --detectOpenHandles --silent --config ./app/jest.unit.config.js
...

Test Suites: 85 passed, 85 total
Tests:       3 skipped, 724 passed, 727 total
Snapshots:   0 total
Time:        14.865s
✨  Done in 15.64s.
```

## Release notes

Notes: no-notes

### CODE REVIEW

**Comment by shiftkey** [comment]
> do you think it's worth taking the time to build some sort of default config to be used in our testing environment instead of being vulnerable to the underlying system's settings?

I gather you're thinking of something like this?

https://github.com/desktop/desktop/blob/f32909cfbf099d720f6ac3fe546cca29ba58ffa8/app/test/unit/git/config-test.ts#L38-L55

I worry that using a pre-canned config with tests would prevent us from catching issues with config set at the  `system` level (set by the Git distribution, and can differ by OS) or `global` level by users that Desktop should handle. 

I think in this case what I should have done was ensure the local config for a repository is set correctly for what is being tested (which overrides whatever may be set globally). That's the approach I continue to recommend, particularly with complex areas with plenty of config options like `git pull`.

These tests were there to help me wrap my head around the current pull behaviour based on expected config values as I dove into "pull with rebase" and seeing them fail now was a good chance to revisit them and question what value they _actually_ had to the feature. I worry that abstracting away the global config away will not give us a chance to identify and re-evaluate our tests as things evolve.

We also don't have an easy way to inject the config for each test (`getGlobalConfigValue` was important to get under test otherwise we'd be overwriting the user's config), and I worry this might add complexity to the overall Git API surface.

**Comment by outofambit** [comment]
@shiftkey I'm not sure how the code snippet above relates to the question?

I understand your concerns but I think ideally we would enumerate our conditions and assumptions in our test harnesses instead of relying on variations in underlying system variance to catch bugs. (This can lead to difficult to reproduce test failures that don't provide much data to us and can be frustrating for our collaborators.)

For this PR, I'd prefer a fixture-ish approach that uses helper functions for setting up certain config conditions. Perhaps returning an entire config is a bit too much to take on now, but it would be nice to start collecting our different configs and modifiers for our testing into a single place.

Perhaps something like a `setPullRebaseConfig(repositoryPath, boolean)` or even `PullRebaseButNotFF(repositoryPath)` in a helper file?

**Comment by shiftkey** [comment]
> I'm not sure how the code snippet above relates to the question?

This is the ceremony I had in mind when you were asking about a "testing environment instead of being vulnerable to the underlying system's settings" - creating a new global config on disk, assigning this to the `HOME` environment variable, and then passing that through to the Git command to represent the "global" configuration (each API under test would need to support this). 

That sounds different to this:

> For this PR, I'd prefer a fixture-ish approach that uses helper functions for setting up certain config conditions.

This is interesting to me from the perspective of making setup more clear:

```diff
diff --git a/app/test/helpers/local-config.ts b/app/test/helpers/local-config.ts
new file mode 100644
index 000000000..0283d80f9
--- /dev/null
+++ b/app/test/helpers/local-config.ts
@@ -0,0 +1,11 @@
+import { Repository } from '../../src/models/repository'
+import { GitProcess } from 'dugite'
+
+export async function setupLocalConfig(
+  repository: Repository,
+  localConfig: Iterable<[string, string]>
+) {
+  for (const [key, value] of localConfig) {
+    await GitProcess.exec(['config', key, value], repository.path)
+  }
+}
diff --git a/app/test/unit/git/pull/ahead-and-behind-test.ts b/app/test/unit/git/pull/ahead-and-behind-test.ts
index 6ecff4bb4..356e61c8a 100644
--- a/app/test/unit/git/pull/ahead-and-behind-test.ts
+++ b/app/test/unit/git/pull/ahead-and-behind-test.ts
@@ -13,6 +13,7 @@ import {
 } from '../../../helpers/repository-scaffolding'
 import { getTipOrError, getRefOrError } from '../../../helpers/tip'
 import { GitProcess } from 'dugite'
+import { setupLocalConfig } from '../../../helpers/local-config'
 
 const featureBranch = 'this-is-a-feature'
 const origin = 'origin'
@@ -59,14 +60,10 @@ describe('git/pull', () => {
       let newTip: Commit
 
       beforeEach(async () => {
-        await GitProcess.exec(
-          ['config', '--local', 'pull.rebase', 'false'],
-          repository.path
-        )
-        await GitProcess.exec(
-          ['config', '--local', 'pull.ff', 'false'],
-          repository.path
-        )
+        await setupLocalConfig(repository, [
+          ['pull.rebase', 'false'],
+          ['pull.ff', 'false'],
+        ])
 
         previousTip = await getTipOrError(repository)
```

It doesn't quite address the presence of the global config problem - we'd still need to pass in the new `HOME` environment variable for each Git operation under test. 

Would an API like ☝️ help unblock this PR?

**Comment by outofambit** [comment]
> This is the ceremony I had in mind

@shiftkey ah! thanks for clarifying. yeah i'm thinking we can override global, system-level configs with local configs in the repositories we use in tests.

> Would an API like ☝️ help unblock this PR?

👍 👍 👍 yes! this looks great.

**Comment by shiftkey** [comment]
@outofambit ok cool, I'll add that work into this PR and see how it changes things. There's some places where we change the config on-the-fly that I'll call out as being different to this sort of "setup" case we're discussing here.

File: app/test/unit/git/diff-test.ts [hunk 1]
```diff
@@ -348,6 +348,7 @@ describe('git/diff', () => {
         repo.path
       )
 
+      // change config on-the-fly to trigger the line endings change warning
       await GitProcess.exec(['config', 'core.autocrlf', 'true'], repo.path)
```
Comment (shiftkey) [inline app/test/unit/git/diff-test.ts]: This is the only place I've left untouched by this PR, but I've added a better comment here to explain why it's necessary to do this mid-test rather than as part of the repository setupo.

File: app/test/unit/git/log-test.ts [hunk 2]
```diff
@@ -34,11 +34,10 @@ describe('git/log', () => {
...
 
-      // ensure the test repository is configured to detect copies
-      await GitProcess.exec(
-        ['config', 'log.showSignature', 'true'],
-        repository.path
-      )
+      // ensure the default config is to try and show signatures
+      // this should be overriden by the `getCommits` function as it may not
+      // have a valid GPG agent configured
+      await setupLocalConfig(repository, [['log.showSignature', 'true']])
```
Comment (shiftkey) [inline app/test/unit/git/log-test.ts]: The comment attached to this setup wasn't even remotely accurate to what was being tested, so I updated that to better explain this test case.

**Comment by iAmWillShepherd** [comment]
Since this is tech-debt and @outofambit was involved in guiding the direction of this PR, I'm going to let it hang around until she gets a chance to take a look.
