### PR TITLE
fix manual conflict detection

### LINKED ISSUE #6693: binary file merge conflicts detection broken
version: Desktop `1.6.0`, `1.5.1`

## Steps to reproduce:

1. create a `bothModified` conflict for an image file
(create image in base branch, then edit in a feature branch and base branch, merge)
2. take no action to resolve conflicts

## Current Result:

screen shot 2019-01-23 at 7 07 46 am

## Desired Result:

Detect that this is a binary conflict and offer command line resolutions (or #6062)

## Notes

blocks #6062

### PR DESCRIPTION
**Pull request by outofambit**
~~🌵 🌵 **blocked by #6697** 🌵 🌵~~ 

## Overview

fixes #6693 

### Behavior _after_ this PR

1. screen shot 2019-01-24 at 12 21 02 pm

2. `git checkout --theirs imm.png`

3. screen shot 2019-01-24 at 12 21 23 pm

## Description

- tightens up tests around binary merge conflicts
- uses whether a file is considered binary by git to decide if it can have conflict markers

## Release notes

Notes: [Fixed] Fix manual conflict detection for binary files

### CODE REVIEW

File: app/src/lib/git/status.ts [hunk 1]
```diff
@@ -178,13 +197,21 @@ export async function getStatus(
...
   // if we have any conflicted files reported by status, let
-  const conflictState = mergeHeadFound
-    ? await getFilesWithConflictMarkers(repository.path)
-    : new Map<string, number>()
+  const conflictDetails = mergeHeadFound
+    ? {
+        conflictCountsByPath: await getFilesWithConflictMarkers(
+          repository.path
+        ),
+        binaryFilepaths: await getBinaryPaths(repository, 'MERGE_HEAD'),
```
Comment (shiftkey) [inline app/src/lib/git/status.ts]: I'm curious about the use of `MERGE_HEAD` here as the ref. Are you able to share how this helps with the underlying issue?

Comment (outofambit) [reply app/src/lib/git/status.ts]: yes! [git's CLI is a little weird around this.](https://git-scm.com/docs/git-diff#git-diff-emgitdiffemltoptionsgtltcommitgt--ltpathgt82308203) supplying `HEAD` (or no `rev` argument) to git diff compares your working tree to `HEAD`. supplying any other `rev` compares that `rev` to `HEAD`. so supplying `MERGE_HEAD` will compare it to `HEAD`.

does that make sense? this line effectively generates the diff between the two `HEAD`s of the merge. (and assumes that a merge is in progress due to the merge head check above.

Comment (outofambit) [reply app/src/lib/git/status.ts]: that sounds better to be explicit!

**Comment by outofambit** [comment]
🍏

**Comment by shiftkey** [comment]
Just tested "both added":

screen shot 2019-01-25 at 12 31 38 pm

```shellsession
$ git status
On branch master
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both added:      image.png

no changes added to commit (use "git add" and/or "git commit -a")
```

And "both modified":



```shellsession
$ git status
On branch master
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   image.png

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by outofambit** [comment]
yeah i’m digging into those. thanks!

**Comment by outofambit** [comment]
these intermittent test failures were due improper test setup and using `expect().resolves` in the jest tests (it hid the error logging and failed unrelated tests!). i also took the opporunity to extract out some logic from `getStatus` into `getConflictDetails`

**Comment by shiftkey** [comment]
>  (it hid the error logging and failed unrelated tests!)

Ugh, that's annoying. Nice work getting to the bottom of it!
