### PR TITLE
Fix continually being prompted to add the upstream

### LINKED ISSUE #3252: problem with upstream adding to forks
### Description

>just updated my client to 1.0.7
>
>but i get this dialog in a loop now:
fork
>
>two confusions here:
>- why is the current link identical to the expected one?
>- why do i see this dialog every time i switch to that fork? even after hitting `update` ?

from https://github.com/desktop/desktop/pull/3199#issuecomment-342520769

### Version

**GitHub Desktop version:** 1.0.7

**OS version:** Microsoft Windows [Version 10.0.16299.19]

### Steps to Reproduce

1. Switch to a fork in desktop app
2. Popup appears, hit `Update`
3. Switch to another repo and back to the same fork shortly after (or close app in between, doesn't matter)
4. Popup appears again

**Expected behavior:** Only show popup once

**Actual behavior:** Popup shows every time

**Reproduces how often:** always

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #3252

The case really doesn't matter so we could be more relaxed, but it also turns out the API doesn't use a consistent casing for usernames so could end up never matching.

### CODE REVIEW

**Comment by joshaber** [comment]
This is ready for review 🙏

File: app/src/lib/stores/helpers/find-upstream-remote.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+import { forceUnwrap } from '../../fatal-error'
+
+/** The name for a fork's upstream remote. */
+export const UpstreamRemoteName = 'upstream'
+
+/**
+ * Find the upstream remote based on the parent repository and the list of
+ * remotes.
+ */
+export function findUpstreamRemote(
```
Comment (j-f1) [inline app/src/lib/stores/helpers/find-upstream-remote.ts]: Might want to 📖 that this only works because GitHub is case-sensitive — the path part of a URL is case-sensitive unless the server normalizes case.

It might also be a good idea to automatically correct the remote’s case if the cases don’t match.
