### PR TITLE
Use `command` in our CLI script to prevent the use of aliases

### LINKED ISSUE #13935: GitHub CLI broken in M1 Monterey 12.2.1
### Describe the bug
Github CLI does not work on M1 Monterey 12.2.1 

### Version & OS

GitHub Desktop Version: 2.9.8 (x64)
OS: MacOS Monterey 12.2.1 M1

### Steps to reproduce the behavior

1. Open a Terminal
2. Enter the command: `github .`

### Expected behavior

It should open GitHub Desktop

### Actual behavior

It crashes with an error.

```
/usr/local/bin/github: line 13: /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop: No such file or directory
```

The `GitHub Desktop` executable exists in that path so not sure why this is erroring.

### PR DESCRIPTION
**Pull request by sergiou87**
Closes #13935

## Description
This PR changes our CLI script to use `command` to run `dirname` and `ls`, to avoid running into oddities caused by users' aliases around those commands.

## Release notes

Notes: [Fixed] Command Line Tool ignores command aliases set by user on macOS

### CODE REVIEW

File: app/static/darwin/github.sh [hunk 1]
```diff
@@ -5,8 +5,8 @@ function realpath() {
   /usr/bin/perl -e "use Cwd;print Cwd::abs_path(@ARGV[0])" "$0";
 }
 
-CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
-BINARY_NAME="$(ls "$CONTENTS/MacOS/")"
+CONTENTS="$(command dirname "$(command dirname "$(command dirname "$(command dirname "$(realpath "$0")")")")")"
+BINARY_NAME="$(TERM=dumb command ls "$CONTENTS/MacOS/")"
```
Comment (sergiou87) [inline app/static/darwin/github.sh:9]: I wanted to use `--color=none` as suggested in https://github.com/desktop/desktop/issues/13935#issuecomment-1050087225, but `--color` is not available on macOS older than Monterey. I _think_ just setting `TERM=dumb` achieves the same result, I'm waiting to see if @offirgolan can confirm 🤞

Comment (offirgolan) [reply app/static/darwin/github.sh:9]: That worked for me 😄

**Review by tidy-dev — APPROVED** [review]
✨  Nice fix!
