### PR TITLE
"Publish branch" modal window's default button doesn't work as default

### LINKED ISSUE #5777: "Publish branch" modal window's default button doesn't work as default
## Description
When you try to open a PR for an unpublished branch, a modal window is show. If you press _return_ on your keyboard, the cancel button is used instead of the publish branch (which has a default button treatment).

publish-branch

## Version
* GitHub Desktop: 1.4.1
* Operating system: macOS 10.14

## Steps to Reproduce
1. Create a new branch
2. Commit some changes
3. Press Cmd-R to open a PR
4. Press _return_

### Expected Behavior
Default button (_Publish Branch_) should be used

### Actual Behavior
_Cancel_ button is used

### PR DESCRIPTION
**Pull request by JKirkYuan**
This resolves #5777 

@outofambit! Please take a look when you have time 👍

### CODE REVIEW

**Comment by tierninho** [comment]
- [x] Tested the functionality and the default button is now `Publish`. `Enter` (and `space-bar`) result in publishing of the branch.

File: app/src/ui/branches/push-branch-commits.tsx [hunk 1]
```diff
@@ -71,12 +71,19 @@ export class PushBranchCommits extends React.Component<
...
 > {
+  private dialogButtonRef: HTMLButtonElement | null = null
   public constructor(props: IPushBranchCommitsProps) {
     super(props)
 
     this.state = { isPushingOrPublishing: false }
   }
 
+  public componentDidMount() {
+    if (this.dialogButtonRef) {
```
Comment (outofambit) [inline app/src/ui/branches/push-branch-commits.tsx]: Can we add a comment here explaining why we're doing this? something short is fine :)

**Comment by outofambit** [comment]
thank you @JKirkYuan!
