### PR TITLE
Diff check all logic iteration.

### LINKED ISSUE #18248: "Semantic check all button" does not always work
### The problem

Looks like it's #18201.

As you can see, it works for the group of 5 lines, but not for the group of 2 lines:

https://github.com/desktop/desktop/assets/1537591/2bc804b2-1908-4392-bb6d-98d0275cda8f

### Release version

3.3.10-beta1

### Operating system

Windows 11

### Steps to reproduce the behavior

_No response_

### Log files

[2024-03-04.desktop.beta.log](https://github.com/desktop/desktop/files/14478747/2024-03-04.desktop.beta.log)

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tidy-dev**
Fixes: https://github.com/desktop/desktop/issues/18248
xref: https://github.com/github/accessibility-audits/issues/7017

## Description

This PR:
1. Fixes the issue where if you scroll the first row out of the virtual scroll rendering, the check all control disappears.
2. Fixes the issue where one line is modified doesn't have a check all, but has a deleted and removed line check.
3. Uses the grids rendered row index to make the calculation of the height more performant by no longer looping through all the rows, but only a loop of the rendered rows and only the rows of the group. 
4. Makes the logic more performant by implementing a cache for the data that is obtained by looping through all the rows, but does not change on row re render.

Both 3-4 together have made it so that scrolling a file with lots of line (I tested on > 1000) no longer leads to noticeable increase in load time. 

### Screenshots
Check all for multiple rows with same line number:
Check all for multiple rows with same line number

Showing that the check all control no longer disappears when scrolling down,
Showing that the check all control no longer disappears when scrolling down

Showing that no longer have long periods of white screen when scrolling:
Showing that no longer have long periods of white screen when scrolling

## Release notes
Notes: [Fixed] Groups of  two rows that represent one line number change have a check all control.
[Fixed] Check all control does not disappear when first row in group is scrolled out of view.
[Improved] The check all rendering does not cause a lag rendering when scrolling.

### CODE REVIEW

File: app/src/ui/diff/diff-helpers.tsx [hunk 1]
```diff
@@ -207,6 +207,21 @@ export type SimplifiedDiffRow =
 
 export type ChangedFile = WorkingDirectoryFileChange | CommittedFileChange
 
+/**
+ * Whether the row is a type that represent a change (added, deleted, modified)
+ * in the diff. This is useful for checking to see if a row type would have
+ * something line 'hunkStartLine` on it.
```
Comment (sergiou87) [inline app/src/ui/diff/diff-helpers.tsx]: Nit:
```suggestion
 * something like 'hunkStartLine` on it.
```

**Review by sergiou87 — CHANGES_REQUESTED** [review]
Code looks good to me, only found a typo in a comment. It works great, I only found this small nit where hovering over the check all octicon doesn't use the pointer cursor:

https://github.com/desktop/desktop/assets/1083228/c47f6078-3ebf-4bd1-aff2-806d707f6552

One nice idea to discuss for a future PR (because I don't even know how to implement it 😓 ) would be to make the "check all" octicon sticky to the scroll, so it's always visible no matter how many lines are there in a hunk. I think that'd be nice to know whether the hunk is selected completely or only partially.

**Comment by tidy-dev** [comment]
> One nice idea to discuss for a future PR (because I don't even know how to implement it 😓 ) would be to make the "check all" octicon sticky to the scroll, so it's always visible no matter how many lines are there in a hunk. I think that'd be nice to know whether the hunk is selected completely or only partially. 

A version of this might not actually be difficult because I can just have the check all icons rendered on the "visible" check all control. I would have to try it tho.. it may be too flickery looking.... but there may be some other method using css sticky type approach on scroll..

**Comment by tidy-dev** [comment]
Fixed cursor pointer

**Comment by tidy-dev** [comment]
>  it may be too flickery looking

The idea I had definitely not good as renderer too slow and not quite always visible. Tho, I like the sticky scroll idea, I am going to table it for now as css sticky sorcery can be tedious and I am not 100% I can make it work.

**Review by sergiou87 — APPROVED** [review]
