### PR TITLE
restrict "Open in" context menu for files which are Danger Zone™

### LINKED ISSUE #2464: Open with external editor runs batch files on windows
### Description

Using the new **Open with external editor** feature results in `.cmd` files being run instead of opened in an editor.

I have VS Code installed, and the settings show it's the default editor, but the file isn't opened in it, nor are any others.

### Version

**GitHub Desktop version:** 0.7.3-beta3
**OS version:** Win10 CU

### Steps to Reproduce

1. Add a `.cmd` file to your repo
1. Right click on it and select `Open with external editor`
1. Watch the console open and the file run

**Expected behavior:** The file to open in the default editor of this type (for me it's Notepad/Notepad2) or the default editor selected in the application (VS Code in this case)

**Actual behavior:** The console opens and the file executes

**Reproduces how often:** Every time

### Logs

Nothing shows in the logs relating to opening/running the file.

#### Additional Information

None

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2464 in two ways:

 - updates the changed file context menu to mention "Default Program" to distinguish it from "Open in External Editor"
 - disables the menu item for known extensions that execute whe the `Open` verb is used by Electron as per [here](https://github.com/electron/electron/blob/eb63bea87c299b3c440d6a36ccced3cc9653e1c4/atom/common/platform_util_win.cc#L308-L315)

### CODE REVIEW

File: app/src/ui/changes/changed-file.tsx [hunk 1]
```diff
@@ -9,6 +9,8 @@ import { Checkbox, CheckboxValue } from '../lib/checkbox'
 
 const GitIgnoreFileName = '.gitignore'
 
+const RestrictedFileExtensions = ['.cmd', '.exe', '.bat', '.sh']
```
Comment (joshaber) [inline app/src/ui/changes/changed-file.tsx]: I don't fully understand the problem, but should we be at all worried that this is playing whack-a-mole?

Comment (say25) [inline app/src/ui/changes/changed-file.tsx]: Do we need to include .o files here?

**Comment by shiftkey** [comment]
> I'm not really sure why as openItem seems like the better fit, and I wonder if it'd have this same problem?

`openItem` suffers from the same issue

File: app/src/ui/changes/changed-file.tsx (hunk 1 above)
Comment (shiftkey) [inline app/src/ui/changes/changed-file.tsx]: Yeah, I don't intend for this to be a permanent solution. I'm just worried about the "executing arbitrary code" scenario and distrusting repositository content.
