### PR TITLE
git reset can use stdin on windows to avoid shell limits

### LINKED ISSUE #2833: spawn ENAMETOOLONG error on discarding files
### Description

Github Desktop still seems to have issues discarding a large number of files and will give a "spawn ENAMETOOLONG error". 

An issue was [already reported for this issue](https://github.com/desktop/desktop/issues/1668) but it was marked as resolved. 

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** Windows 10 Home - Version 1703 - OS Build 15063.608

### Steps to Reproduce

screenshot of issue

1. Have a large amount of files with staged changes
2. Right click on the bar which states the number of staged files and click discard changes

**Expected behavior:** Discard changes to files

**Actual behavior:** spawn ENAMETOOLONG error

**Reproduces how often:** 100%
### Logs

[2017-09-22.desktop.production.txt](https://github.com/desktop/desktop/files/1323148/2017-09-22.desktop.production.txt)

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2833

I stumbled upon this fix while looking at tidying up a warning mentioned in #2721:

```
2017-09-14T04:01:31.645Z - error: [ui] `git reset --mixed HEAD -- membercentral/assets/common/css/main.css` exited with an unexpected code: 128.
warning: --mixed with paths is deprecated; use 'git reset -- <paths>' instead.
```

That message has been around for a while, but then I found these flags on the Git for Windows docs:

screen shot 2017-09-26 at 1 02 53 pm

> **--stdin**
>   EXPERIMENTAL: Instead of taking list of paths from the command line, read list of paths from the standard input. Paths are separated by LF (i.e. one path per line) by default.
> 
> **-z**
>   EXPERIMENTAL: Only meaningful with --stdin; paths are separated with NUL character instead of LF.

It's not technically in git core (a recent version of the patch is discussed [here](https://public-inbox.org/git/3b0bad26045ed175f40f050e15b65cb6a8f2368c.1485520718.git.johannes.schindelin@gmx.de/)) so I've added tests here to ensure it doesn't disappear when updating Git down the track.

### CODE REVIEW

File: app/src/lib/git/reset.ts [hunk 1]
```diff
@@ -43,8 +43,8 @@ export async function reset(
   mode: GitResetMode,
   ref: string
 ): Promise<true> {
-  const modeFlag = resetModeToFlag(mode)
-  await git(['reset', modeFlag, ref, '--'], repository.path, 'reset')
+  const args = resetModeToArgs(mode, ref)
```
Comment (joshaber) [inline app/src/lib/git/reset.ts]: I _think_ we should still have the trailing `--` so that Git provides a better error message than complaining about ambiguity.

Comment (mingjusamyak) [reply app/src/lib/git/reset.ts]: 😂😂😂😂

Comment (shiftkey) [reply app/src/lib/git/reset.ts]: Not sure I understand. This is still the case for the non-Win32 shells:

https://github.com/desktop/desktop/blob/b8c18c3fae807f5e12ba04c513f973cf132da2a4/app/src/lib/git/reset.ts#L91-L94

Comment (shiftkey) [reply app/src/lib/git/reset.ts]: And in this case, the `--` is unnecessary because it doesn't provide any files.

Comment (shiftkey) [reply app/src/lib/git/reset.ts]: Ugh, I didn't realise this is only supported for mixed resets:



Back to the drawing board...

Comment (shiftkey) [reply app/src/lib/git/reset.ts]: Nevermind, the workaround wasn't too bad 📝

**Comment by joshaber** [comment]
🛥
