### PR TITLE
Commander of lines

### LINKED ISSUE #696: Command line tool
Desktop Classic for Mac includes a little command line tool you can install that lets you do things like `github .` to open the current directory in Desktop.

Should we do that in TNG as well? Does Windows do something similar?

### LINKED ISSUE #1759: Every update recreates desktop shortcut
### Description

Every time GitHub Desktop downloads a new version it recreates the desktop shortcut. I've deleted it multiple times because I don't want it there.

### Version

**GitHub Desktop version:** 0.5.8

**OS version:** `Microsoft Windows [Version 10.0.15063]`

### Steps to Reproduce

1. Install GitHub Desktop
2. Delete the desktop shortcut
3. Wait for a new build to be downloaded and installed in the background
4. Note that a new desktop shortcut has been created

**Expected behaviour:** The shortcut stays removed and is not recreated

**Actual behaviour:** The shortcut is recreated

**Reproduces how often:** 100% of the time when a new build is downloaded & installed.

### LINKED ISSUE #1863: Windows installer never completes installation
### Description

Installer goes into a loop, never finishing the install. No UI is shown at all.

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Clean install of Windows 10 Pro
2. Download and install
3. Installer never completes, looping a squirrel-task appoximately once per second

It looks like all the files are installed, but running GitHub Desktop.exe does not start the program.

**Expected behaviour:** Installer completes

**Actual behaviour:** Installer loops indefinitely

**Reproduces how often:** 100%

### Logs

Contents of `C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9\SquirrelSetup.log`: (complete)
```
2017-06-01 17.28.23> Program: Starting Squirrel Updater: --updateSelf=C:\Users\fr\AppData\Local\SquirrelTemp\Update.exe
2017-06-01 17.28.23> Program: About to wait for parent PID 8960
```

Content of `C:\Users\fr\AppData\Local\GitHubDesktop\SquirrelSetup.log`: (partial)
```
2017-06-01 17.28.23> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-01 17.28.23> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\fr\AppData\Local\GitHubDesktop
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\Desktop\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\Desktop\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-06-01 17.28.23> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-01 17.28.23> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\fr\AppData\Local\GitHubDesktop
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\fr\Desktop\GitHub Desktop.lnk
2017-06-01 17.28.23> ApplyReleasesImpl: About to save shortcut: C:\Users\fr\Desktop\GitHub Desktop.lnk (target C:\Users\fr\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\fr\AppData\Local\GitHubDesktop\app-0.5.9, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-01 17.28.23> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
[repeatedly]
```

#### Additional Information

New machine with AMD Ryzen CPU.

### LINKED ISSUE #1875: installer doesn't complete, missing `screen` module
### Description

Installer doesn't complete successfully, appears to get stuck in a loop

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Windows 10 x64 (Version 1703, OS Build 15063.332), ie Creators Update GA.

### Steps to Reproduce

1. Install GitHub Desktop

**Expected behaviour:** Installer completes and launches application

**Actual behaviour:** From @jstangroome: "it just pegs the CPU as "GitHub Desktop.exe" starts, launches a copy of itself, then dies, and repeats ad infinitum"

**Reproduces how often:** repeatable, even after cleaning folders at `%LOCALAPPDATA%\GitHubDesktop` and `%APPDATA%\GitHub Desktop`

### Logs

https://gist.github.com/jstangroome/82f832dd66be0e77c9f6e338bff2bced

```
2017-06-02T01:27:11.603Z - error: Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\jason\AppData\Local\GitHubDesktop\app-0.5.9\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as screen] (C:\Users\jason\AppData\Local\GitHubDesktop\app-0.5.9\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at o.exports (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\~\electron-window-state\index.js:19:1)
    at new T (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\app-window.ts:42:13)
    at S (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:294:18)
    at App.C.app.on (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:163:3)
```

### PR DESCRIPTION
**Pull request by joshaber**
~~_⚠️ Dependent on https://github.com/desktop/desktop/pull/1924 ⚠️_~~

Fixes #696 

On Windows, we'll automatically insert our `bin` directory into the user's `PATH`, like Atom and VS Code do. On Mac, the user will need to explicitly choose to install the tool.

While I was mucking around with Squirrel.Windows, I also fixed a few bugs:

Fixes #1875
Fixes #1759 
Fixes #1863

screen shot 2017-06-08 at 10 33 37 am

screen shot 2017-06-08 at 3 06 19 pm

### CODE REVIEW

**Comment by joshaber** [comment]
This is ready though it is dependent on https://github.com/desktop/desktop/pull/1924 🙏

**Comment by iAmWillShepherd** [comment]
Does this need to get reviewed since it's not being merged into `master`?

**Comment by joshaber** [comment]
It'll need to be reviewed, but only after #1924 lands.

**Comment by joshaber** [comment]
This is ready for 🦅 👀

File: app/src/main-process/squirrel-updater.ts [hunk 1]
```diff
@@ -1,34 +1,213 @@
...
+      let stdout = ''
+      child.stdout.on('data', data => {
+        stdout += data
+      })
+
+      child.on('close', code => {
+        if (code === 0) {
+          resolve(stdout)
+        } else {
+          reject(new Error(`Command failed: ${stdout}`))
```
Comment (01nad54) [inline app/src/main-process/squirrel-updater.ts]: не получилось

File: app/static/win32/github.bat [hunk 2]
```diff
@@ -0,0 +1,7 @@
+@echo off
+setlocal
+
+set ELECTRON_RUN_AS_NODE=1
+call "%~dp0..\..\..\GitHub Desktop.exe" "%~dp0..\cli.js" %*
```
Comment (joshaber) [inline app/static/win32/github.bat]: Yeah, I wasn't sure I cared. I made an attempt at having it work but my batch skills are not up to snuff. If we care, I'll probably need a hand to get this working.

Comment (shiftkey) [inline app/static/win32/github.bat]: Let's extract this to a `tech-debt` task, I don't it should hold up this.

File: app/src/cli/main.ts [hunk 3]
```diff
@@ -0,0 +1,18 @@
+import * as ChildProcess from 'child_process'
+import * as Path from 'path'
+
+const args = process.argv.slice(2)
+
+// At some point we may have other command line options, but for now we assume
+// the first arg is the path to open.
+const pathArg = args.length > 0 ? args[0] : ''
+const repositoryPath = Path.resolve(process.cwd(), pathArg)
```
Comment (joshaber) [inline app/src/cli/main.ts]: >Related: what should happen if we pass in an invalid path here?

So it currently still opens the "Add Local Repository" with an invalid path. I _think_ that's right.

File: app/src/main-process/squirrel-updater.ts [hunk 4]
```diff
@@ -1,34 +1,213 @@
...
     case '--squirrel-obsolete':
-      app.quit()
-      return true
+      return Promise.resolve()
+  }
+
+  return null
+}
+
+async function handleUpdated(): Promise<void> {
```
Comment (joshaber) [inline app/src/main-process/squirrel-updater.ts]: No, great shout 👍

File: app/static/win32/github.bat (hunk 2 above)
Comment (joshaber) [inline app/static/win32/github.bat]: 👍 https://github.com/desktop/desktop/issues/2150

**Comment by joshaber** [comment]
☄️

**Comment by toshimaru** [comment]
I'd like the PR to be merged! 😄

**Comment by joshaber** [comment]
🏤

File: app/src/main-process/squirrel-updater.ts [hunk 5]
```diff
@@ -1,34 +1,236 @@
...
+  let setxPath: string
+  const systemRoot = process.env['SystemRoot']
+  if (systemRoot) {
+    const system32Path = Path.join(systemRoot, 'System32')
+    setxPath = Path.join(system32Path, 'setx.exe')
+  } else {
+    setxPath = 'setx.exe'
+  }
+
+  await spawn(setxPath, ['Path', paths.join(';')])
```
Comment (shiftkey) [inline app/src/main-process/squirrel-updater.ts]: We don't refresh `process.env.PATH` for the current process after installing the shortcut, so launching a shell for the initial launch won't have the path to `github`.

**Comment by shiftkey** [comment]
This is looking pretty good, but I'm about to board a plane for holidays and I really don't want to rush this review. Gonna drop myself from the review.

File: app/src/main-process/squirrel-updater.ts (hunk 5 above)
Comment (joshaber) [inline app/src/main-process/squirrel-updater.ts]: We don't ever launch `github` from the app itself, tho, so it doesn't seem like that matters. Unless I'm misunderstanding you?

Comment (shiftkey) [inline app/src/main-process/squirrel-updater.ts]: But a user can then open a shell from in the app, which inherits the `PATH` from the parent process.

Comment (joshaber) [inline app/src/main-process/squirrel-updater.ts]: Ah, yeah, so the way Squirrel events work is you're meant to do some action and then quit ASAP. It's not a normal run of the app. So it shouldn't matter.

**Comment by joshaber** [comment]
@niik @iAmWillShepherd could one of you take a look at this? It'd be nice to get those Squirrel.Windows fixes out.

File: app/src/ui/cli-installed/cli-installed.tsx [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+      >
+        <DialogContent>
+          <div>
+            The command line tool has been installed at{' '}
+            <strong>{InstalledCLIPath}</strong>.
+          </div>
+        </DialogContent>
+        <DialogFooter>
+          <ButtonGroup>
+            <Button type="submit">OK</Button>
```
Comment (niik) [inline app/src/ui/cli-installed/cli-installed.tsx]: `Ok`?

File: app/src/ui/lib/install-cli.ts [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+  command: string,
+  args: ReadonlyArray<string>,
+  options?: { admin: boolean }
+) => number = require('runas')
+
+/** The path for the installed command line tool. */
+export const InstalledCLIPath = '/usr/local/bin/github'
+
+/** The path to the packaged CLI. */
+const PackagedPath = Path.resolve(__dirname, 'static', 'github.sh')
```
Comment (niik) [inline app/src/ui/lib/install-cli.ts]: @joshaber Is this gonna be static across versions on macOS? I don't know how that works at all

File: app/src/main-process/squirrel-updater.ts [hunk 8]
```diff
@@ -1,34 +1,236 @@
...
-      ChildProcess.spawn(updateDotExe, args, { detached: true })
-    } catch (error) {}
-  }
+const appFolder = Path.resolve(process.execPath, '..')
+const rootAppDir = Path.resolve(appFolder, '..')
+const updateDotExe = Path.resolve(Path.join(rootAppDir, 'Update.exe'))
+const exeName = Path.basename(process.execPath)
+
+// A lot of this code was cargo-culted from our Atom comrades:
+// https://github.com/atom/atom/blob/7c9f39e3f1d05ee423e0093e6b83f042ce11c90a/src/main-process/squirrel-update.coffee.
```
Comment (niik) [inline app/src/main-process/squirrel-updater.ts]: ❤️  for linking straight to this

File: app/src/main-process/squirrel-updater.ts [hunk 9]
```diff
@@ -1,34 +1,236 @@
...
+ * just launches the current version's CLI tool. Then, whenever we update, we
+ * rewrite the trampoline to point to the new, version-specific path. Bingo
+ * bango Bob's your uncle.
+ */
+async function writeCLITrampoline(): Promise<string> {
+  const binPath = getBinPath()
+  const appFolder = Path.resolve(process.execPath, '..')
+  const versionedPath = Path.relative(
+    binPath,
+    Path.join(appFolder, 'resources', 'app', 'static', 'github.bat')
```
Comment (niik) [inline app/src/main-process/squirrel-updater.ts]: It seems `atom` went with `.cmd` for their extension and so did `node.js`. I don't know if there's any real difference but perhaps it would be wise to stick to that convention?

File: app/src/main-process/main.ts [hunk 10]
```diff
@@ -121,11 +121,22 @@ process.on('uncaughtException', (error: Error) => {
...
+let willQuit = false
+
 if (__WIN32__ && process.argv.length > 1) {
-  if (handleSquirrelEvent(process.argv[1])) {
-    app.quit()
+  const arg = process.argv[1]
+  const promise = handleSquirrelEvent(arg)
+  if (promise) {
+    willQuit = true
+    promise
```
Comment (joshaber) [inline app/src/main-process/main.ts]: We can't `await` in the topmost scope, sadly.

>it seems this would be more readable if it returned a promise yielding true or false depending on whether it was handled or not.

I agree, but we need to synchronously set the `willQuit` variable to avoid doing anything in the `ready` handler later on. This is the fix to https://github.com/desktop/desktop/issues/1875. I'm open to any ideas you have on that.

File: app/src/main-process/squirrel-updater.ts (hunk 9 above)
Comment (joshaber) [inline app/src/main-process/squirrel-updater.ts]: >Path.join should take care of normalization for you

Oh nice! TIL.

>It seems atom went with .cmd for their extension and so did node.js. I don't know if there's any real difference but perhaps it would be wise to stick to that convention?

I don't care at all. I asked about this in chat a while back and got the answer that it doesn't matter: https://github.slack.com/archives/C17LP0XU3/p1496864546708077

File: app/src/ui/cli-installed/cli-installed.tsx (hunk 6 above)
Comment (joshaber) [inline app/src/ui/cli-installed/cli-installed.tsx]: On Mac I'd expect "OK".

File: app/src/ui/lib/install-cli.ts (hunk 7 above)
Comment (joshaber) [inline app/src/ui/lib/install-cli.ts]: I'm not entirely sure I understand what you're asking, so I'll just ramble 😛

The packaged path will be the path to the script in the app bundle. The app bundle can be put anywhere. The user can move the app bundle at anytime. That would break the symlink and they'd need to reinstall it. This was the same with Classic Mac.

**Comment by joshaber** [comment]
🇱🇰

File: app/src/main-process/main.ts (hunk 10 above)
Comment (niik) [inline app/src/main-process/main.ts]: > We can't await in the topmost scope, sadly.

Ah, that's what I was missing.

File: app/src/ui/lib/install-cli.ts (hunk 7 above)
Comment (niik) [inline app/src/ui/lib/install-cli.ts]: Gotcha

**Comment by zeke** [comment]
Thank you, Team Desktop. 💛

**Comment by feross** [comment]
Excellent! 🎉
