### PR TITLE
refresh issues when user manually fetches

### LINKED ISSUE #4076: Allow for issues to be manually refreshed
### Description

When creating issues on GitHub while GitHub Desktop is open, they won't show up when referencing them in commit field (#`issue-number`).

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

1. Open GitHub Desktop
1. Create an issue on GitHub
1. GitHub Desktop fails to show it when referencing the issue in commit field.

**Expected behavior:** Being able to select the issue that was recently created.

**Actual behavior:** Fails to show the issue.

**Reproduces how often:** 100%

#### Additional Information

No additional information 😜

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #4076

I didn't like how we use `update` and `fetch` in this API, so I took the chance to clean this up so it looked similar to the PR APIs inside `app-store` and other components - these behave similarly in terms of handling the refreshing under the hood, might as well ensure they're named consistently.

### CODE REVIEW

File: app/src/lib/stores/app-store.ts [hunk 1]
```diff
@@ -2439,6 +2439,9 @@ export class AppStore extends TypedBaseStore<IAppState> {
 
         if (fetchType === FetchType.UserInitiatedTask) {
```
Comment (niik) [inline app/src/lib/stores/app-store.ts]: Why are we only doing this for manual fetches? Shouldn't we be refreshing PRs and issues in the background?

Comment (shiftkey) [reply app/src/lib/stores/app-store.ts]: We avoid doing this for background fetching because we already have a `PullRequestUpdater` that's working in the background and updating every 10mins - #3502 has some more context for why we went down that path. I think the goal here is to force a refresh of PRs as a part of the user fetching changes from the remote repository.

We don't really have an equivalent for fetching issues in the background currently - `IssuesAutocompletionProvider` manages this inside it's own `ThrottledScheduler` which runs ever minute, but this is only started _after_ an autocompletion request is initiated - and the list won't be refreshed when it does have new results (I think you'd need to change the input to re-render the list).

https://github.com/desktop/desktop/blob/d73112a9fc9ca4a953697ae471d3942ae8e07d7b/app/src/ui/autocompletion/issues-autocompletion-provider.tsx#L51-L59
