### PR TITLE
ensure creating branch with detached HEAD does not revert to default branch

### LINKED ISSUE #6085: Creating branch from detached HEAD branches from master
## Description
While in a detached HEAD state, creating a new branch results in that branch being branched from master instead of the currently checked out commit.

## Version
* GitHub Desktop:
1.4.3
* Operating system:
Windows

## Steps to Reproduce
1. From terminal: `git checkout <some_commit_hash>`
2. In GitHub Desktop: Branch -> New branch...
3. Type a name.
4. Create branch.

### Expected Behavior
The newly created branch should point to `<some_commit_hash>`, as the dialog states `You do not currently have any branch checked out (your HEAD reference is detached). As such your new branch will be based on your currently checked out commit (<some_commit_hash>).`

### Actual Behavior
The newly created branch points to the HEAD of master.

## Additional Information
This happens on 1.4.2-linux1 from @shiftkey's [fork](https://github.com/shiftkey/desktop) as well.

### Logs
Not applicable

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

~~🌵🌵🌵🌵 **Builds upon #6100, go review that first**  🌵🌵🌵🌵~~

**Closes #6085**

## Description

This PR does a few things around the original bug:

- extract function from inside component - 6fc99d6
- wrap it in tests to catch regressions  - a599356
- make the tests fail so that we can see the bug - 87ec4b1
- finally, fix the bug by respecting when the repository is in detached HEAD - e463cd4

## TODO

 - [x] rebase branch on `master` once #6100 is merged

## Release notes

Notes: Creating a branch when in detached HEAD state no longer reverts to using the default branch

### CODE REVIEW

**Comment by shiftkey** [comment]
Rebased and ready for proper review now :tada:

File: app/src/lib/create-branch.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
+import { TipState, Tip } from '../models/tip'
+import { StartPoint, Branch } from '../models/branch'
+
+type BranchInfo = {
```
Comment (iAmWillShepherd) [inline app/src/lib/create-branch.ts]: Any reason why a type alias was chosen over an interface?

**Review by iAmWillShepherd — APPROVED** [review]

File: app/src/lib/create-branch.ts (hunk 1 above)
Comment (shiftkey) [reply app/src/lib/create-branch.ts]: - convenience (it's not exported and was relatively trivial)
- my growing dislike of the `I` prefix on interfaces that this will require, and my growing preference of just using `type` unless we're looking to do object-oriented work in the codebase

**Comment by bangke213** [comment]
What does this mean

**Comment by bangke213** [comment]
it's clear what this data means

**Comment by kaster14** [comment]
This functionality is broken again, I am having the same problem as in this issue and #6085
In my use case I have a dev branch I merge downstream to other branches which have additional commits that don't exist on dev.

From GH desktop on my feature branch if I right on a commit and select "Checkout commit" it takes me to that commit on Dev branch and not on my feature branch so my additional commits on my feature branch disappear from the commit history.

I did have one instance where this process worked correctly and used my feature branch (which made me look crazy to my coworkers when I was reviewing this with them! :-D ), but then when I did it a second time it reverted to the dev branch history and I was exonerated. I do not know how to repeat that intermittent functionality.

I'm running windows 10 Pro
image

**Comment by shiftkey** [comment]
@kaster14 I would advise opening a fresh issue and filling out the template
