### PR TITLE
use shift for shortcut chord instead of alt

### LINKED ISSUE #2607: Opens a new chrome tab on ]
### Description

With hungarian layout pressing the `]` character is done with altgr+G which the Github application catches as ctrl+alt+g which opens a chrome tab.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Press alt gr+G

**Expected behavior:** It does not open a chrome tab.

**Actual behavior:** Opens a chrome tab.

**Reproduces how often:** Every time :)

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #2607 (again)

Six of our existing shortcuts use `CmdOrCtrl+Shift` for the chorded shortcut, and two use `CmdOrCtrl+Alt`. And as mentioned in this comment https://github.com/desktop/desktop/issues/2607#issuecomment-328385687 some keyboards layouts will handle `Ctrl+Alt` differently on Windows.

As we can't rely on handling `AltGr` separately to `Alt`, let's just avoid it completely. This is What Windows Does™.

@joshaber any objections to this on the macOS side?

### CODE REVIEW

File: app/src/main-process/menu/build-default-menu.ts [hunk 1]
```diff
@@ -165,7 +165,7 @@ export function buildDefaultMenu(
       {
         label: '&Reload',
         id: 'reload-window',
-        accelerator: 'CmdOrCtrl+Alt+R',
+        accelerator: 'CmdOrCtrl+Shift+R',
```
Comment (joshaber) [inline app/src/main-process/menu/build-default-menu.ts]: Since this one's just available on dev builds, I'd suggest keeping it `Alt`. That way we can use `CmdOrCtrl+Shift+R` for a user-facing feature down the road if needed.

**Comment by shiftkey** [comment]
:apple:
