### PR TITLE
Disable textbox if there are no branches to compare

### LINKED ISSUE #4559: Show message when no branches to compare
## Description
A suggestion for an enhancement. When there are no branches other than master and going to compare and select a branch from the list the pane shows "Sorry, I can't find that branch" when really there are just no other branches to select.

## Version
* GitHub Desktop: 1.1.2-beta4
* Operating system: Mac and Windows

## Steps to Reproduce
1. Use a repository that only has master branch
2. Go to `Compare` tab
3. Click in `Select branch to compare...`

### Expected Behavior
See a message like "There are no branches to compare"

### Actual Behavior
The current message says: "Sorry, I can't find that branch"

no other branches exist

### PR DESCRIPTION
**Pull request by iAmWillShepherd**
Fixes #4559.

Instead of showing a message saying there is nothing to compare, this PR goes one step further by not allowing the textbox to be selected when there are fewer than 2 branches in the repo.

**Before**
See original issue...

**After**

### CODE REVIEW

File: app/src/ui/history/compare.tsx [hunk 1]
```diff
@@ -117,12 +117,17 @@ export class CompareSidebar extends React.Component<
...
     const formState = this.props.compareState.formState
+    const numBranches = this.props.compareState.allBranches.length
     const placeholderText =
-      formState.kind === ComparisonView.None
+      numBranches <= 1
         ? __DARWIN__
-          ? 'Select Branch to Compare...'
-          : 'Select branch to compare...'
-        : undefined
+          ? 'There Are No Branches to Compare'
```
Comment (iAmWillShepherd) [inline app/src/ui/history/compare.tsx]: Sorry about the nested ternary. If there were a function that could handle casing for me, I could remove the nesting.

**Comment by iAmWillShepherd** [comment]
@meaghanlewis how do you feel about shortening the placeholder message to say _No Branches to Compare_?

**Comment by meaghanlewis** [comment]
This LGTM, thanks @iAmWillShepherd ✨

**Comment by j-f1** [comment]
How about “Nothing to Compare With”? Also, can you make the area behind the Octicon gray instead of white?

**Comment by donokuda** [comment]
> How about “Nothing to Compare With”? Also, can you make the area behind the Octicon gray instead of white?

Good catch 👀 I didn't even notice that in the screenshot!

File: app/src/ui/history/compare.tsx [hunk 2]
```diff
@@ -117,12 +117,17 @@ export class CompareSidebar extends React.Component<
 
   public render() {
     const formState = this.props.compareState.formState
+    const numBranches = this.props.compareState.allBranches.length
```
Comment (shiftkey) [inline app/src/ui/history/compare.tsx]: :art: could we just use `allBranches` here instead of `numBranches`?

File: app/src/ui/history/compare.tsx (hunk 1 above)
Comment (shiftkey) [reply app/src/ui/history/compare.tsx]: I think `Are` should be lower-cased here. But I'm also :thumbsup: to `No Branches to Compare` here which would make that change unnecessary.

Comment (shiftkey) [inline app/src/ui/history/compare.tsx]: If you're worried about the nesting, why not extract to a function?

```ts
function getPlaceholderText(compareState: ICompareState): string | undefined {
  const formState = compareState.formState
  if (compareState.allBranches.length <= 1) {
    return __DARWIN__
      ? 'There Are No Branches to Compare'
      : 'There are no branches to compare'
  } else if (formState.kind === ComparisonView.None) {
    return __DARWIN__
      ? 'Select Branch to Compare...'
      : 'Select branch to compare...'
  } else {
    return undefined
  }
}
```

Comment (japan) [reply app/src/ui/history/compare.tsx]: Most style guides ask for all verbs to be capitalised in titles and headings. _"Capitalize My Title"_ is a great tool when in doubt - https://capitalizemytitle.com

Comment (shiftkey) [reply app/src/ui/history/compare.tsx]: @japan thanks for the tip - that will definitely help for the future!

**Comment by iAmWillShepherd** [comment]
@j-f1 @donokuda , I've opened a separate issue to track the textbox color.

**Comment by tierninho** [comment]
Found an edge case that makes this reproducible. 

If no branches exist, and user selects the `Compare to Branch` option from the Branch menu, then we still see:

screen shot 2018-09-21 at 9 46 56 am

Perhaps the fix can be folded in to https://github.com/desktop/desktop/issues/5603 ?

1.4.1-beta0, mac
