### PR TITLE
Wrap the parsed error in an API error

### LINKED ISSUE #2279: Error message is incorrect
When pushing a repo to Github.com; it fails saying there is no internet checking however it should say you do not have a private plan. As I mentioned in my previous issue, #2165  it should be unticked by default.

All that needs to happen is that the error message says "You do not have a paid plan, please upgrade" or that the box is unchecked by default.

Image showing what is happening

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #2279

This is why it'd be nice to have typed `throws` declarations :disappointed:

### CODE REVIEW

File: app/src/lib/http.ts [hunk 1]
```diff
@@ -133,7 +133,7 @@ export async function parsedResponse<T>(response: Response): Promise<T> {
       throw new APIError(response, null)
     }
 
-    throw apiError
+    throw new APIError(response, apiError)
```
Comment (niik) [inline app/src/lib/http.ts]: Just nitpicking but could we move this up into the `try` block and thus get rid of the `apiError` let variable all together?

```ts
try {
  throw new APIError(response, await deserialize<IAPIError>(response))
} catch {
  throw new APIError(response, null)
}
```

Comment (j-f1) [inline app/src/lib/http.ts]: No, because that would trigger the `catch` block.

Comment (niik) [inline app/src/lib/http.ts]: Doh! It's getting too late in the day for me to be reviewing PRs.
