### PR TITLE
Reenable Menu Items For Removed Repo

### LINKED ISSUE #1776: Allow user to remove missing repo from the menu
The `remove` option is missing from the repo menu when user needs to remove a bad repo. Although technically it may not be a repo yet, but it does show in the Repo list. Yes, there are other methods to remove it, but the menu item should ideally be one of them.

screen shot 2017-05-25 at 2 20 28 pm

Reproduce:
- drag a repo into Desktop that has the wrong location

v0.5.8, OS X 10.11.5

### PR DESCRIPTION
**Pull request by say25**
- Fixes #1776
- Allow to View Repo or Remove when Missing via menu
- Check for missing before warning about deleting

### CODE REVIEW

File: app/src/lib/menu-update.ts [hunk 1]
```diff
@@ -155,8 +155,15 @@ function getMenuState(state: IAppState): Map<MenuIDs, IMenuItemState> {
     menuStateBuilder.setEnabled('pull', hasPublishedBranch && !networkActionInProgress)
     menuStateBuilder.setEnabled('create-branch', !tipStateIsUnknown)
   } else {
-    for (const id of repositoryScopedIDs) {
-      menuStateBuilder.disable(id)
+    if (selectedState && selectedState.type === SelectionType.MissingRepository) {
+      menuStateBuilder.enable('view-repository-on-github')
```
Comment (joshaber) [inline app/src/lib/menu-update.ts]: If the repository isn't a GitHub repository (i.e., doesn't have a `gitHubRepository`), this should be disabled.

File: app/src/lib/menu-update.ts [hunk 2]
```diff
@@ -155,8 +155,15 @@ function getMenuState(state: IAppState): Map<MenuIDs, IMenuItemState> {
...
+      menuStateBuilder.enable('remove-repository')
+    } else {
```
Comment (joshaber) [inline app/src/lib/menu-update.ts]: Doesn't this mean, e.g., `open-working-directory` will still be enabled for missing repositories?

Comment (say25) [inline app/src/lib/menu-update.ts]: oddly enough, no because first time this code gets hit selectedState is null so they all get disabled and second time this code gets hit only `'view-repository-on-github'` and `'remove-repository'` get enabled

Comment (say25) [inline app/src/lib/menu-update.ts]: but I completely agree that is me taking advantage of the way it executes and should be fixed

**Comment by say25** [comment]
Replied in line to your feedback. fixed it because I believe you are write and it should be better than it is in the end though

**Comment by joshaber** [comment]
This looks good, thanks @say25!
