### PR TITLE
avoid resolving conflicts using "Open in External Editor" flow if no editors found

### LINKED ISSUE #6060: If no default editor found, user cannot use Merge Conflicts
If no default editor found, Desktop prompts the user to download Atom, thus disrupting the Merge Conflict flow as other git actions need to be resolved before continuing with Merge Conflict

oct-31-2018 10-53-32
oct-31-2018 10-55-34

Alternatively, I have seen this error too:
```
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

Reproduce:
- Remove your editors, restart Desktop
- Attempt a merge conflict, click `open in editor` button

Logs:
```
2018-10-31T17:50:55.535Z - info: [ui] launching: 1.5.0-beta2 (Mac OS 10.13.6)
2018-10-31T17:50:55.536Z - info: [ui] execPath: '/Applications/Beta Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2018-10-31T17:51:25.404Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PRlist - tierninho (has token)
2018-10-31T17:52:03.465Z - error: [ui] `git merge origin/ccc` exited with an unexpected code: 1.
Auto-merging .gitignore
CONFLICT (content): Merge conflict in .gitignore
Automatic merge failed; fix conflicts and then commit the result.

(The error was parsed as 7: We found some conflicts while trying to merge. Please resolve the conflicts and commit the changes.)
2018-10-31T17:52:12.709Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PRlist - tierninho (has token)
2018-10-31T17:52:12.732Z - error: [ui] `git -c credential.helper= checkout --progress origin/ccc -b ccc --recurse-submodules --` exited with an unexpected code: 1.
.gitignore: needs merge

error: you need to resolve your current index first

2018-10-31T17:52:56.924Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: NEWtest - tierninho (has token)
2018-10-31T17:52:57.979Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.048s)
2018-10-31T17:52:58.377Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: asdasdasddsdss - tierninho (has token)
2018-10-31T17:52:59.937Z - info: [ui] Background fetch for 12 repositories took 4.745sec
2018-10-31T17:53:55.816Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PRlist - tierninho (has token)
2018-10-31T17:53:55.837Z - error: [ui] `git -c credential.helper= checkout --progress origin/ccc -b ccc --recurse-submodules --` exited with an unexpected code: 1.
.gitignore: needs merge

error: you need to resolve your current index first

2018-10-31T17:54:46.240Z - error: [ui] `git merge origin/ccc` exited with an unexpected code: 128.
error: Your local changes to the following files would be overwritten by merge:
	.gitignore
Please commit your changes or stash them before you merge.
Aborting
```

tested in: 1.5.0-beta2, mac

### PR DESCRIPTION
**Pull request by shiftkey**
## Overview

**Closes #6060**

## Description

- [x] lift error out of `findEditorOrDefault`, make `App` responsible for that, and return `null` if no editors can be found
 - [x] update `MergeConflictsDialog` to resolve the editor after mounting, and not show the button if the editor cannot be found
 - [x] test happy path when an editor can be found -> user can resolve conflicts in editor
 - [x] test sad path when not editors can be found  -> buttons are disabled

## Release notes

This is related to a new feature that hasn't yet made it to production

Notes: no-notes

### CODE REVIEW

**Comment by shiftkey** [comment]
Here's what the conflicts dialog looks like when we're unable to find any editor:

**Comment by shiftkey** [comment]
@billygriffin @ampinsk @outofambit just going to call out what I'd like input on from a UX side as part of addressing this bug:

 - given all the whitespace on the right-hand column when you don't have an active editor, should we try and make use of that space? i'll see if i can put together a screenshot of what this looks like with long paths
 - should we make the command line link more prominent - i.e. above the list of files - if that's what they need to use?

**Comment by billygriffin** [comment]
Recap of discussion with @shiftkey, @ampinsk, @tierninho, and me:

From @shiftkey's screenshot in https://github.com/desktop/desktop/pull/6109#issuecomment-436302543, we'll add in buttons as normal next to each conflict.

- The buttons will say "Open in editor," cased appropriately
- The buttons will be disabled
- Hovering over each button will have a tooltip that says: "No editor configured in `Preferences > Advanced`"

**Comment by shiftkey** [comment]
One extra thing:

> "No editor configured in `Preferences > Advanced`"

This is a platform-specific label too (`Preferences` on macOS, `Options` on the others)

**Comment by shiftkey** [comment]
Some updated screenshots based on the feedback from above:

**Comment by tierninho** [comment]
LGTM!

File: app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx [hunk 1]
```diff
@@ -39,8 +81,20 @@ const cancelButtonString = 'Abort merge'
...
-  {}
+  IMergeConflictsDialogState
 > {
+  public constructor(props: IMergeConflictsDialogProps) {
+    super(props)
+
+    this.state = { foundExternalEditor: null }
+  }
+
+  public async componentDidMount() {
```
Comment (outofambit) [inline app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx]: blocking:
what do you think about doing this lookup in `app.tsx` and `appStore`? i'd like to avoid introducing state here as a local callback/re-render mechanism. i think routing this through `dispatcher`, `appStore`, resulting in a `setState` at the app level (which would cause this to rerender) would keep this more global logic out of this component. it would also enable us to rerender this component if in the future something changes the editor state from the background without any additional logic.

Comment (shiftkey) [reply app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx]: The biggest headache I had here was that there wasn't an ideal spot to perform this check aside from pushing it all the way back around.

Some other things I considered:

 - `App.currentPopupContent` - the component that shows the dialog - doesn't support doing any async work there
 - pushing this further out to the code that wants to open `PopupType.MergeConflicts` meant having to make changes in four different places
 - I wanted to avoid adding more global state until I could better organize the state to group preferences (which is what `selectedExternalEditor` is currently)

I'll try this pushing this through `dispatcher` and see how it feels after addressing the conflicts.

Comment (shiftkey) [reply app/src/ui/merge-conflicts/merge-conflicts-dialog.tsx]: Check out 4ea8718 and 28e137e and see if that helps
