### PR TITLE
fix regression for keyboard layouts that overwrite character before cursor

### LINKED ISSUE #3354: Microsoft Pinyin input method not working
### Description

使用 GitHub Desktop 新建一个库并为新的库添加描述信息，在用微软拼音输入法输入中文时，会显示一连串的拼音，选择汉字后拼音还会存在

### Version

GitHub Desktop version:  1.0.9

**OS version: Microsoft Windows 10.0.10240

### Steps to Reproduce

1、打开 Github Desktop
2、选择菜单： File > new repository 
3、聚焦到 Description 输入框
4、将输入法切换到微软拼音
5、随意输入汉字就能发现问题

**Expected behavior:** 

正确的输入库的描述

**Actual behavior:** 

输入的描述里包含有汉字的拼音

**Reproduces how often:**

一直出现

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #3354 by being more careful with `setState` inside `text-box` rather than managing things ourselves:

 - [x] revert caret management code
 - [x] confirm original issue #2222 still reproducible
 - [x] pull in [this work](https://github.com/reactjs/react-redux/issues/525#issuecomment-254852039) into our `TextBox` to better manage re-rendering...

### CODE REVIEW

**Comment by shiftkey** [comment]
Here it is in action:

File: app/src/ui/lib/text-box.tsx [hunk 1]
```diff
@@ -143,21 +110,29 @@ export class TextBox extends React.Component<ITextBoxProps, ITextBoxState> {
...
       this.props.onChange(event)
     }
 
-    if (this.props.onValueChanged && !event.defaultPrevented) {
-      this.props.onValueChanged(event.currentTarget.value)
-    }
+    const defaultPrevented = event.defaultPrevented
+
+    this.setState({ value }, () => {
+      if (this.props.onValueChanged && !defaultPrevented) {
```
Comment (shiftkey) [inline app/src/ui/lib/text-box.tsx]: Doing this in the callback to `setState` means that we know the state has been applied _before_ we raise the callback (and potentially trigger `componentWillReceiveProps` again).

Comment (iAmWillShepherd) [reply app/src/ui/lib/text-box.tsx]: TIL `setState` accepts a callback function.
